services:
  igloo_db:
    container_name: igloo_db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: igloo
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data

  igloo_cache:
    container_name: igloo_cache
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis:/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio_data:

