/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthTrailerRouteImport } from './routes/_auth/trailer'
import { Route as AuthSettingsRouteRouteImport } from './routes/_auth/settings/route'
import { Route as AuthMusicIndexRouteImport } from './routes/_auth/music/index'
import { Route as AuthMusicPlaylistIdRouteImport } from './routes/_auth/music/playlist.$id'
import { Route as AuthMusicMusicianIdRouteImport } from './routes/_auth/music/musician.$id'
import { Route as AuthMusicAlbumIdRouteImport } from './routes/_auth/music/album.$id'
import { Route as AuthMoviesPlayIdRouteImport } from './routes/_auth/movies/play.$id'

const LoginIndexLazyRouteImport = createFileRoute('/login/')()
const AuthIndexLazyRouteImport = createFileRoute('/_auth/')()
const AuthTvShowsIndexLazyRouteImport = createFileRoute('/_auth/tv-shows/')()
const AuthSettingsIndexLazyRouteImport = createFileRoute('/_auth/settings/')()
const AuthPhotosIndexLazyRouteImport = createFileRoute('/_auth/photos/')()
const AuthMoviesIndexLazyRouteImport = createFileRoute('/_auth/movies/')()
const AuthSettingsPlaybackLazyRouteImport = createFileRoute(
  '/_auth/settings/playback',
)()
const AuthSettingsLibrariesLazyRouteImport = createFileRoute(
  '/_auth/settings/libraries',
)()
const AuthSettingsAccountLazyRouteImport = createFileRoute(
  '/_auth/settings/account',
)()
const AuthMoviesInTheatersIdLazyRouteImport = createFileRoute(
  '/_auth/movies/in-theaters/$id',
)()

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexLazyRoute = LoginIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))
const AuthIndexLazyRoute = AuthIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/index.lazy').then((d) => d.Route))
const AuthTrailerRoute = AuthTrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTvShowsIndexLazyRoute = AuthTvShowsIndexLazyRouteImport.update({
  id: '/tv-shows/',
  path: '/tv-shows/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/tv-shows/index.lazy').then((d) => d.Route),
)
const AuthSettingsIndexLazyRoute = AuthSettingsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/settings/index.lazy').then((d) => d.Route),
)
const AuthPhotosIndexLazyRoute = AuthPhotosIndexLazyRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/photos/index.lazy').then((d) => d.Route),
)
const AuthMoviesIndexLazyRoute = AuthMoviesIndexLazyRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/movies/index.lazy').then((d) => d.Route),
)
const AuthMusicIndexRoute = AuthMusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsPlaybackLazyRoute =
  AuthSettingsPlaybackLazyRouteImport.update({
    id: '/playback',
    path: '/playback',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/settings/playback.lazy').then((d) => d.Route),
  )
const AuthSettingsLibrariesLazyRoute =
  AuthSettingsLibrariesLazyRouteImport.update({
    id: '/libraries',
    path: '/libraries',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/settings/libraries.lazy').then((d) => d.Route),
  )
const AuthSettingsAccountLazyRoute = AuthSettingsAccountLazyRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/settings/account.lazy').then((d) => d.Route),
)
const AuthMoviesInTheatersIdLazyRoute =
  AuthMoviesInTheatersIdLazyRouteImport.update({
    id: '/movies/in-theaters/$id',
    path: '/movies/in-theaters/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/movies/in-theaters.$id.lazy').then((d) => d.Route),
  )
const AuthMusicPlaylistIdRoute = AuthMusicPlaylistIdRouteImport.update({
  id: '/music/playlist/$id',
  path: '/music/playlist/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMusicMusicianIdRoute = AuthMusicMusicianIdRouteImport.update({
  id: '/music/musician/$id',
  path: '/music/musician/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMusicAlbumIdRoute = AuthMusicAlbumIdRouteImport.update({
  id: '/music/album/$id',
  path: '/music/album/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMoviesPlayIdRoute = AuthMoviesPlayIdRouteImport.update({
  id: '/movies/play/$id',
  path: '/movies/play/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexLazyRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/trailer': typeof AuthTrailerRoute
  '/login/': typeof LoginIndexLazyRoute
  '/settings/account': typeof AuthSettingsAccountLazyRoute
  '/settings/libraries': typeof AuthSettingsLibrariesLazyRoute
  '/settings/playback': typeof AuthSettingsPlaybackLazyRoute
  '/music/': typeof AuthMusicIndexRoute
  '/movies/': typeof AuthMoviesIndexLazyRoute
  '/photos/': typeof AuthPhotosIndexLazyRoute
  '/settings/': typeof AuthSettingsIndexLazyRoute
  '/tv-shows/': typeof AuthTvShowsIndexLazyRoute
  '/movies/play/$id': typeof AuthMoviesPlayIdRoute
  '/music/album/$id': typeof AuthMusicAlbumIdRoute
  '/music/musician/$id': typeof AuthMusicMusicianIdRoute
  '/music/playlist/$id': typeof AuthMusicPlaylistIdRoute
  '/movies/in-theaters/$id': typeof AuthMoviesInTheatersIdLazyRoute
}
export interface FileRoutesByTo {
  '/trailer': typeof AuthTrailerRoute
  '/': typeof AuthIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/settings/account': typeof AuthSettingsAccountLazyRoute
  '/settings/libraries': typeof AuthSettingsLibrariesLazyRoute
  '/settings/playback': typeof AuthSettingsPlaybackLazyRoute
  '/music': typeof AuthMusicIndexRoute
  '/movies': typeof AuthMoviesIndexLazyRoute
  '/photos': typeof AuthPhotosIndexLazyRoute
  '/settings': typeof AuthSettingsIndexLazyRoute
  '/tv-shows': typeof AuthTvShowsIndexLazyRoute
  '/movies/play/$id': typeof AuthMoviesPlayIdRoute
  '/music/album/$id': typeof AuthMusicAlbumIdRoute
  '/music/musician/$id': typeof AuthMusicMusicianIdRoute
  '/music/playlist/$id': typeof AuthMusicPlaylistIdRoute
  '/movies/in-theaters/$id': typeof AuthMoviesInTheatersIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/trailer': typeof AuthTrailerRoute
  '/_auth/': typeof AuthIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/_auth/settings/account': typeof AuthSettingsAccountLazyRoute
  '/_auth/settings/libraries': typeof AuthSettingsLibrariesLazyRoute
  '/_auth/settings/playback': typeof AuthSettingsPlaybackLazyRoute
  '/_auth/music/': typeof AuthMusicIndexRoute
  '/_auth/movies/': typeof AuthMoviesIndexLazyRoute
  '/_auth/photos/': typeof AuthPhotosIndexLazyRoute
  '/_auth/settings/': typeof AuthSettingsIndexLazyRoute
  '/_auth/tv-shows/': typeof AuthTvShowsIndexLazyRoute
  '/_auth/movies/play/$id': typeof AuthMoviesPlayIdRoute
  '/_auth/music/album/$id': typeof AuthMusicAlbumIdRoute
  '/_auth/music/musician/$id': typeof AuthMusicMusicianIdRoute
  '/_auth/music/playlist/$id': typeof AuthMusicPlaylistIdRoute
  '/_auth/movies/in-theaters/$id': typeof AuthMoviesInTheatersIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/trailer'
    | '/login/'
    | '/settings/account'
    | '/settings/libraries'
    | '/settings/playback'
    | '/music/'
    | '/movies/'
    | '/photos/'
    | '/settings/'
    | '/tv-shows/'
    | '/movies/play/$id'
    | '/music/album/$id'
    | '/music/musician/$id'
    | '/music/playlist/$id'
    | '/movies/in-theaters/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/trailer'
    | '/'
    | '/login'
    | '/settings/account'
    | '/settings/libraries'
    | '/settings/playback'
    | '/music'
    | '/movies'
    | '/photos'
    | '/settings'
    | '/tv-shows'
    | '/movies/play/$id'
    | '/music/album/$id'
    | '/music/musician/$id'
    | '/music/playlist/$id'
    | '/movies/in-theaters/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/settings'
    | '/_auth/trailer'
    | '/_auth/'
    | '/login/'
    | '/_auth/settings/account'
    | '/_auth/settings/libraries'
    | '/_auth/settings/playback'
    | '/_auth/music/'
    | '/_auth/movies/'
    | '/_auth/photos/'
    | '/_auth/settings/'
    | '/_auth/tv-shows/'
    | '/_auth/movies/play/$id'
    | '/_auth/music/album/$id'
    | '/_auth/music/musician/$id'
    | '/_auth/music/playlist/$id'
    | '/_auth/movies/in-theaters/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexLazyRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/trailer': {
      id: '/_auth/trailer'
      path: '/trailer'
      fullPath: '/trailer'
      preLoaderRoute: typeof AuthTrailerRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tv-shows/': {
      id: '/_auth/tv-shows/'
      path: '/tv-shows'
      fullPath: '/tv-shows/'
      preLoaderRoute: typeof AuthTvShowsIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexLazyRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/photos/': {
      id: '/_auth/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof AuthPhotosIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/movies/': {
      id: '/_auth/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof AuthMoviesIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/music/': {
      id: '/_auth/music/'
      path: '/music'
      fullPath: '/music/'
      preLoaderRoute: typeof AuthMusicIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/playback': {
      id: '/_auth/settings/playback'
      path: '/playback'
      fullPath: '/settings/playback'
      preLoaderRoute: typeof AuthSettingsPlaybackLazyRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/libraries': {
      id: '/_auth/settings/libraries'
      path: '/libraries'
      fullPath: '/settings/libraries'
      preLoaderRoute: typeof AuthSettingsLibrariesLazyRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/account': {
      id: '/_auth/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthSettingsAccountLazyRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/movies/in-theaters/$id': {
      id: '/_auth/movies/in-theaters/$id'
      path: '/movies/in-theaters/$id'
      fullPath: '/movies/in-theaters/$id'
      preLoaderRoute: typeof AuthMoviesInTheatersIdLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/music/playlist/$id': {
      id: '/_auth/music/playlist/$id'
      path: '/music/playlist/$id'
      fullPath: '/music/playlist/$id'
      preLoaderRoute: typeof AuthMusicPlaylistIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/music/musician/$id': {
      id: '/_auth/music/musician/$id'
      path: '/music/musician/$id'
      fullPath: '/music/musician/$id'
      preLoaderRoute: typeof AuthMusicMusicianIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/music/album/$id': {
      id: '/_auth/music/album/$id'
      path: '/music/album/$id'
      fullPath: '/music/album/$id'
      preLoaderRoute: typeof AuthMusicAlbumIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/movies/play/$id': {
      id: '/_auth/movies/play/$id'
      path: '/movies/play/$id'
      fullPath: '/movies/play/$id'
      preLoaderRoute: typeof AuthMoviesPlayIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthSettingsRouteRouteChildren {
  AuthSettingsAccountLazyRoute: typeof AuthSettingsAccountLazyRoute
  AuthSettingsLibrariesLazyRoute: typeof AuthSettingsLibrariesLazyRoute
  AuthSettingsPlaybackLazyRoute: typeof AuthSettingsPlaybackLazyRoute
  AuthSettingsIndexLazyRoute: typeof AuthSettingsIndexLazyRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsAccountLazyRoute: AuthSettingsAccountLazyRoute,
  AuthSettingsLibrariesLazyRoute: AuthSettingsLibrariesLazyRoute,
  AuthSettingsPlaybackLazyRoute: AuthSettingsPlaybackLazyRoute,
  AuthSettingsIndexLazyRoute: AuthSettingsIndexLazyRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthTrailerRoute: typeof AuthTrailerRoute
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
  AuthMusicIndexRoute: typeof AuthMusicIndexRoute
  AuthMoviesIndexLazyRoute: typeof AuthMoviesIndexLazyRoute
  AuthPhotosIndexLazyRoute: typeof AuthPhotosIndexLazyRoute
  AuthTvShowsIndexLazyRoute: typeof AuthTvShowsIndexLazyRoute
  AuthMoviesPlayIdRoute: typeof AuthMoviesPlayIdRoute
  AuthMusicAlbumIdRoute: typeof AuthMusicAlbumIdRoute
  AuthMusicMusicianIdRoute: typeof AuthMusicMusicianIdRoute
  AuthMusicPlaylistIdRoute: typeof AuthMusicPlaylistIdRoute
  AuthMoviesInTheatersIdLazyRoute: typeof AuthMoviesInTheatersIdLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthTrailerRoute: AuthTrailerRoute,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
  AuthMusicIndexRoute: AuthMusicIndexRoute,
  AuthMoviesIndexLazyRoute: AuthMoviesIndexLazyRoute,
  AuthPhotosIndexLazyRoute: AuthPhotosIndexLazyRoute,
  AuthTvShowsIndexLazyRoute: AuthTvShowsIndexLazyRoute,
  AuthMoviesPlayIdRoute: AuthMoviesPlayIdRoute,
  AuthMusicAlbumIdRoute: AuthMusicAlbumIdRoute,
  AuthMusicMusicianIdRoute: AuthMusicMusicianIdRoute,
  AuthMusicPlaylistIdRoute: AuthMusicPlaylistIdRoute,
  AuthMoviesInTheatersIdLazyRoute: AuthMoviesInTheatersIdLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexLazyRoute: LoginIndexLazyRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
