// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: crew_list.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCrewMember = `-- name: CreateCrewMember :one
INSERT INTO crew_list (
    artist_id,
    movie_id,
    job,
    department
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, created_at, updated_at, artist_id, movie_id, job, department
`

type CreateCrewMemberParams struct {
	ArtistID   pgtype.Int4 `json:"artist_id"`
	MovieID    pgtype.Int4 `json:"movie_id"`
	Job        string      `json:"job"`
	Department string      `json:"department"`
}

func (q *Queries) CreateCrewMember(ctx context.Context, arg CreateCrewMemberParams) (CrewList, error) {
	row := q.db.QueryRow(ctx, createCrewMember,
		arg.ArtistID,
		arg.MovieID,
		arg.Job,
		arg.Department,
	)
	var i CrewList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistID,
		&i.MovieID,
		&i.Job,
		&i.Department,
	)
	return i, err
}
