// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMovieGenre(ctx context.Context, arg AddMovieGenreParams) error
	AddMovieStudio(ctx context.Context, arg AddMovieStudioParams) error
	AddUserMovie(ctx context.Context, arg AddUserMovieParams) error
	CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error)
	CreateAudioStream(ctx context.Context, arg CreateAudioStreamParams) (AudioStream, error)
	CreateCastMember(ctx context.Context, arg CreateCastMemberParams) (CastList, error)
	CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error)
	CreateCrewMember(ctx context.Context, arg CreateCrewMemberParams) (CrewList, error)
	CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateMovieExtra(ctx context.Context, arg CreateMovieExtraParams) (MovieExtra, error)
	CreateSettings(ctx context.Context, arg CreateSettingsParams) (GlobalSetting, error)
	CreateStudio(ctx context.Context, arg CreateStudioParams) (Studio, error)
	CreateSubtitle(ctx context.Context, arg CreateSubtitleParams) (Subtitle, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVideoStream(ctx context.Context, arg CreateVideoStreamParams) (VideoStream, error)
	GetArtistByTmdbID(ctx context.Context, tmdbID int32) (GetArtistByTmdbIDRow, error)
	GetGenreByID(ctx context.Context, id int32) (string, error)
	GetGenreByTmdbID(ctx context.Context, tmdbID int32) (GetGenreByTmdbIDRow, error)
	GetLatestMovies(ctx context.Context) ([]GetLatestMoviesRow, error)
	GetMovieByTmdbID(ctx context.Context, tmdbID string) (GetMovieByTmdbIDRow, error)
	GetMovieCount(ctx context.Context) (int64, error)
	GetMovieDetails(ctx context.Context, id int32) (GetMovieDetailsRow, error)
	GetMovieForStreaming(ctx context.Context, id int32) (GetMovieForStreamingRow, error)
	GetMovieStudios(ctx context.Context, movieID int32) ([]Studio, error)
	GetMovieVideoStreams(ctx context.Context, movieID pgtype.Int4) ([]VideoStream, error)
	GetMoviesPaginated(ctx context.Context, arg GetMoviesPaginatedParams) ([]GetMoviesPaginatedRow, error)
	GetSettings(ctx context.Context) (GlobalSetting, error)
	GetStudioByTmdbID(ctx context.Context, tmdbID int32) (GetStudioByTmdbIDRow, error)
	GetTotalUsersCount(ctx context.Context) (int64, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetUserForLogin(ctx context.Context, arg GetUserForLoginParams) (User, error)
	GetUserMovies(ctx context.Context, userID int32) ([]Movie, error)
	GetUsersPaginated(ctx context.Context, arg GetUsersPaginatedParams) ([]GetUsersPaginatedRow, error)
	RemoveUserMovie(ctx context.Context, arg RemoveUserMovieParams) error
	UpdateArtistThumb(ctx context.Context, arg UpdateArtistThumbParams) (Artist, error)
}

var _ Querier = (*Queries)(nil)
