// Renders the app icons from the brand sources: src/lib/theme-tokens.ts (the
// colors), src/lib/brand-mark.ts (the igloo glyph) and src/lib/constants.ts
// (the app name and description). See docs/design-system.md §2.4.
//
//   bun run generate:icons          rewrite favicon.svg, manifest.webmanifest,
//                                   the PNG icons and favicon.ico
//   bun run generate:icons --check  exit 1 if favicon.svg or the manifest is
//                                   stale (CI-friendly, never opens a browser)
//
// The text outputs (SVG, manifest) are pure renders that
// src/test/shared/icon-drift.test.ts compares against the committed files. The
// rasters are screenshots of the SVG taken with Playwright's bundled Chromium;
// their bytes vary by Chromium version, so they are committed and regenerated
// on demand rather than drift-checked.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BRAND_MARK_PATH, BRAND_MARK_VIEWBOX } from "../src/lib/brand-mark";
import { APP_DESCRIPTION, APP_NAME } from "../src/lib/constants";
import { tokenHex } from "../src/lib/theme-tokens";

const GENERATED_HINT =
  "GENERATED by scripts/generate-icons.ts from src/lib/theme-tokens.ts, src/lib/brand-mark.ts and src/lib/constants.ts — run `bun run generate:icons`";

/** Alpha of the glacier glow at the top of the tile (the boot.css canvas tint, stronger so it reads on an icon). */
const ICON_GLOW_ALPHA = 0.22;

interface IconVariant {
  /** Corner radius of the 64-unit tile; 0 renders a full-bleed square. */
  tileRadius: number;
  /** Glyph scale about the tile centre; 1 for the favicon, smaller to stay inside a launcher's safe zone. */
  glyphScale: number;
}

const ICON_VARIANTS = {
  /** Browser tab, home screen and PWA install: rounded tile with transparent corners. */
  favicon: { tileRadius: 14, glyphScale: 1 },
  /** Android adaptive icon: full-bleed, glyph inside the central 80 % safe zone. */
  maskable: { tileRadius: 0, glyphScale: 0.8 },
  /** iOS home screen: full-bleed, iOS rounds the corners itself. */
  appleTouch: { tileRadius: 0, glyphScale: 0.9 },
} as const satisfies Record<string, IconVariant>;

/** The complete SVG document for one icon variant. */
function renderIconSvg(variant: IconVariant): string {
  const canvas = tokenHex("dark", "--background");
  const glacier = tokenHex("dark", "--primary");
  const tile = (fill: string) =>
    `  <rect width="64" height="64" rx="${variant.tileRadius}" fill="${fill}"/>`;
  const glyph = `<path d="${BRAND_MARK_PATH}" fill="${glacier}" fill-rule="evenodd"/>`;
  const placedGlyph =
    variant.glyphScale === 1
      ? `  ${glyph}`
      : [
          `  <g transform="translate(32 32) scale(${variant.glyphScale}) translate(-32 -32)">`,
          `    ${glyph}`,
          "  </g>",
        ].join("\n");
  return [
    `<!-- ${GENERATED_HINT} -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${BRAND_MARK_VIEWBOX}" role="img" aria-label="${APP_NAME}">`,
    "  <defs>",
    '    <radialGradient id="glacier-glow" gradientUnits="userSpaceOnUse" cx="32" cy="0" r="40">',
    `      <stop offset="0" stop-color="${glacier}" stop-opacity="${ICON_GLOW_ALPHA}"/>`,
    `      <stop offset="1" stop-color="${glacier}" stop-opacity="0"/>`,
    "    </radialGradient>",
    "  </defs>",
    tile(canvas),
    tile("url(#glacier-glow)"),
    placedGlyph,
    "</svg>",
    "",
  ].join("\n");
}

/** public/favicon.svg */
export function renderFaviconSvg(): string {
  return renderIconSvg(ICON_VARIANTS.favicon);
}

/** public/manifest.webmanifest */
export function renderManifest(): string {
  const canvas = tokenHex("dark", "--background");
  const manifest = {
    name: APP_NAME,
    short_name: APP_NAME,
    description: APP_DESCRIPTION,
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: canvas,
    theme_color: canvas,
    icons: [
      { src: "/favicon.svg", sizes: "any", type: "image/svg+xml" },
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

interface IconTextTarget {
  /** Path relative to the web/ project root. */
  relPath: string;
  render: () => string;
}

/** Whole-file text outputs; drift-checked by `--check` and the icon-drift test. */
export const ICON_TEXT_TARGETS: IconTextTarget[] = [
  { relPath: "public/favicon.svg", render: renderFaviconSvg },
  { relPath: "public/manifest.webmanifest", render: renderManifest },
];

interface IcoImage {
  /** Edge length in pixels (square, at most 256). */
  size: number;
  /** A complete PNG stream. */
  png: Uint8Array;
}

/**
 * Wraps PNG streams in an ICO container (ICONDIR + one ICONDIRENTRY per image,
 * then the PNG bytes). PNG-in-ICO is read by every browser and by Windows
 * since Vista, so no BMP encoder is needed.
 */
export function packIco(images: readonly IcoImage[]): Buffer {
  const HEADER = 6;
  const ENTRY = 16;
  const directory = Buffer.alloc(HEADER + ENTRY * images.length);
  directory.writeUInt16LE(0, 0); // reserved
  directory.writeUInt16LE(1, 2); // type: icon
  directory.writeUInt16LE(images.length, 4);
  let offset = directory.length;
  images.forEach((image, index) => {
    if (image.size < 1 || image.size > 256) {
      throw new Error(`ICO images must be 1–256 px, got ${image.size}`);
    }
    const at = HEADER + ENTRY * index;
    const edge = image.size === 256 ? 0 : image.size;
    directory.writeUInt8(edge, at); // width (0 = 256)
    directory.writeUInt8(edge, at + 1); // height
    directory.writeUInt8(0, at + 2); // palette size
    directory.writeUInt8(0, at + 3); // reserved
    directory.writeUInt16LE(1, at + 4); // color planes
    directory.writeUInt16LE(32, at + 6); // bits per pixel
    directory.writeUInt32LE(image.png.byteLength, at + 8);
    directory.writeUInt32LE(offset, at + 12);
    offset += image.png.byteLength;
  });
  return Buffer.concat([directory, ...images.map((image) => image.png)]);
}

interface RasterJob {
  relPath: string;
  size: number;
  variant: IconVariant;
}

const RASTER_JOBS: RasterJob[] = [
  { relPath: "public/icon-192.png", size: 192, variant: ICON_VARIANTS.favicon },
  { relPath: "public/icon-512.png", size: 512, variant: ICON_VARIANTS.favicon },
  {
    relPath: "public/icon-maskable-512.png",
    size: 512,
    variant: ICON_VARIANTS.maskable,
  },
  {
    relPath: "public/apple-touch-icon.png",
    size: 180,
    variant: ICON_VARIANTS.appleTouch,
  },
];

/** favicon.ico members, smallest first; rendered in memory only. */
const ICO_SIZES = [16, 32];

/** An HTML page showing one icon at an exact pixel size on a transparent canvas. */
function rasterPage(variant: IconVariant, size: number): string {
  return [
    "<!doctype html>",
    "<html><head><meta charset=\"utf-8\"><style>",
    "html, body { margin: 0; background: transparent; overflow: hidden; }",
    `svg { display: block; width: ${size}px; height: ${size}px; }`,
    "</style></head><body>",
    renderIconSvg(variant),
    "</body></html>",
  ].join("\n");
}

async function rasterize(webRoot: string): Promise<void> {
  // Imported lazily so the drift test (which imports this module under
  // vitest, before CI installs any browser) never loads Playwright.
  const { chromium } = await import("@playwright/test");
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ deviceScaleFactor: 1 });
    const render = async (variant: IconVariant, size: number) => {
      await page.setViewportSize({ width: size, height: size });
      await page.setContent(rasterPage(variant, size), { waitUntil: "load" });
      return page.screenshot({
        type: "png",
        omitBackground: true,
        clip: { x: 0, y: 0, width: size, height: size },
      });
    };
    for (const job of RASTER_JOBS) {
      writeFileSync(resolve(webRoot, job.relPath), await render(job.variant, job.size));
      console.log(`generated ${job.relPath}`);
    }
    const members: IcoImage[] = [];
    for (const size of ICO_SIZES) {
      members.push({ size, png: await render(ICON_VARIANTS.favicon, size) });
    }
    writeFileSync(resolve(webRoot, "public/favicon.ico"), packIco(members));
    console.log("generated public/favicon.ico");
  } finally {
    await browser.close();
  }
}

async function main(check: boolean): Promise<void> {
  const webRoot = fileURLToPath(new URL("..", import.meta.url));
  const stale: string[] = [];
  for (const target of ICON_TEXT_TARGETS) {
    const path = resolve(webRoot, target.relPath);
    const rendered = target.render();
    if (readFileSync(path, "utf8") === rendered) {
      continue;
    }
    if (check) {
      stale.push(target.relPath);
      continue;
    }
    writeFileSync(path, rendered);
    console.log(`generated ${target.relPath}`);
  }
  if (stale.length > 0) {
    console.error(
      `stale generated icon files (run \`bun run generate:icons\`): ${stale.join(", ")}`,
    );
    process.exit(1);
  }
  if (check) {
    return;
  }
  try {
    await rasterize(webRoot);
  } catch (error) {
    console.error(
      "could not rasterize the icons with Playwright's Chromium (install it with `bun x playwright install chromium`):",
      error,
    );
    process.exit(1);
  }
}

const isMain =
  process.argv[1] != null &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  await main(process.argv.includes("--check"));
}
