// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCollaboratorStmt, err = db.PrepareContext(ctx, addCollaborator); err != nil {
		return nil, fmt.Errorf("error preparing query AddCollaborator: %w", err)
	}
	if q.addTrackToPlaylistStmt, err = db.PrepareContext(ctx, addTrackToPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query AddTrackToPlaylist: %w", err)
	}
	if q.canUserEditPlaylistStmt, err = db.PrepareContext(ctx, canUserEditPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query CanUserEditPlaylist: %w", err)
	}
	if q.checkTrackUnchangedStmt, err = db.PrepareContext(ctx, checkTrackUnchanged); err != nil {
		return nil, fmt.Errorf("error preparing query CheckTrackUnchanged: %w", err)
	}
	if q.clearPlaylistStmt, err = db.PrepareContext(ctx, clearPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPlaylist: %w", err)
	}
	if q.countPlaylistTracksStmt, err = db.PrepareContext(ctx, countPlaylistTracks); err != nil {
		return nil, fmt.Errorf("error preparing query CountPlaylistTracks: %w", err)
	}
	if q.countPlaylistsByUserIdStmt, err = db.PrepareContext(ctx, countPlaylistsByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query CountPlaylistsByUserId: %w", err)
	}
	if q.createMusicianAlbumStmt, err = db.PrepareContext(ctx, createMusicianAlbum); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMusicianAlbum: %w", err)
	}
	if q.createPlaylistStmt, err = db.PrepareContext(ctx, createPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePlaylist: %w", err)
	}
	if q.createSettingsStmt, err = db.PrepareContext(ctx, createSettings); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSettings: %w", err)
	}
	if q.createTrackGenreStmt, err = db.PrepareContext(ctx, createTrackGenre); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTrackGenre: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteAlbumStmt, err = db.PrepareContext(ctx, deleteAlbum); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAlbum: %w", err)
	}
	if q.deletePlaylistStmt, err = db.PrepareContext(ctx, deletePlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePlaylist: %w", err)
	}
	if q.deleteTrackGenresStmt, err = db.PrepareContext(ctx, deleteTrackGenres); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTrackGenres: %w", err)
	}
	if q.deleteTrackGenresExceptStmt, err = db.PrepareContext(ctx, deleteTrackGenresExcept); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTrackGenresExcept: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getAdminUserStmt, err = db.PrepareContext(ctx, getAdminUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminUser: %w", err)
	}
	if q.getAlbumByIDStmt, err = db.PrepareContext(ctx, getAlbumByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAlbumByID: %w", err)
	}
	if q.getAlbumBySpotifyIDStmt, err = db.PrepareContext(ctx, getAlbumBySpotifyID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAlbumBySpotifyID: %w", err)
	}
	if q.getAlbumsAlphabeticalStmt, err = db.PrepareContext(ctx, getAlbumsAlphabetical); err != nil {
		return nil, fmt.Errorf("error preparing query GetAlbumsAlphabetical: %w", err)
	}
	if q.getAlbumsByMusicianIDStmt, err = db.PrepareContext(ctx, getAlbumsByMusicianID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAlbumsByMusicianID: %w", err)
	}
	if q.getAlbumsCountStmt, err = db.PrepareContext(ctx, getAlbumsCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetAlbumsCount: %w", err)
	}
	if q.getAllPlaylistTracksStmt, err = db.PrepareContext(ctx, getAllPlaylistTracks); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPlaylistTracks: %w", err)
	}
	if q.getAllTrackPathsAndSizesStmt, err = db.PrepareContext(ctx, getAllTrackPathsAndSizes); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTrackPathsAndSizes: %w", err)
	}
	if q.getGenresByAlbumIDStmt, err = db.PrepareContext(ctx, getGenresByAlbumID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGenresByAlbumID: %w", err)
	}
	if q.getGenresByAlbumIDDirectStmt, err = db.PrepareContext(ctx, getGenresByAlbumIDDirect); err != nil {
		return nil, fmt.Errorf("error preparing query GetGenresByAlbumIDDirect: %w", err)
	}
	if q.getGenresByMusicianIDStmt, err = db.PrepareContext(ctx, getGenresByMusicianID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGenresByMusicianID: %w", err)
	}
	if q.getLatestAlbumsStmt, err = db.PrepareContext(ctx, getLatestAlbums); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestAlbums: %w", err)
	}
	if q.getLikedTrackIDsByUserIDStmt, err = db.PrepareContext(ctx, getLikedTrackIDsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetLikedTrackIDsByUserID: %w", err)
	}
	if q.getLikedTracksByUserIDStmt, err = db.PrepareContext(ctx, getLikedTracksByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetLikedTracksByUserID: %w", err)
	}
	if q.getMaxPositionStmt, err = db.PrepareContext(ctx, getMaxPosition); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaxPosition: %w", err)
	}
	if q.getMusicianByIDStmt, err = db.PrepareContext(ctx, getMusicianByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMusicianByID: %w", err)
	}
	if q.getMusicianBySpotifyIDStmt, err = db.PrepareContext(ctx, getMusicianBySpotifyID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMusicianBySpotifyID: %w", err)
	}
	if q.getMusiciansAlphabeticalStmt, err = db.PrepareContext(ctx, getMusiciansAlphabetical); err != nil {
		return nil, fmt.Errorf("error preparing query GetMusiciansAlphabetical: %w", err)
	}
	if q.getMusiciansByAlbumIDStmt, err = db.PrepareContext(ctx, getMusiciansByAlbumID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMusiciansByAlbumID: %w", err)
	}
	if q.getMusiciansCountStmt, err = db.PrepareContext(ctx, getMusiciansCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetMusiciansCount: %w", err)
	}
	if q.getOrCreateGenreStmt, err = db.PrepareContext(ctx, getOrCreateGenre); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrCreateGenre: %w", err)
	}
	if q.getPlaylistByIdStmt, err = db.PrepareContext(ctx, getPlaylistById); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlaylistById: %w", err)
	}
	if q.getPlaylistCollaboratorsStmt, err = db.PrepareContext(ctx, getPlaylistCollaborators); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlaylistCollaborators: %w", err)
	}
	if q.getPlaylistDurationStmt, err = db.PrepareContext(ctx, getPlaylistDuration); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlaylistDuration: %w", err)
	}
	if q.getPlaylistTracksInfiniteStmt, err = db.PrepareContext(ctx, getPlaylistTracksInfinite); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlaylistTracksInfinite: %w", err)
	}
	if q.getPlaylistsByUserIdStmt, err = db.PrepareContext(ctx, getPlaylistsByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlaylistsByUserId: %w", err)
	}
	if q.getPlaylistsWithCollaboratorAccessStmt, err = db.PrepareContext(ctx, getPlaylistsWithCollaboratorAccess); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlaylistsWithCollaboratorAccess: %w", err)
	}
	if q.getRandomTracksStmt, err = db.PrepareContext(ctx, getRandomTracks); err != nil {
		return nil, fmt.Errorf("error preparing query GetRandomTracks: %w", err)
	}
	if q.getSettingsStmt, err = db.PrepareContext(ctx, getSettings); err != nil {
		return nil, fmt.Errorf("error preparing query GetSettings: %w", err)
	}
	if q.getTrackStmt, err = db.PrepareContext(ctx, getTrack); err != nil {
		return nil, fmt.Errorf("error preparing query GetTrack: %w", err)
	}
	if q.getTracksAlphabeticalStmt, err = db.PrepareContext(ctx, getTracksAlphabetical); err != nil {
		return nil, fmt.Errorf("error preparing query GetTracksAlphabetical: %w", err)
	}
	if q.getTracksByAlbumIDStmt, err = db.PrepareContext(ctx, getTracksByAlbumID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTracksByAlbumID: %w", err)
	}
	if q.getTracksByMusicianIDStmt, err = db.PrepareContext(ctx, getTracksByMusicianID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTracksByMusicianID: %w", err)
	}
	if q.getTracksCountStmt, err = db.PrepareContext(ctx, getTracksCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetTracksCount: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserListeningHistoryByPeriodStmt, err = db.PrepareContext(ctx, getUserListeningHistoryByPeriod); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserListeningHistoryByPeriod: %w", err)
	}
	if q.getUserListeningStatsStmt, err = db.PrepareContext(ctx, getUserListeningStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserListeningStats: %w", err)
	}
	if q.getUserRecentlyPlayedStmt, err = db.PrepareContext(ctx, getUserRecentlyPlayed); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserRecentlyPlayed: %w", err)
	}
	if q.getUserTopAlbumsStmt, err = db.PrepareContext(ctx, getUserTopAlbums); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserTopAlbums: %w", err)
	}
	if q.getUserTopGenresStmt, err = db.PrepareContext(ctx, getUserTopGenres); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserTopGenres: %w", err)
	}
	if q.getUserTopMusiciansStmt, err = db.PrepareContext(ctx, getUserTopMusicians); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserTopMusicians: %w", err)
	}
	if q.getUserTopTracksStmt, err = db.PrepareContext(ctx, getUserTopTracks); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserTopTracks: %w", err)
	}
	if q.getUserTrackPlayCountStmt, err = db.PrepareContext(ctx, getUserTrackPlayCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserTrackPlayCount: %w", err)
	}
	if q.isTrackInPlaylistStmt, err = db.PrepareContext(ctx, isTrackInPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query IsTrackInPlaylist: %w", err)
	}
	if q.isTrackLikedStmt, err = db.PrepareContext(ctx, isTrackLiked); err != nil {
		return nil, fmt.Errorf("error preparing query IsTrackLiked: %w", err)
	}
	if q.isUserCollaboratorStmt, err = db.PrepareContext(ctx, isUserCollaborator); err != nil {
		return nil, fmt.Errorf("error preparing query IsUserCollaborator: %w", err)
	}
	if q.likeTrackStmt, err = db.PrepareContext(ctx, likeTrack); err != nil {
		return nil, fmt.Errorf("error preparing query LikeTrack: %w", err)
	}
	if q.recordPlayEventStmt, err = db.PrepareContext(ctx, recordPlayEvent); err != nil {
		return nil, fmt.Errorf("error preparing query RecordPlayEvent: %w", err)
	}
	if q.removeCollaboratorStmt, err = db.PrepareContext(ctx, removeCollaborator); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveCollaborator: %w", err)
	}
	if q.removeTrackFromPlaylistStmt, err = db.PrepareContext(ctx, removeTrackFromPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveTrackFromPlaylist: %w", err)
	}
	if q.shiftPositionsDownStmt, err = db.PrepareContext(ctx, shiftPositionsDown); err != nil {
		return nil, fmt.Errorf("error preparing query ShiftPositionsDown: %w", err)
	}
	if q.shiftPositionsUpStmt, err = db.PrepareContext(ctx, shiftPositionsUp); err != nil {
		return nil, fmt.Errorf("error preparing query ShiftPositionsUp: %w", err)
	}
	if q.unlikeTrackStmt, err = db.PrepareContext(ctx, unlikeTrack); err != nil {
		return nil, fmt.Errorf("error preparing query UnlikeTrack: %w", err)
	}
	if q.updateCollaboratorPermissionStmt, err = db.PrepareContext(ctx, updateCollaboratorPermission); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCollaboratorPermission: %w", err)
	}
	if q.updatePlaylistStmt, err = db.PrepareContext(ctx, updatePlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePlaylist: %w", err)
	}
	if q.updatePlaylistTimestampStmt, err = db.PrepareContext(ctx, updatePlaylistTimestamp); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePlaylistTimestamp: %w", err)
	}
	if q.updateTrackPositionStmt, err = db.PrepareContext(ctx, updateTrackPosition); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTrackPosition: %w", err)
	}
	if q.updateUserAvatarStmt, err = db.PrepareContext(ctx, updateUserAvatar); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserAvatar: %w", err)
	}
	if q.updateUserNameStmt, err = db.PrepareContext(ctx, updateUserName); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserName: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.upsertAlbumStmt, err = db.PrepareContext(ctx, upsertAlbum); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAlbum: %w", err)
	}
	if q.upsertAlbumGenreStmt, err = db.PrepareContext(ctx, upsertAlbumGenre); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAlbumGenre: %w", err)
	}
	if q.upsertMusicianStmt, err = db.PrepareContext(ctx, upsertMusician); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMusician: %w", err)
	}
	if q.upsertMusicianGenreStmt, err = db.PrepareContext(ctx, upsertMusicianGenre); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMusicianGenre: %w", err)
	}
	if q.upsertTrackStmt, err = db.PrepareContext(ctx, upsertTrack); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertTrack: %w", err)
	}
	if q.upsertUserTrackStatsStmt, err = db.PrepareContext(ctx, upsertUserTrackStats); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertUserTrackStats: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCollaboratorStmt != nil {
		if cerr := q.addCollaboratorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCollaboratorStmt: %w", cerr)
		}
	}
	if q.addTrackToPlaylistStmt != nil {
		if cerr := q.addTrackToPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTrackToPlaylistStmt: %w", cerr)
		}
	}
	if q.canUserEditPlaylistStmt != nil {
		if cerr := q.canUserEditPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing canUserEditPlaylistStmt: %w", cerr)
		}
	}
	if q.checkTrackUnchangedStmt != nil {
		if cerr := q.checkTrackUnchangedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkTrackUnchangedStmt: %w", cerr)
		}
	}
	if q.clearPlaylistStmt != nil {
		if cerr := q.clearPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPlaylistStmt: %w", cerr)
		}
	}
	if q.countPlaylistTracksStmt != nil {
		if cerr := q.countPlaylistTracksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPlaylistTracksStmt: %w", cerr)
		}
	}
	if q.countPlaylistsByUserIdStmt != nil {
		if cerr := q.countPlaylistsByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPlaylistsByUserIdStmt: %w", cerr)
		}
	}
	if q.createMusicianAlbumStmt != nil {
		if cerr := q.createMusicianAlbumStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMusicianAlbumStmt: %w", cerr)
		}
	}
	if q.createPlaylistStmt != nil {
		if cerr := q.createPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPlaylistStmt: %w", cerr)
		}
	}
	if q.createSettingsStmt != nil {
		if cerr := q.createSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSettingsStmt: %w", cerr)
		}
	}
	if q.createTrackGenreStmt != nil {
		if cerr := q.createTrackGenreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTrackGenreStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteAlbumStmt != nil {
		if cerr := q.deleteAlbumStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAlbumStmt: %w", cerr)
		}
	}
	if q.deletePlaylistStmt != nil {
		if cerr := q.deletePlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePlaylistStmt: %w", cerr)
		}
	}
	if q.deleteTrackGenresStmt != nil {
		if cerr := q.deleteTrackGenresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTrackGenresStmt: %w", cerr)
		}
	}
	if q.deleteTrackGenresExceptStmt != nil {
		if cerr := q.deleteTrackGenresExceptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTrackGenresExceptStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getAdminUserStmt != nil {
		if cerr := q.getAdminUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminUserStmt: %w", cerr)
		}
	}
	if q.getAlbumByIDStmt != nil {
		if cerr := q.getAlbumByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAlbumByIDStmt: %w", cerr)
		}
	}
	if q.getAlbumBySpotifyIDStmt != nil {
		if cerr := q.getAlbumBySpotifyIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAlbumBySpotifyIDStmt: %w", cerr)
		}
	}
	if q.getAlbumsAlphabeticalStmt != nil {
		if cerr := q.getAlbumsAlphabeticalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAlbumsAlphabeticalStmt: %w", cerr)
		}
	}
	if q.getAlbumsByMusicianIDStmt != nil {
		if cerr := q.getAlbumsByMusicianIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAlbumsByMusicianIDStmt: %w", cerr)
		}
	}
	if q.getAlbumsCountStmt != nil {
		if cerr := q.getAlbumsCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAlbumsCountStmt: %w", cerr)
		}
	}
	if q.getAllPlaylistTracksStmt != nil {
		if cerr := q.getAllPlaylistTracksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPlaylistTracksStmt: %w", cerr)
		}
	}
	if q.getAllTrackPathsAndSizesStmt != nil {
		if cerr := q.getAllTrackPathsAndSizesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTrackPathsAndSizesStmt: %w", cerr)
		}
	}
	if q.getGenresByAlbumIDStmt != nil {
		if cerr := q.getGenresByAlbumIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGenresByAlbumIDStmt: %w", cerr)
		}
	}
	if q.getGenresByAlbumIDDirectStmt != nil {
		if cerr := q.getGenresByAlbumIDDirectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGenresByAlbumIDDirectStmt: %w", cerr)
		}
	}
	if q.getGenresByMusicianIDStmt != nil {
		if cerr := q.getGenresByMusicianIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGenresByMusicianIDStmt: %w", cerr)
		}
	}
	if q.getLatestAlbumsStmt != nil {
		if cerr := q.getLatestAlbumsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestAlbumsStmt: %w", cerr)
		}
	}
	if q.getLikedTrackIDsByUserIDStmt != nil {
		if cerr := q.getLikedTrackIDsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLikedTrackIDsByUserIDStmt: %w", cerr)
		}
	}
	if q.getLikedTracksByUserIDStmt != nil {
		if cerr := q.getLikedTracksByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLikedTracksByUserIDStmt: %w", cerr)
		}
	}
	if q.getMaxPositionStmt != nil {
		if cerr := q.getMaxPositionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaxPositionStmt: %w", cerr)
		}
	}
	if q.getMusicianByIDStmt != nil {
		if cerr := q.getMusicianByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMusicianByIDStmt: %w", cerr)
		}
	}
	if q.getMusicianBySpotifyIDStmt != nil {
		if cerr := q.getMusicianBySpotifyIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMusicianBySpotifyIDStmt: %w", cerr)
		}
	}
	if q.getMusiciansAlphabeticalStmt != nil {
		if cerr := q.getMusiciansAlphabeticalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMusiciansAlphabeticalStmt: %w", cerr)
		}
	}
	if q.getMusiciansByAlbumIDStmt != nil {
		if cerr := q.getMusiciansByAlbumIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMusiciansByAlbumIDStmt: %w", cerr)
		}
	}
	if q.getMusiciansCountStmt != nil {
		if cerr := q.getMusiciansCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMusiciansCountStmt: %w", cerr)
		}
	}
	if q.getOrCreateGenreStmt != nil {
		if cerr := q.getOrCreateGenreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrCreateGenreStmt: %w", cerr)
		}
	}
	if q.getPlaylistByIdStmt != nil {
		if cerr := q.getPlaylistByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlaylistByIdStmt: %w", cerr)
		}
	}
	if q.getPlaylistCollaboratorsStmt != nil {
		if cerr := q.getPlaylistCollaboratorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlaylistCollaboratorsStmt: %w", cerr)
		}
	}
	if q.getPlaylistDurationStmt != nil {
		if cerr := q.getPlaylistDurationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlaylistDurationStmt: %w", cerr)
		}
	}
	if q.getPlaylistTracksInfiniteStmt != nil {
		if cerr := q.getPlaylistTracksInfiniteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlaylistTracksInfiniteStmt: %w", cerr)
		}
	}
	if q.getPlaylistsByUserIdStmt != nil {
		if cerr := q.getPlaylistsByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlaylistsByUserIdStmt: %w", cerr)
		}
	}
	if q.getPlaylistsWithCollaboratorAccessStmt != nil {
		if cerr := q.getPlaylistsWithCollaboratorAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlaylistsWithCollaboratorAccessStmt: %w", cerr)
		}
	}
	if q.getRandomTracksStmt != nil {
		if cerr := q.getRandomTracksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRandomTracksStmt: %w", cerr)
		}
	}
	if q.getSettingsStmt != nil {
		if cerr := q.getSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSettingsStmt: %w", cerr)
		}
	}
	if q.getTrackStmt != nil {
		if cerr := q.getTrackStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTrackStmt: %w", cerr)
		}
	}
	if q.getTracksAlphabeticalStmt != nil {
		if cerr := q.getTracksAlphabeticalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTracksAlphabeticalStmt: %w", cerr)
		}
	}
	if q.getTracksByAlbumIDStmt != nil {
		if cerr := q.getTracksByAlbumIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTracksByAlbumIDStmt: %w", cerr)
		}
	}
	if q.getTracksByMusicianIDStmt != nil {
		if cerr := q.getTracksByMusicianIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTracksByMusicianIDStmt: %w", cerr)
		}
	}
	if q.getTracksCountStmt != nil {
		if cerr := q.getTracksCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTracksCountStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserListeningHistoryByPeriodStmt != nil {
		if cerr := q.getUserListeningHistoryByPeriodStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserListeningHistoryByPeriodStmt: %w", cerr)
		}
	}
	if q.getUserListeningStatsStmt != nil {
		if cerr := q.getUserListeningStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserListeningStatsStmt: %w", cerr)
		}
	}
	if q.getUserRecentlyPlayedStmt != nil {
		if cerr := q.getUserRecentlyPlayedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserRecentlyPlayedStmt: %w", cerr)
		}
	}
	if q.getUserTopAlbumsStmt != nil {
		if cerr := q.getUserTopAlbumsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserTopAlbumsStmt: %w", cerr)
		}
	}
	if q.getUserTopGenresStmt != nil {
		if cerr := q.getUserTopGenresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserTopGenresStmt: %w", cerr)
		}
	}
	if q.getUserTopMusiciansStmt != nil {
		if cerr := q.getUserTopMusiciansStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserTopMusiciansStmt: %w", cerr)
		}
	}
	if q.getUserTopTracksStmt != nil {
		if cerr := q.getUserTopTracksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserTopTracksStmt: %w", cerr)
		}
	}
	if q.getUserTrackPlayCountStmt != nil {
		if cerr := q.getUserTrackPlayCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserTrackPlayCountStmt: %w", cerr)
		}
	}
	if q.isTrackInPlaylistStmt != nil {
		if cerr := q.isTrackInPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isTrackInPlaylistStmt: %w", cerr)
		}
	}
	if q.isTrackLikedStmt != nil {
		if cerr := q.isTrackLikedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isTrackLikedStmt: %w", cerr)
		}
	}
	if q.isUserCollaboratorStmt != nil {
		if cerr := q.isUserCollaboratorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isUserCollaboratorStmt: %w", cerr)
		}
	}
	if q.likeTrackStmt != nil {
		if cerr := q.likeTrackStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing likeTrackStmt: %w", cerr)
		}
	}
	if q.recordPlayEventStmt != nil {
		if cerr := q.recordPlayEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordPlayEventStmt: %w", cerr)
		}
	}
	if q.removeCollaboratorStmt != nil {
		if cerr := q.removeCollaboratorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeCollaboratorStmt: %w", cerr)
		}
	}
	if q.removeTrackFromPlaylistStmt != nil {
		if cerr := q.removeTrackFromPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeTrackFromPlaylistStmt: %w", cerr)
		}
	}
	if q.shiftPositionsDownStmt != nil {
		if cerr := q.shiftPositionsDownStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing shiftPositionsDownStmt: %w", cerr)
		}
	}
	if q.shiftPositionsUpStmt != nil {
		if cerr := q.shiftPositionsUpStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing shiftPositionsUpStmt: %w", cerr)
		}
	}
	if q.unlikeTrackStmt != nil {
		if cerr := q.unlikeTrackStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unlikeTrackStmt: %w", cerr)
		}
	}
	if q.updateCollaboratorPermissionStmt != nil {
		if cerr := q.updateCollaboratorPermissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCollaboratorPermissionStmt: %w", cerr)
		}
	}
	if q.updatePlaylistStmt != nil {
		if cerr := q.updatePlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePlaylistStmt: %w", cerr)
		}
	}
	if q.updatePlaylistTimestampStmt != nil {
		if cerr := q.updatePlaylistTimestampStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePlaylistTimestampStmt: %w", cerr)
		}
	}
	if q.updateTrackPositionStmt != nil {
		if cerr := q.updateTrackPositionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTrackPositionStmt: %w", cerr)
		}
	}
	if q.updateUserAvatarStmt != nil {
		if cerr := q.updateUserAvatarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserAvatarStmt: %w", cerr)
		}
	}
	if q.updateUserNameStmt != nil {
		if cerr := q.updateUserNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserNameStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.upsertAlbumStmt != nil {
		if cerr := q.upsertAlbumStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAlbumStmt: %w", cerr)
		}
	}
	if q.upsertAlbumGenreStmt != nil {
		if cerr := q.upsertAlbumGenreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAlbumGenreStmt: %w", cerr)
		}
	}
	if q.upsertMusicianStmt != nil {
		if cerr := q.upsertMusicianStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMusicianStmt: %w", cerr)
		}
	}
	if q.upsertMusicianGenreStmt != nil {
		if cerr := q.upsertMusicianGenreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMusicianGenreStmt: %w", cerr)
		}
	}
	if q.upsertTrackStmt != nil {
		if cerr := q.upsertTrackStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertTrackStmt: %w", cerr)
		}
	}
	if q.upsertUserTrackStatsStmt != nil {
		if cerr := q.upsertUserTrackStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertUserTrackStatsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                     DBTX
	tx                                     *sql.Tx
	addCollaboratorStmt                    *sql.Stmt
	addTrackToPlaylistStmt                 *sql.Stmt
	canUserEditPlaylistStmt                *sql.Stmt
	checkTrackUnchangedStmt                *sql.Stmt
	clearPlaylistStmt                      *sql.Stmt
	countPlaylistTracksStmt                *sql.Stmt
	countPlaylistsByUserIdStmt             *sql.Stmt
	createMusicianAlbumStmt                *sql.Stmt
	createPlaylistStmt                     *sql.Stmt
	createSettingsStmt                     *sql.Stmt
	createTrackGenreStmt                   *sql.Stmt
	createUserStmt                         *sql.Stmt
	deleteAlbumStmt                        *sql.Stmt
	deletePlaylistStmt                     *sql.Stmt
	deleteTrackGenresStmt                  *sql.Stmt
	deleteTrackGenresExceptStmt            *sql.Stmt
	deleteUserStmt                         *sql.Stmt
	getAdminUserStmt                       *sql.Stmt
	getAlbumByIDStmt                       *sql.Stmt
	getAlbumBySpotifyIDStmt                *sql.Stmt
	getAlbumsAlphabeticalStmt              *sql.Stmt
	getAlbumsByMusicianIDStmt              *sql.Stmt
	getAlbumsCountStmt                     *sql.Stmt
	getAllPlaylistTracksStmt               *sql.Stmt
	getAllTrackPathsAndSizesStmt           *sql.Stmt
	getGenresByAlbumIDStmt                 *sql.Stmt
	getGenresByAlbumIDDirectStmt           *sql.Stmt
	getGenresByMusicianIDStmt              *sql.Stmt
	getLatestAlbumsStmt                    *sql.Stmt
	getLikedTrackIDsByUserIDStmt           *sql.Stmt
	getLikedTracksByUserIDStmt             *sql.Stmt
	getMaxPositionStmt                     *sql.Stmt
	getMusicianByIDStmt                    *sql.Stmt
	getMusicianBySpotifyIDStmt             *sql.Stmt
	getMusiciansAlphabeticalStmt           *sql.Stmt
	getMusiciansByAlbumIDStmt              *sql.Stmt
	getMusiciansCountStmt                  *sql.Stmt
	getOrCreateGenreStmt                   *sql.Stmt
	getPlaylistByIdStmt                    *sql.Stmt
	getPlaylistCollaboratorsStmt           *sql.Stmt
	getPlaylistDurationStmt                *sql.Stmt
	getPlaylistTracksInfiniteStmt          *sql.Stmt
	getPlaylistsByUserIdStmt               *sql.Stmt
	getPlaylistsWithCollaboratorAccessStmt *sql.Stmt
	getRandomTracksStmt                    *sql.Stmt
	getSettingsStmt                        *sql.Stmt
	getTrackStmt                           *sql.Stmt
	getTracksAlphabeticalStmt              *sql.Stmt
	getTracksByAlbumIDStmt                 *sql.Stmt
	getTracksByMusicianIDStmt              *sql.Stmt
	getTracksCountStmt                     *sql.Stmt
	getUserStmt                            *sql.Stmt
	getUserByEmailStmt                     *sql.Stmt
	getUserListeningHistoryByPeriodStmt    *sql.Stmt
	getUserListeningStatsStmt              *sql.Stmt
	getUserRecentlyPlayedStmt              *sql.Stmt
	getUserTopAlbumsStmt                   *sql.Stmt
	getUserTopGenresStmt                   *sql.Stmt
	getUserTopMusiciansStmt                *sql.Stmt
	getUserTopTracksStmt                   *sql.Stmt
	getUserTrackPlayCountStmt              *sql.Stmt
	isTrackInPlaylistStmt                  *sql.Stmt
	isTrackLikedStmt                       *sql.Stmt
	isUserCollaboratorStmt                 *sql.Stmt
	likeTrackStmt                          *sql.Stmt
	recordPlayEventStmt                    *sql.Stmt
	removeCollaboratorStmt                 *sql.Stmt
	removeTrackFromPlaylistStmt            *sql.Stmt
	shiftPositionsDownStmt                 *sql.Stmt
	shiftPositionsUpStmt                   *sql.Stmt
	unlikeTrackStmt                        *sql.Stmt
	updateCollaboratorPermissionStmt       *sql.Stmt
	updatePlaylistStmt                     *sql.Stmt
	updatePlaylistTimestampStmt            *sql.Stmt
	updateTrackPositionStmt                *sql.Stmt
	updateUserAvatarStmt                   *sql.Stmt
	updateUserNameStmt                     *sql.Stmt
	updateUserPasswordStmt                 *sql.Stmt
	upsertAlbumStmt                        *sql.Stmt
	upsertAlbumGenreStmt                   *sql.Stmt
	upsertMusicianStmt                     *sql.Stmt
	upsertMusicianGenreStmt                *sql.Stmt
	upsertTrackStmt                        *sql.Stmt
	upsertUserTrackStatsStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		addCollaboratorStmt:                    q.addCollaboratorStmt,
		addTrackToPlaylistStmt:                 q.addTrackToPlaylistStmt,
		canUserEditPlaylistStmt:                q.canUserEditPlaylistStmt,
		checkTrackUnchangedStmt:                q.checkTrackUnchangedStmt,
		clearPlaylistStmt:                      q.clearPlaylistStmt,
		countPlaylistTracksStmt:                q.countPlaylistTracksStmt,
		countPlaylistsByUserIdStmt:             q.countPlaylistsByUserIdStmt,
		createMusicianAlbumStmt:                q.createMusicianAlbumStmt,
		createPlaylistStmt:                     q.createPlaylistStmt,
		createSettingsStmt:                     q.createSettingsStmt,
		createTrackGenreStmt:                   q.createTrackGenreStmt,
		createUserStmt:                         q.createUserStmt,
		deleteAlbumStmt:                        q.deleteAlbumStmt,
		deletePlaylistStmt:                     q.deletePlaylistStmt,
		deleteTrackGenresStmt:                  q.deleteTrackGenresStmt,
		deleteTrackGenresExceptStmt:            q.deleteTrackGenresExceptStmt,
		deleteUserStmt:                         q.deleteUserStmt,
		getAdminUserStmt:                       q.getAdminUserStmt,
		getAlbumByIDStmt:                       q.getAlbumByIDStmt,
		getAlbumBySpotifyIDStmt:                q.getAlbumBySpotifyIDStmt,
		getAlbumsAlphabeticalStmt:              q.getAlbumsAlphabeticalStmt,
		getAlbumsByMusicianIDStmt:              q.getAlbumsByMusicianIDStmt,
		getAlbumsCountStmt:                     q.getAlbumsCountStmt,
		getAllPlaylistTracksStmt:               q.getAllPlaylistTracksStmt,
		getAllTrackPathsAndSizesStmt:           q.getAllTrackPathsAndSizesStmt,
		getGenresByAlbumIDStmt:                 q.getGenresByAlbumIDStmt,
		getGenresByAlbumIDDirectStmt:           q.getGenresByAlbumIDDirectStmt,
		getGenresByMusicianIDStmt:              q.getGenresByMusicianIDStmt,
		getLatestAlbumsStmt:                    q.getLatestAlbumsStmt,
		getLikedTrackIDsByUserIDStmt:           q.getLikedTrackIDsByUserIDStmt,
		getLikedTracksByUserIDStmt:             q.getLikedTracksByUserIDStmt,
		getMaxPositionStmt:                     q.getMaxPositionStmt,
		getMusicianByIDStmt:                    q.getMusicianByIDStmt,
		getMusicianBySpotifyIDStmt:             q.getMusicianBySpotifyIDStmt,
		getMusiciansAlphabeticalStmt:           q.getMusiciansAlphabeticalStmt,
		getMusiciansByAlbumIDStmt:              q.getMusiciansByAlbumIDStmt,
		getMusiciansCountStmt:                  q.getMusiciansCountStmt,
		getOrCreateGenreStmt:                   q.getOrCreateGenreStmt,
		getPlaylistByIdStmt:                    q.getPlaylistByIdStmt,
		getPlaylistCollaboratorsStmt:           q.getPlaylistCollaboratorsStmt,
		getPlaylistDurationStmt:                q.getPlaylistDurationStmt,
		getPlaylistTracksInfiniteStmt:          q.getPlaylistTracksInfiniteStmt,
		getPlaylistsByUserIdStmt:               q.getPlaylistsByUserIdStmt,
		getPlaylistsWithCollaboratorAccessStmt: q.getPlaylistsWithCollaboratorAccessStmt,
		getRandomTracksStmt:                    q.getRandomTracksStmt,
		getSettingsStmt:                        q.getSettingsStmt,
		getTrackStmt:                           q.getTrackStmt,
		getTracksAlphabeticalStmt:              q.getTracksAlphabeticalStmt,
		getTracksByAlbumIDStmt:                 q.getTracksByAlbumIDStmt,
		getTracksByMusicianIDStmt:              q.getTracksByMusicianIDStmt,
		getTracksCountStmt:                     q.getTracksCountStmt,
		getUserStmt:                            q.getUserStmt,
		getUserByEmailStmt:                     q.getUserByEmailStmt,
		getUserListeningHistoryByPeriodStmt:    q.getUserListeningHistoryByPeriodStmt,
		getUserListeningStatsStmt:              q.getUserListeningStatsStmt,
		getUserRecentlyPlayedStmt:              q.getUserRecentlyPlayedStmt,
		getUserTopAlbumsStmt:                   q.getUserTopAlbumsStmt,
		getUserTopGenresStmt:                   q.getUserTopGenresStmt,
		getUserTopMusiciansStmt:                q.getUserTopMusiciansStmt,
		getUserTopTracksStmt:                   q.getUserTopTracksStmt,
		getUserTrackPlayCountStmt:              q.getUserTrackPlayCountStmt,
		isTrackInPlaylistStmt:                  q.isTrackInPlaylistStmt,
		isTrackLikedStmt:                       q.isTrackLikedStmt,
		isUserCollaboratorStmt:                 q.isUserCollaboratorStmt,
		likeTrackStmt:                          q.likeTrackStmt,
		recordPlayEventStmt:                    q.recordPlayEventStmt,
		removeCollaboratorStmt:                 q.removeCollaboratorStmt,
		removeTrackFromPlaylistStmt:            q.removeTrackFromPlaylistStmt,
		shiftPositionsDownStmt:                 q.shiftPositionsDownStmt,
		shiftPositionsUpStmt:                   q.shiftPositionsUpStmt,
		unlikeTrackStmt:                        q.unlikeTrackStmt,
		updateCollaboratorPermissionStmt:       q.updateCollaboratorPermissionStmt,
		updatePlaylistStmt:                     q.updatePlaylistStmt,
		updatePlaylistTimestampStmt:            q.updatePlaylistTimestampStmt,
		updateTrackPositionStmt:                q.updateTrackPositionStmt,
		updateUserAvatarStmt:                   q.updateUserAvatarStmt,
		updateUserNameStmt:                     q.updateUserNameStmt,
		updateUserPasswordStmt:                 q.updateUserPasswordStmt,
		upsertAlbumStmt:                        q.upsertAlbumStmt,
		upsertAlbumGenreStmt:                   q.upsertAlbumGenreStmt,
		upsertMusicianStmt:                     q.upsertMusicianStmt,
		upsertMusicianGenreStmt:                q.upsertMusicianGenreStmt,
		upsertTrackStmt:                        q.upsertTrackStmt,
		upsertUserTrackStatsStmt:               q.upsertUserTrackStatsStmt,
	}
}
