// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Album struct {
	ID                int64           `json:"id"`
	Title             string          `json:"title"`
	SortTitle         string          `json:"sort_title"`
	Musician          sql.NullString  `json:"musician"`
	SpotifyID         sql.NullString  `json:"spotify_id"`
	SpotifyPopularity sql.NullFloat64 `json:"spotify_popularity"`
	ReleaseDate       sql.NullString  `json:"release_date"`
	Year              sql.NullInt64   `json:"year"`
	TotalTracks       sql.NullInt64   `json:"total_tracks"`
	Cover             sql.NullString  `json:"cover"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

type Genre struct {
	ID        int64  `json:"id"`
	Tag       string `json:"tag"`
	GenreType string `json:"genre_type"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Musician struct {
	ID                int64           `json:"id"`
	Name              string          `json:"name"`
	SortName          string          `json:"sort_name"`
	Summary           sql.NullString  `json:"summary"`
	SpotifyPopularity sql.NullFloat64 `json:"spotify_popularity"`
	SpotifyFollowers  sql.NullInt64   `json:"spotify_followers"`
	SpotifyID         sql.NullString  `json:"spotify_id"`
	Thumb             sql.NullString  `json:"thumb"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

type Playlist struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CoverImage  sql.NullString `json:"cover_image"`
	IsPublic    bool           `json:"is_public"`
	FolderID    sql.NullInt64  `json:"folder_id"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type PlaylistCollaborator struct {
	ID         int64  `json:"id"`
	PlaylistID int64  `json:"playlist_id"`
	UserID     int64  `json:"user_id"`
	CanEdit    bool   `json:"can_edit"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type PlaylistTrack struct {
	ID         int64         `json:"id"`
	PlaylistID int64         `json:"playlist_id"`
	TrackID    int64         `json:"track_id"`
	Position   int64         `json:"position"`
	AddedBy    sql.NullInt64 `json:"added_by"`
	AddedAt    string        `json:"added_at"`
}

type Setting struct {
	ID                         int64          `json:"id"`
	TmdbKey                    sql.NullString `json:"tmdb_key"`
	JellyfinToken              sql.NullString `json:"jellyfin_token"`
	SpotifyClientID            sql.NullString `json:"spotify_client_id"`
	SpotifyClientSecret        sql.NullString `json:"spotify_client_secret"`
	HardwareAccelerationDevice sql.NullString `json:"hardware_acceleration_device"`
	EnableLogger               bool           `json:"enable_logger"`
	EnableWatcher              bool           `json:"enable_watcher"`
	DownloadImages             bool           `json:"download_images"`
	MoviesDir                  sql.NullString `json:"movies_dir"`
	ShowsDir                   sql.NullString `json:"shows_dir"`
	MusicDir                   sql.NullString `json:"music_dir"`
	StaticDir                  string         `json:"static_dir"`
	LogsDir                    string         `json:"logs_dir"`
	CreatedAt                  string         `json:"created_at"`
	UpdatedAt                  string         `json:"updated_at"`
}

type Track struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	SortTitle     string         `json:"sort_title"`
	FilePath      string         `json:"file_path"`
	FileName      string         `json:"file_name"`
	Container     string         `json:"container"`
	MimeType      string         `json:"mime_type"`
	Codec         string         `json:"codec"`
	Size          int64          `json:"size"`
	TrackIndex    int64          `json:"track_index"`
	Duration      int64          `json:"duration"`
	Disc          int64          `json:"disc"`
	Channels      string         `json:"channels"`
	ChannelLayout string         `json:"channel_layout"`
	BitRate       int64          `json:"bit_rate"`
	Profile       string         `json:"profile"`
	ReleaseDate   sql.NullString `json:"release_date"`
	Year          sql.NullInt64  `json:"year"`
	Composer      sql.NullString `json:"composer"`
	Copyright     sql.NullString `json:"copyright"`
	Language      sql.NullString `json:"language"`
	AlbumID       sql.NullInt64  `json:"album_id"`
	MusicianID    sql.NullInt64  `json:"musician_id"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	IsAdmin   bool           `json:"is_admin"`
	Avatar    sql.NullString `json:"avatar"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}
