// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddCollaborator(ctx context.Context, arg AddCollaboratorParams) (PlaylistCollaborator, error)
	AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) (PlaylistTrack, error)
	CanUserEditPlaylist(ctx context.Context, arg CanUserEditPlaylistParams) (int64, error)
	// Quick check if track exists with same path and size (likely unchanged)
	CheckTrackUnchanged(ctx context.Context, arg CheckTrackUnchangedParams) (int64, error)
	ClearPlaylist(ctx context.Context, playlistID int64) error
	CountPlaylistTracks(ctx context.Context, playlistID int64) (int64, error)
	CountPlaylistsByUserId(ctx context.Context, userID int64) (int64, error)
	CreateMusicianAlbum(ctx context.Context, arg CreateMusicianAlbumParams) error
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreateSettings(ctx context.Context, arg CreateSettingsParams) (Setting, error)
	CreateTrackGenre(ctx context.Context, arg CreateTrackGenreParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deleting an album will cascade delete all associated tracks
	DeleteAlbum(ctx context.Context, id int64) error
	DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error
	DeleteTrackGenres(ctx context.Context, trackID int64) error
	// Deletes all genre relationships for a track except the specified genre.
	// Used to efficiently update genres: only removes stale relationships.
	DeleteTrackGenresExcept(ctx context.Context, arg DeleteTrackGenresExceptParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetAdminUser(ctx context.Context) (User, error)
	GetAlbumByID(ctx context.Context, id int64) (Album, error)
	GetAlbumBySpotifyID(ctx context.Context, spotifyID sql.NullString) (Album, error)
	// Returns albums sorted alphabetically by title with pagination.
	// Non-alphabetic titles (numbers, symbols) are grouped under '#' and sorted first.
	GetAlbumsAlphabetical(ctx context.Context, arg GetAlbumsAlphabeticalParams) ([]GetAlbumsAlphabeticalRow, error)
	// Returns all albums associated with a musician via the musician_albums join table
	// Sorted by release date (newest first), then by title
	GetAlbumsByMusicianID(ctx context.Context, musicianID int64) ([]GetAlbumsByMusicianIDRow, error)
	GetAlbumsCount(ctx context.Context) (int64, error)
	GetAllPlaylistTracks(ctx context.Context, playlistID int64) ([]GetAllPlaylistTracksRow, error)
	// Returns all track file paths and sizes for efficient batch skip-checking during scans.
	// Used to pre-load existing tracks into memory, replacing N individual queries with 1.
	GetAllTrackPathsAndSizes(ctx context.Context) ([]GetAllTrackPathsAndSizesRow, error)
	GetGenresByAlbumID(ctx context.Context, albumID sql.NullInt64) ([]GetGenresByAlbumIDRow, error)
	// Returns genres directly associated with an album via album_genres table
	GetGenresByAlbumIDDirect(ctx context.Context, albumID int64) ([]GetGenresByAlbumIDDirectRow, error)
	// Returns all genres associated with a musician
	GetGenresByMusicianID(ctx context.Context, musicianID int64) ([]GetGenresByMusicianIDRow, error)
	GetLatestAlbums(ctx context.Context) ([]GetLatestAlbumsRow, error)
	GetLikedTrackIDsByUserID(ctx context.Context, userID int64) ([]int64, error)
	GetLikedTracksByUserID(ctx context.Context, userID int64) ([]GetLikedTracksByUserIDRow, error)
	GetMaxPosition(ctx context.Context, playlistID int64) (interface{}, error)
	// Returns a single musician by ID with full details
	GetMusicianByID(ctx context.Context, id int64) (Musician, error)
	GetMusicianBySpotifyID(ctx context.Context, spotifyID sql.NullString) (Musician, error)
	// Returns musicians sorted alphabetically by sort_name with pagination.
	// Non-alphabetic names (numbers, symbols) are grouped under '#' and sorted first.
	GetMusiciansAlphabetical(ctx context.Context, arg GetMusiciansAlphabeticalParams) ([]GetMusiciansAlphabeticalRow, error)
	GetMusiciansByAlbumID(ctx context.Context, albumID int64) ([]GetMusiciansByAlbumIDRow, error)
	GetMusiciansCount(ctx context.Context) (int64, error)
	GetOrCreateGenre(ctx context.Context, arg GetOrCreateGenreParams) (Genre, error)
	GetPlaylistById(ctx context.Context, id int64) (Playlist, error)
	GetPlaylistCollaborators(ctx context.Context, playlistID int64) ([]GetPlaylistCollaboratorsRow, error)
	GetPlaylistDuration(ctx context.Context, playlistID int64) (interface{}, error)
	GetPlaylistTracksInfinite(ctx context.Context, arg GetPlaylistTracksInfiniteParams) ([]GetPlaylistTracksInfiniteRow, error)
	GetPlaylistsByUserId(ctx context.Context, userID int64) ([]GetPlaylistsByUserIdRow, error)
	GetPlaylistsWithCollaboratorAccess(ctx context.Context, arg GetPlaylistsWithCollaboratorAccessParams) ([]GetPlaylistsWithCollaboratorAccessRow, error)
	GetRandomTracks(ctx context.Context, limit int64) ([]GetRandomTracksRow, error)
	GetSettings(ctx context.Context) (Setting, error)
	GetTrack(ctx context.Context, id int64) (Track, error)
	GetTracksAlphabetical(ctx context.Context, arg GetTracksAlphabeticalParams) ([]GetTracksAlphabeticalRow, error)
	GetTracksByAlbumID(ctx context.Context, albumID sql.NullInt64) ([]Track, error)
	// Returns all tracks by a musician, sorted alphabetically by sort_title
	GetTracksByMusicianID(ctx context.Context, musicianID sql.NullInt64) ([]GetTracksByMusicianIDRow, error)
	GetTracksCount(ctx context.Context) (int64, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Returns listening stats grouped by date for charts
	GetUserListeningHistoryByPeriod(ctx context.Context, arg GetUserListeningHistoryByPeriodParams) ([]GetUserListeningHistoryByPeriodRow, error)
	// Returns overall listening statistics for a user
	GetUserListeningStats(ctx context.Context, arg GetUserListeningStatsParams) (GetUserListeningStatsRow, error)
	// Returns the user's recently played tracks
	GetUserRecentlyPlayed(ctx context.Context, arg GetUserRecentlyPlayedParams) ([]GetUserRecentlyPlayedRow, error)
	// Returns the user's most listened albums
	GetUserTopAlbums(ctx context.Context, arg GetUserTopAlbumsParams) ([]GetUserTopAlbumsRow, error)
	// Returns the user's most listened genres
	GetUserTopGenres(ctx context.Context, arg GetUserTopGenresParams) ([]GetUserTopGenresRow, error)
	// Returns the user's most listened musicians by total play count
	GetUserTopMusicians(ctx context.Context, arg GetUserTopMusiciansParams) ([]GetUserTopMusiciansRow, error)
	// ============================================================================
	// USER STATISTICS QUERIES
	// ============================================================================
	// Returns the user's most played tracks
	GetUserTopTracks(ctx context.Context, arg GetUserTopTracksParams) ([]GetUserTopTracksRow, error)
	// Returns the play count for a specific track
	GetUserTrackPlayCount(ctx context.Context, arg GetUserTrackPlayCountParams) (int64, error)
	IsTrackInPlaylist(ctx context.Context, arg IsTrackInPlaylistParams) (int64, error)
	IsTrackLiked(ctx context.Context, arg IsTrackLikedParams) (bool, error)
	IsUserCollaborator(ctx context.Context, arg IsUserCollaboratorParams) (int64, error)
	LikeTrack(ctx context.Context, arg LikeTrackParams) error
	// ============================================================================
	// PLAY HISTORY RECORDING
	// ============================================================================
	// Records a new play event when a track is played
	RecordPlayEvent(ctx context.Context, arg RecordPlayEventParams) error
	RemoveCollaborator(ctx context.Context, arg RemoveCollaboratorParams) error
	RemoveTrackFromPlaylist(ctx context.Context, arg RemoveTrackFromPlaylistParams) error
	ShiftPositionsDown(ctx context.Context, arg ShiftPositionsDownParams) error
	ShiftPositionsUp(ctx context.Context, arg ShiftPositionsUpParams) error
	UnlikeTrack(ctx context.Context, arg UnlikeTrackParams) error
	UpdateCollaboratorPermission(ctx context.Context, arg UpdateCollaboratorPermissionParams) error
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error)
	UpdatePlaylistTimestamp(ctx context.Context, id int64) error
	UpdateTrackPosition(ctx context.Context, arg UpdateTrackPositionParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (Album, error)
	// Creates a relationship between an album and a genre (idempotent)
	UpsertAlbumGenre(ctx context.Context, arg UpsertAlbumGenreParams) error
	UpsertMusician(ctx context.Context, arg UpsertMusicianParams) (Musician, error)
	// Creates a relationship between a musician and a genre (idempotent)
	UpsertMusicianGenre(ctx context.Context, arg UpsertMusicianGenreParams) error
	UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error)
	// Updates aggregated stats when a play event is recorded
	UpsertUserTrackStats(ctx context.Context, arg UpsertUserTrackStatsParams) error
}

var _ Querier = (*Queries)(nil)
