services:
  postgres:
    image: postgres:alpine
    container_name: igloo_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "${POSTGRES_DATA_PATH:-./pg_data}:/var/lib/postgresql/18/docker"
      - ../sqlc/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: igloo_redis
    env_file:
      - .env
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: sh -c "redis-server --user $${REDIS_USER} on >$${REDIS_PASSWORD} ~* &* +@all --requirepass $${REDIS_PASSWORD} --appendonly yes"
    volumes:
      - "${REDIS_DATA_PATH:-./redis_data}:/data"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -u redis://$${REDIS_USER}:$${REDIS_PASSWORD}@localhost:6379 ping",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
