// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track_genres.sql

package database

import (
	"context"
	"database/sql"
)

const createTrackGenre = `-- name: CreateTrackGenre :exec
INSERT INTO track_genres (track_id, genre_id)
VALUES (?, ?)
ON CONFLICT (track_id, genre_id) DO NOTHING
`

type CreateTrackGenreParams struct {
	TrackID int64 `json:"track_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) CreateTrackGenre(ctx context.Context, arg CreateTrackGenreParams) error {
	_, err := q.exec(ctx, q.createTrackGenreStmt, createTrackGenre, arg.TrackID, arg.GenreID)
	return err
}

const deleteTrackGenres = `-- name: DeleteTrackGenres :exec
DELETE FROM track_genres WHERE track_id = ?
`

func (q *Queries) DeleteTrackGenres(ctx context.Context, trackID int64) error {
	_, err := q.exec(ctx, q.deleteTrackGenresStmt, deleteTrackGenres, trackID)
	return err
}

const deleteTrackGenresExcept = `-- name: DeleteTrackGenresExcept :exec
DELETE FROM track_genres WHERE track_id = ? AND genre_id != ?
`

type DeleteTrackGenresExceptParams struct {
	TrackID int64 `json:"track_id"`
	GenreID int64 `json:"genre_id"`
}

// Deletes all genre relationships for a track except the specified genre.
// Used to efficiently update genres: only removes stale relationships.
func (q *Queries) DeleteTrackGenresExcept(ctx context.Context, arg DeleteTrackGenresExceptParams) error {
	_, err := q.exec(ctx, q.deleteTrackGenresExceptStmt, deleteTrackGenresExcept, arg.TrackID, arg.GenreID)
	return err
}

const getGenresByAlbumID = `-- name: GetGenresByAlbumID :many
SELECT
  tg.track_id,
  g.id AS genre_id,
  g.tag
FROM
  track_genres tg
  INNER JOIN genres g ON tg.genre_id = g.id
  INNER JOIN tracks t ON tg.track_id = t.id
WHERE
  t.album_id = ?
ORDER BY
  tg.track_id,
  g.tag
`

type GetGenresByAlbumIDRow struct {
	TrackID int64  `json:"track_id"`
	GenreID int64  `json:"genre_id"`
	Tag     string `json:"tag"`
}

func (q *Queries) GetGenresByAlbumID(ctx context.Context, albumID sql.NullInt64) ([]GetGenresByAlbumIDRow, error) {
	rows, err := q.query(ctx, q.getGenresByAlbumIDStmt, getGenresByAlbumID, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGenresByAlbumIDRow{}
	for rows.Next() {
		var i GetGenresByAlbumIDRow
		if err := rows.Scan(&i.TrackID, &i.GenreID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
