#!/usr/bin/env bash
set -euo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
env_file=${1:-"$repo_root/.env"}
output_file=${2:-"$repo_root/compose.override.yaml"}
marker="# Generated by scripts/generate-compose-media-override.sh; do not edit."

trim() {
  local value=$1
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

unquote() {
  local value=$1
  if [[ ${#value} -ge 2 ]]; then
    local first=${value:0:1}
    local last=${value: -1}
    if [[ ($first == "'" && $last == "'") || ($first == '"' && $last == '"') ]]; then
      value=${value:1:${#value}-2}
    fi
  fi
  printf '%s' "$value"
}

yaml_quote() {
  local value=$1
  value=${value//\'/\'\'}
  printf "'%s'" "$value"
}

[[ -f "$env_file" ]] || die "env file not found: $env_file"
env_dir=$(CDPATH= cd -- "$(dirname -- "$env_file")" && pwd)

declare -A env_values=()
while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
  line=${raw_line%$'\r'}
  line=$(trim "$line")

  [[ -n "$line" ]] || continue
  [[ ${line:0:1} != "#" ]] || continue

  if [[ $line =~ ^export[[:space:]]+(.+)$ ]]; then
    line=${BASH_REMATCH[1]}
  fi

  [[ $line == *"="* ]] || continue

  key=$(trim "${line%%=*}")
  value=$(trim "${line#*=}")

  [[ $key =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue

  env_values["$key"]=$(unquote "$value")
done < "$env_file"

declare -a media_env_names=()
declare -a media_targets=()
declare -a media_sources=()

add_media_mount() {
  local env_name=$1
  local container_path=$2
  local raw_value=${env_values[$env_name]-}
  local host_path
  local resolved_path

  raw_value=$(trim "$raw_value")
  [[ -n "$raw_value" ]] || return 0

  if [[ $raw_value = /* ]]; then
    host_path=$raw_value
  else
    host_path=$env_dir/$raw_value
  fi

  [[ -d "$host_path" ]] || die "$env_name is set to '$raw_value' but directory does not exist: $host_path"

  resolved_path=$(CDPATH= cd -- "$host_path" && pwd -P) || die "$env_name is set to '$raw_value' but the directory is not accessible"

  media_env_names+=("$env_name")
  media_targets+=("$container_path")
  media_sources+=("$resolved_path")
}

add_media_mount MOVIES_DIR /media/movies
add_media_mount SHOWS_DIR /media/shows
add_media_mount MUSIC_DIR /media/music

if [[ -e "$output_file" ]] && ! grep -Fqx "$marker" "$output_file"; then
  die "$output_file already exists and was not generated by this script"
fi

if [[ ${#media_env_names[@]} -eq 0 ]]; then
  if [[ -e "$output_file" ]]; then
    rm -f "$output_file"
    printf 'Removed %s because no media directories are configured.\n' "$output_file"
  else
    printf 'No media directories configured; no Compose override needed.\n'
  fi
  exit 0
fi

tmp_file=$(mktemp "${output_file}.tmp.XXXXXX")
trap 'rm -f "$tmp_file"' EXIT

{
  printf '%s\n' "$marker"
  printf 'services:\n'
  printf '  igloo:\n'
  printf '    environment:\n'

  for i in "${!media_env_names[@]}"; do
    printf '      %s: %s\n' "${media_env_names[$i]}" "${media_targets[$i]}"
  done

  printf '    volumes:\n'

  for i in "${!media_env_names[@]}"; do
    printf '      - type: bind\n'
    printf '        source: '
    yaml_quote "${media_sources[$i]}"
    printf '\n'
    printf '        target: %s\n' "${media_targets[$i]}"
    printf '        read_only: true\n'
    printf '        bind:\n'
    printf '          create_host_path: false\n'
  done
} > "$tmp_file"

mv "$tmp_file" "$output_file"
trap - EXIT

printf 'Wrote %s with %d media mount(s).\n' "$output_file" "${#media_env_names[@]}"
