/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/solid-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthMoviesIndexImport } from './routes/_auth/movies/index'
import { Route as AuthMoviesMovieIDImport } from './routes/_auth/movies/$movieID'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const AuthMoviesMovieIDPlayLazyImport = createFileRoute(
  '/_auth/movies/$movieID/play',
)()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthMoviesIndexRoute = AuthMoviesIndexImport.update({
  id: '/_auth/movies/',
  path: '/movies/',
  getParentRoute: () => rootRoute,
} as any)

const AuthMoviesMovieIDRoute = AuthMoviesMovieIDImport.update({
  id: '/_auth/movies/$movieID',
  path: '/movies/$movieID',
  getParentRoute: () => rootRoute,
} as any)

const AuthMoviesMovieIDPlayLazyRoute = AuthMoviesMovieIDPlayLazyImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthMoviesMovieIDRoute,
} as any).lazy(() =>
  import('./routes/_auth/movies/$movieID.play.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/movies/$movieID': {
      id: '/_auth/movies/$movieID'
      path: '/movies/$movieID'
      fullPath: '/movies/$movieID'
      preLoaderRoute: typeof AuthMoviesMovieIDImport
      parentRoute: typeof rootRoute
    }
    '/_auth/movies/': {
      id: '/_auth/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AuthMoviesIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/movies/$movieID/play': {
      id: '/_auth/movies/$movieID/play'
      path: '/play'
      fullPath: '/movies/$movieID/play'
      preLoaderRoute: typeof AuthMoviesMovieIDPlayLazyImport
      parentRoute: typeof AuthMoviesMovieIDImport
    }
  }
}

// Create and export the route tree

interface AuthMoviesMovieIDRouteChildren {
  AuthMoviesMovieIDPlayLazyRoute: typeof AuthMoviesMovieIDPlayLazyRoute
}

const AuthMoviesMovieIDRouteChildren: AuthMoviesMovieIDRouteChildren = {
  AuthMoviesMovieIDPlayLazyRoute: AuthMoviesMovieIDPlayLazyRoute,
}

const AuthMoviesMovieIDRouteWithChildren =
  AuthMoviesMovieIDRoute._addFileChildren(AuthMoviesMovieIDRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/movies/$movieID': typeof AuthMoviesMovieIDRouteWithChildren
  '/movies': typeof AuthMoviesIndexRoute
  '/movies/$movieID/play': typeof AuthMoviesMovieIDPlayLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/movies/$movieID': typeof AuthMoviesMovieIDRouteWithChildren
  '/movies': typeof AuthMoviesIndexRoute
  '/movies/$movieID/play': typeof AuthMoviesMovieIDPlayLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/_auth/movies/$movieID': typeof AuthMoviesMovieIDRouteWithChildren
  '/_auth/movies/': typeof AuthMoviesIndexRoute
  '/_auth/movies/$movieID/play': typeof AuthMoviesMovieIDPlayLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/movies/$movieID'
    | '/movies'
    | '/movies/$movieID/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/movies/$movieID' | '/movies' | '/movies/$movieID/play'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/_auth/movies/$movieID'
    | '/_auth/movies/'
    | '/_auth/movies/$movieID/play'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginLazyRoute: typeof LoginLazyRoute
  AuthMoviesMovieIDRoute: typeof AuthMoviesMovieIDRouteWithChildren
  AuthMoviesIndexRoute: typeof AuthMoviesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginLazyRoute: LoginLazyRoute,
  AuthMoviesMovieIDRoute: AuthMoviesMovieIDRouteWithChildren,
  AuthMoviesIndexRoute: AuthMoviesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/_auth/movies/$movieID",
        "/_auth/movies/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/_auth/movies/$movieID": {
      "filePath": "_auth/movies/$movieID.tsx",
      "children": [
        "/_auth/movies/$movieID/play"
      ]
    },
    "/_auth/movies/": {
      "filePath": "_auth/movies/index.tsx"
    },
    "/_auth/movies/$movieID/play": {
      "filePath": "_auth/movies/$movieID.play.lazy.tsx",
      "parent": "/_auth/movies/$movieID"
    }
  }
}
ROUTE_MANIFEST_END */
