// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package database

import (
	"context"
	"database/sql"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
  user_id,
  name,
  platform,
  app_version,
  token_hash
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, platform, app_version, token_hash, created_at, last_used_at
`

type CreateDeviceParams struct {
	UserID     int64          `json:"user_id"`
	Name       string         `json:"name"`
	Platform   string         `json:"platform"`
	AppVersion sql.NullString `json:"app_version"`
	TokenHash  string         `json:"token_hash"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.queryRow(ctx, q.createDeviceStmt, createDevice,
		arg.UserID,
		arg.Name,
		arg.Platform,
		arg.AppVersion,
		arg.TokenHash,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteDeviceForUser = `-- name: DeleteDeviceForUser :execrows
DELETE FROM devices
WHERE id = ?1
  AND user_id = ?2
`

type DeleteDeviceForUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteDeviceForUser(ctx context.Context, arg DeleteDeviceForUserParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteDeviceForUserStmt, deleteDeviceForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
SELECT id, user_id, name, platform, app_version, token_hash, created_at, last_used_at
FROM devices
WHERE token_hash = ?
LIMIT 1
`

func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash string) (Device, error) {
	row := q.queryRow(ctx, q.getDeviceByTokenHashStmt, getDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getDevicesByUser = `-- name: GetDevicesByUser :many
SELECT
  id,
  user_id,
  name,
  platform,
  app_version,
  created_at,
  last_used_at
FROM devices
WHERE user_id = ?
ORDER BY last_used_at DESC, id DESC
`

type GetDevicesByUserRow struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	Name       string         `json:"name"`
	Platform   string         `json:"platform"`
	AppVersion sql.NullString `json:"app_version"`
	CreatedAt  string         `json:"created_at"`
	LastUsedAt string         `json:"last_used_at"`
}

func (q *Queries) GetDevicesByUser(ctx context.Context, userID int64) ([]GetDevicesByUserRow, error) {
	rows, err := q.query(ctx, q.getDevicesByUserStmt, getDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDevicesByUserRow{}
	for rows.Next() {
		var i GetDevicesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Platform,
			&i.AppVersion,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameDevice = `-- name: RenameDevice :execrows
UPDATE devices
SET name = ?1
WHERE id = ?2
  AND user_id = ?3
`

type RenameDeviceParams struct {
	Name   string `json:"name"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) RenameDevice(ctx context.Context, arg RenameDeviceParams) (int64, error) {
	result, err := q.exec(ctx, q.renameDeviceStmt, renameDevice, arg.Name, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeviceLastUsed = `-- name: UpdateDeviceLastUsed :exec
UPDATE devices
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateDeviceLastUsed(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.updateDeviceLastUsedStmt, updateDeviceLastUsed, id)
	return err
}
