// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Album struct {
	ID                int64           `json:"id"`
	Title             string          `json:"title"`
	SortTitle         string          `json:"sort_title"`
	SpotifyID         sql.NullString  `json:"spotify_id"`
	SpotifyPopularity sql.NullFloat64 `json:"spotify_popularity"`
	Musician          sql.NullString  `json:"musician"`
	ReleaseDate       sql.NullString  `json:"release_date"`
	Year              sql.NullInt64   `json:"year"`
	TotalTracks       sql.NullInt64   `json:"total_tracks"`
	Cover             sql.NullString  `json:"cover"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

type Artist struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	TmdbID    int64          `json:"tmdb_id"`
	Profile   sql.NullString `json:"profile"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type AudioStream struct {
	ID            int64          `json:"id"`
	MovieID       int64          `json:"movie_id"`
	StreamIndex   int64          `json:"stream_index"`
	Codec         string         `json:"codec"`
	CodecProfile  sql.NullString `json:"codec_profile"`
	BitRate       int64          `json:"bit_rate"`
	SampleRate    sql.NullInt64  `json:"sample_rate"`
	Channels      int64          `json:"channels"`
	ChannelLayout sql.NullString `json:"channel_layout"`
	Language      sql.NullString `json:"language"`
	Title         sql.NullString `json:"title"`
	IsDefault     bool           `json:"is_default"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type Cast struct {
	ID        int64  `json:"id"`
	MovieID   int64  `json:"movie_id"`
	ArtistID  int64  `json:"artist_id"`
	Character string `json:"character"`
	CastOrder int64  `json:"cast_order"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Chapter struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	StartTime int64          `json:"start_time"`
	Thumb     sql.NullString `json:"thumb"`
	MovieID   int64          `json:"movie_id"`
}

type Crew struct {
	ID         int64  `json:"id"`
	MovieID    int64  `json:"movie_id"`
	ArtistID   int64  `json:"artist_id"`
	Job        string `json:"job"`
	Department string `json:"department"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type Device struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	Name       string         `json:"name"`
	Platform   string         `json:"platform"`
	AppVersion sql.NullString `json:"app_version"`
	TokenHash  string         `json:"token_hash"`
	CreatedAt  string         `json:"created_at"`
	LastUsedAt string         `json:"last_used_at"`
}

type ExtraVideo struct {
	ID         int64          `json:"id"`
	Title      string         `json:"title"`
	ExternalID sql.NullString `json:"external_id"`
	Key        string         `json:"key"`
	Type       string         `json:"type"`
	Site       string         `json:"site"`
	Official   bool           `json:"official"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type Genre struct {
	ID        int64  `json:"id"`
	Tag       string `json:"tag"`
	GenreType string `json:"genre_type"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type KeyframeIndex struct {
	MovieID     int64   `json:"movie_id"`
	StreamIndex int64   `json:"stream_index"`
	Fingerprint string  `json:"fingerprint"`
	DurationSec float64 `json:"duration_sec"`
	Keyframes   string  `json:"keyframes"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type Movie struct {
	ID             int64           `json:"id"`
	Title          string          `json:"title"`
	FilePath       string          `json:"file_path"`
	FileName       string          `json:"file_name"`
	Size           int64           `json:"size"`
	Container      string          `json:"container"`
	MimeType       string          `json:"mime_type"`
	Adult          bool            `json:"adult"`
	TmdbID         sql.NullInt64   `json:"tmdb_id"`
	ImdbID         sql.NullString  `json:"imdb_id"`
	PosterPath     sql.NullString  `json:"poster_path"`
	BackdropPath   sql.NullString  `json:"backdrop_path"`
	Language       sql.NullString  `json:"language"`
	Year           sql.NullInt64   `json:"year"`
	ReleaseDate    sql.NullString  `json:"release_date"`
	Overview       sql.NullString  `json:"overview"`
	TagLine        sql.NullString  `json:"tag_line"`
	Certification  sql.NullString  `json:"certification"`
	CriticRating   sql.NullFloat64 `json:"critic_rating"`
	AudienceRating sql.NullFloat64 `json:"audience_rating"`
	Revenue        sql.NullFloat64 `json:"revenue"`
	Budget         sql.NullFloat64 `json:"budget"`
	RunTime        sql.NullInt64   `json:"run_time"`
	Duration       sql.NullFloat64 `json:"duration"`
	CreatedAt      string          `json:"created_at"`
	UpdatedAt      string          `json:"updated_at"`
}

type MovieWatchProgress struct {
	UserID        int64   `json:"user_id"`
	MovieID       int64   `json:"movie_id"`
	ProgressSec   float64 `json:"progress_sec"`
	DurationSec   float64 `json:"duration_sec"`
	Watched       bool    `json:"watched"`
	SaveSessionID string  `json:"save_session_id"`
	SaveSequence  int64   `json:"save_sequence"`
	UpdatedAt     string  `json:"updated_at"`
}

type MusicSpotifyMatch struct {
	EntityType      string         `json:"entity_type"`
	EntityID        int64          `json:"entity_id"`
	SpotifyID       sql.NullString `json:"spotify_id"`
	Status          string         `json:"status"`
	Reason          sql.NullString `json:"reason"`
	Score           sql.NullInt64  `json:"score"`
	ThresholdValue  sql.NullInt64  `json:"threshold_value"`
	CandidateName   sql.NullString `json:"candidate_name"`
	CandidateArtist sql.NullString `json:"candidate_artist"`
	SearchQuery     sql.NullString `json:"search_query"`
	Strategy        sql.NullString `json:"strategy"`
	Error           sql.NullString `json:"error"`
	UpdatedAt       string         `json:"updated_at"`
}

type Musician struct {
	ID                int64           `json:"id"`
	Name              string          `json:"name"`
	SortName          string          `json:"sort_name"`
	Summary           sql.NullString  `json:"summary"`
	SpotifyID         sql.NullString  `json:"spotify_id"`
	SpotifyPopularity sql.NullFloat64 `json:"spotify_popularity"`
	SpotifyFollowers  sql.NullInt64   `json:"spotify_followers"`
	Thumb             sql.NullString  `json:"thumb"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

type Notification struct {
	ID              int64  `json:"id"`
	CreatedByUserID int64  `json:"created_by_user_id"`
	Title           string `json:"title"`
	Message         string `json:"message"`
	IsAdmin         bool   `json:"is_admin"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type Playlist struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CoverImage  sql.NullString `json:"cover_image"`
	IsPublic    bool           `json:"is_public"`
	MovieID     sql.NullInt64  `json:"movie_id"`
	ContentType string         `json:"content_type"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type PlaylistCollaborator struct {
	ID         int64  `json:"id"`
	PlaylistID int64  `json:"playlist_id"`
	UserID     int64  `json:"user_id"`
	CanEdit    bool   `json:"can_edit"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ProductionCompany struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	TmdbID    int64          `json:"tmdb_id"`
	Logo      sql.NullString `json:"logo"`
	Country   sql.NullString `json:"country"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type RemuxSafetyVerdict struct {
	MovieID     int64  `json:"movie_id"`
	StreamIndex int64  `json:"stream_index"`
	Fingerprint string `json:"fingerprint"`
	Safe        bool   `json:"safe"`
	Reason      string `json:"reason"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Setting struct {
	ID                         int64           `json:"id"`
	TmdbKey                    sql.NullString  `json:"tmdb_key"`
	ImmichBaseUrl              sql.NullString  `json:"immich_base_url"`
	ImmichApiKey               sql.NullString  `json:"immich_api_key"`
	JellyfinBaseUrl            sql.NullString  `json:"jellyfin_base_url"`
	JellyfinApiKey             sql.NullString  `json:"jellyfin_api_key"`
	SpotifyClientID            sql.NullString  `json:"spotify_client_id"`
	SpotifyClientSecret        sql.NullString  `json:"spotify_client_secret"`
	HardwareAccelerationDevice sql.NullString  `json:"hardware_acceleration_device"`
	EnableWatcher              bool            `json:"enable_watcher"`
	DownloadImages             bool            `json:"download_images"`
	MoviesDir                  sql.NullString  `json:"movies_dir"`
	ShowsDir                   sql.NullString  `json:"shows_dir"`
	MusicDir                   sql.NullString  `json:"music_dir"`
	ServerUploadMbps           sql.NullFloat64 `json:"server_upload_mbps"`
	StaticDir                  string          `json:"static_dir"`
	TranscodeDir               string          `json:"transcode_dir"`
	CreatedAt                  string          `json:"created_at"`
	UpdatedAt                  string          `json:"updated_at"`
}

type Subtitle struct {
	ID          int64          `json:"id"`
	MovieID     int64          `json:"movie_id"`
	StreamIndex int64          `json:"stream_index"`
	Codec       string         `json:"codec"`
	Language    sql.NullString `json:"language"`
	Title       sql.NullString `json:"title"`
	IsForced    bool           `json:"is_forced"`
	IsDefault   bool           `json:"is_default"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type Track struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	SortTitle     string         `json:"sort_title"`
	FilePath      string         `json:"file_path"`
	FileName      string         `json:"file_name"`
	Container     string         `json:"container"`
	MimeType      string         `json:"mime_type"`
	Codec         string         `json:"codec"`
	Size          int64          `json:"size"`
	TrackIndex    int64          `json:"track_index"`
	Duration      int64          `json:"duration"`
	Disc          int64          `json:"disc"`
	Channels      string         `json:"channels"`
	ChannelLayout string         `json:"channel_layout"`
	BitRate       int64          `json:"bit_rate"`
	Profile       string         `json:"profile"`
	ReleaseDate   sql.NullString `json:"release_date"`
	Year          sql.NullInt64  `json:"year"`
	Composer      sql.NullString `json:"composer"`
	Copyright     sql.NullString `json:"copyright"`
	Language      sql.NullString `json:"language"`
	AlbumID       sql.NullInt64  `json:"album_id"`
	MusicianID    sql.NullInt64  `json:"musician_id"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	IsAdmin   bool           `json:"is_admin"`
	Avatar    sql.NullString `json:"avatar"`
	Pin       sql.NullString `json:"pin"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type VideoStream struct {
	ID             int64          `json:"id"`
	MovieID        int64          `json:"movie_id"`
	StreamIndex    int64          `json:"stream_index"`
	Codec          string         `json:"codec"`
	CodecProfile   sql.NullString `json:"codec_profile"`
	CodecLevel     sql.NullInt64  `json:"codec_level"`
	BitRate        int64          `json:"bit_rate"`
	Width          int64          `json:"width"`
	Height         int64          `json:"height"`
	CodedWidth     sql.NullInt64  `json:"coded_width"`
	CodedHeight    sql.NullInt64  `json:"coded_height"`
	AspectRatio    sql.NullString `json:"aspect_ratio"`
	FrameRate      float64        `json:"frame_rate"`
	AvgFrameRate   sql.NullString `json:"avg_frame_rate"`
	BitDepth       sql.NullInt64  `json:"bit_depth"`
	PixelFormat    sql.NullString `json:"pixel_format"`
	ColorRange     sql.NullString `json:"color_range"`
	ColorSpace     sql.NullString `json:"color_space"`
	ColorPrimaries sql.NullString `json:"color_primaries"`
	ColorTransfer  sql.NullString `json:"color_transfer"`
	FieldOrder     sql.NullString `json:"field_order"`
	Rotation       sql.NullInt64  `json:"rotation"`
	Language       sql.NullString `json:"language"`
	Title          sql.NullString `json:"title"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type WatchRoom struct {
	ID                  int64          `json:"id"`
	OwnerUserID         int64          `json:"owner_user_id"`
	MovieID             int64          `json:"movie_id"`
	PlaybackMode        string         `json:"playback_mode"`
	AudioTrack          int64          `json:"audio_track"`
	SubtitleTrack       sql.NullInt64  `json:"subtitle_track"`
	AudioStreamIndex    sql.NullInt64  `json:"audio_stream_index"`
	AudioLanguage       sql.NullString `json:"audio_language"`
	SubtitleStreamIndex sql.NullInt64  `json:"subtitle_stream_index"`
	SubtitleLanguage    sql.NullString `json:"subtitle_language"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}
