// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movie_watch_progress.sql

package database

import (
	"context"
	"database/sql"
)

const deleteMovieWatchProgress = `-- name: DeleteMovieWatchProgress :exec
DELETE FROM movie_watch_progress
WHERE user_id = ?
  AND movie_id = ?
`

type DeleteMovieWatchProgressParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) DeleteMovieWatchProgress(ctx context.Context, arg DeleteMovieWatchProgressParams) error {
	_, err := q.exec(ctx, q.deleteMovieWatchProgressStmt, deleteMovieWatchProgress, arg.UserID, arg.MovieID)
	return err
}

const getContinueWatchingMovies = `-- name: GetContinueWatchingMovies :many
SELECT
  m.id,
  m.title,
  m.poster_path,
  m.year,
  mwp.progress_sec,
  mwp.duration_sec
FROM movie_watch_progress AS mwp
JOIN movies AS m ON m.id = mwp.movie_id
WHERE mwp.user_id = ?
  AND mwp.watched = false
  AND mwp.progress_sec >= 30
  AND mwp.duration_sec > 0
  AND mwp.progress_sec < mwp.duration_sec
ORDER BY mwp.updated_at DESC
LIMIT 12
`

type GetContinueWatchingMoviesRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	PosterPath  sql.NullString `json:"poster_path"`
	Year        sql.NullInt64  `json:"year"`
	ProgressSec float64        `json:"progress_sec"`
	DurationSec float64        `json:"duration_sec"`
}

// The 30-second floor must match the web client's
// MOVIE_WATCH_PROGRESS_MIN_SECONDS resume-eligibility floor.
func (q *Queries) GetContinueWatchingMovies(ctx context.Context, userID int64) ([]GetContinueWatchingMoviesRow, error) {
	rows, err := q.query(ctx, q.getContinueWatchingMoviesStmt, getContinueWatchingMovies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContinueWatchingMoviesRow{}
	for rows.Next() {
		var i GetContinueWatchingMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PosterPath,
			&i.Year,
			&i.ProgressSec,
			&i.DurationSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieWatchProgress = `-- name: GetMovieWatchProgress :one
SELECT
  user_id,
  movie_id,
  progress_sec,
  duration_sec,
  watched,
  updated_at
FROM movie_watch_progress
WHERE user_id = ?
  AND movie_id = ?
`

type GetMovieWatchProgressParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) GetMovieWatchProgress(ctx context.Context, arg GetMovieWatchProgressParams) (MovieWatchProgress, error) {
	row := q.queryRow(ctx, q.getMovieWatchProgressStmt, getMovieWatchProgress, arg.UserID, arg.MovieID)
	var i MovieWatchProgress
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.ProgressSec,
		&i.DurationSec,
		&i.Watched,
		&i.UpdatedAt,
	)
	return i, err
}

const markMovieUnwatched = `-- name: MarkMovieUnwatched :exec
INSERT INTO movie_watch_progress (
  user_id,
  movie_id,
  progress_sec,
  duration_sec,
  watched,
  updated_at
)
VALUES
  (?, ?, 0, 0, false, CURRENT_TIMESTAMP)
ON CONFLICT (user_id, movie_id) DO UPDATE
SET
  watched = false,
  updated_at = CURRENT_TIMESTAMP
`

type MarkMovieUnwatchedParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) MarkMovieUnwatched(ctx context.Context, arg MarkMovieUnwatchedParams) error {
	_, err := q.exec(ctx, q.markMovieUnwatchedStmt, markMovieUnwatched, arg.UserID, arg.MovieID)
	return err
}

const markMovieWatched = `-- name: MarkMovieWatched :exec
INSERT INTO movie_watch_progress (
  user_id,
  movie_id,
  progress_sec,
  duration_sec,
  watched,
  updated_at
)
VALUES
  (?, ?, 0, 0, true, CURRENT_TIMESTAMP)
ON CONFLICT (user_id, movie_id) DO UPDATE
SET
  progress_sec = 0,
  watched = true,
  updated_at = CURRENT_TIMESTAMP
`

type MarkMovieWatchedParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) MarkMovieWatched(ctx context.Context, arg MarkMovieWatchedParams) error {
	_, err := q.exec(ctx, q.markMovieWatchedStmt, markMovieWatched, arg.UserID, arg.MovieID)
	return err
}

const upsertMovieWatchProgress = `-- name: UpsertMovieWatchProgress :exec
INSERT INTO movie_watch_progress (
  user_id,
  movie_id,
  progress_sec,
  duration_sec,
  watched,
  updated_at
)
VALUES
  (?, ?, ?, ?, false, CURRENT_TIMESTAMP)
ON CONFLICT (user_id, movie_id) DO UPDATE
SET
  progress_sec = excluded.progress_sec,
  duration_sec = excluded.duration_sec,
  watched = false,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertMovieWatchProgressParams struct {
	UserID      int64   `json:"user_id"`
	MovieID     int64   `json:"movie_id"`
	ProgressSec float64 `json:"progress_sec"`
	DurationSec float64 `json:"duration_sec"`
}

func (q *Queries) UpsertMovieWatchProgress(ctx context.Context, arg UpsertMovieWatchProgressParams) error {
	_, err := q.exec(ctx, q.upsertMovieWatchProgressStmt, upsertMovieWatchProgress,
		arg.UserID,
		arg.MovieID,
		arg.ProgressSec,
		arg.DurationSec,
	)
	return err
}
