// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: music_spotify_matches.sql

package database

import (
	"context"
	"database/sql"
)

const getMusicSpotifyMatch = `-- name: GetMusicSpotifyMatch :one
SELECT status, reason
FROM music_spotify_matches
WHERE entity_type = ? AND entity_id = ?
LIMIT 1
`

type GetMusicSpotifyMatchParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

type GetMusicSpotifyMatchRow struct {
	Status string         `json:"status"`
	Reason sql.NullString `json:"reason"`
}

func (q *Queries) GetMusicSpotifyMatch(ctx context.Context, arg GetMusicSpotifyMatchParams) (GetMusicSpotifyMatchRow, error) {
	row := q.queryRow(ctx, q.getMusicSpotifyMatchStmt, getMusicSpotifyMatch, arg.EntityType, arg.EntityID)
	var i GetMusicSpotifyMatchRow
	err := row.Scan(&i.Status, &i.Reason)
	return i, err
}

const upsertMusicSpotifyMatch = `-- name: UpsertMusicSpotifyMatch :exec
INSERT INTO music_spotify_matches (entity_type, entity_id, status, reason)
VALUES (?, ?, ?, ?)
ON CONFLICT (entity_type, entity_id) DO UPDATE
SET status = excluded.status, reason = excluded.reason
`

type UpsertMusicSpotifyMatchParams struct {
	EntityType string         `json:"entity_type"`
	EntityID   int64          `json:"entity_id"`
	Status     string         `json:"status"`
	Reason     sql.NullString `json:"reason"`
}

func (q *Queries) UpsertMusicSpotifyMatch(ctx context.Context, arg UpsertMusicSpotifyMatchParams) error {
	_, err := q.exec(ctx, q.upsertMusicSpotifyMatchStmt, upsertMusicSpotifyMatch,
		arg.EntityType,
		arg.EntityID,
		arg.Status,
		arg.Reason,
	)
	return err
}
