// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: musician_albums.sql

package database

import (
	"context"
)

const createMusicianAlbum = `-- name: CreateMusicianAlbum :exec
INSERT INTO musician_albums (
  musician_id,
  album_id
)
VALUES
  (?, ?)
ON CONFLICT (musician_id, album_id) DO NOTHING
`

type CreateMusicianAlbumParams struct {
	MusicianID int64 `json:"musician_id"`
	AlbumID    int64 `json:"album_id"`
}

func (q *Queries) CreateMusicianAlbum(ctx context.Context, arg CreateMusicianAlbumParams) error {
	_, err := q.exec(ctx, q.createMusicianAlbumStmt, createMusicianAlbum, arg.MusicianID, arg.AlbumID)
	return err
}

const deleteAlbumMusiciansWithoutTracks = `-- name: DeleteAlbumMusiciansWithoutTracks :exec
DELETE FROM musician_albums
WHERE musician_albums.album_id = ?1
  AND NOT EXISTS (
    SELECT 1
    FROM albums
    INNER JOIN musicians
      ON musicians.id = musician_albums.musician_id
    WHERE albums.id = musician_albums.album_id
      AND albums.musician = musicians.name
  )
  AND NOT EXISTS (
    SELECT 1
    FROM tracks
    WHERE tracks.album_id = musician_albums.album_id
      AND tracks.musician_id = musician_albums.musician_id
  )
  AND NOT EXISTS (
    SELECT 1
    FROM tracks
    INNER JOIN track_musicians
      ON track_musicians.track_id = tracks.id
    WHERE tracks.album_id = musician_albums.album_id
      AND track_musicians.musician_id = musician_albums.musician_id
  )
`

func (q *Queries) DeleteAlbumMusiciansWithoutTracks(ctx context.Context, albumID int64) error {
	_, err := q.exec(ctx, q.deleteAlbumMusiciansWithoutTracksStmt, deleteAlbumMusiciansWithoutTracks, albumID)
	return err
}

const getMusicianIDsByAlbumID = `-- name: GetMusicianIDsByAlbumID :many
SELECT musician_id FROM musician_albums WHERE album_id = ?
`

func (q *Queries) GetMusicianIDsByAlbumID(ctx context.Context, albumID int64) ([]int64, error) {
	rows, err := q.query(ctx, q.getMusicianIDsByAlbumIDStmt, getMusicianIDsByAlbumID, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var musician_id int64
		if err := rows.Scan(&musician_id); err != nil {
			return nil, err
		}
		items = append(items, musician_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
