// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: music_metadata_matches.sql

package database

import (
	"context"
	"database/sql"
)

const getMusicMetadataMatch = `-- name: GetMusicMetadataMatch :one
SELECT
  entity_type, entity_id, provider, external_id, status, reason, score, provider_score, threshold_value, candidate_name, candidate_artist, search_query, strategy, error, attempts, next_retry_at, updated_at
FROM music_metadata_matches
WHERE entity_type = ?
  AND entity_id = ?
  AND provider = ?
LIMIT 1
`

type GetMusicMetadataMatchParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
	Provider   string `json:"provider"`
}

func (q *Queries) GetMusicMetadataMatch(ctx context.Context, arg GetMusicMetadataMatchParams) (MusicMetadataMatch, error) {
	row := q.queryRow(ctx, q.getMusicMetadataMatchStmt, getMusicMetadataMatch, arg.EntityType, arg.EntityID, arg.Provider)
	var i MusicMetadataMatch
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.Provider,
		&i.ExternalID,
		&i.Status,
		&i.Reason,
		&i.Score,
		&i.ProviderScore,
		&i.ThresholdValue,
		&i.CandidateName,
		&i.CandidateArtist,
		&i.SearchQuery,
		&i.Strategy,
		&i.Error,
		&i.Attempts,
		&i.NextRetryAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMusicMetadataMatch = `-- name: UpsertMusicMetadataMatch :exec
INSERT INTO music_metadata_matches (
  entity_type,
  entity_id,
  provider,
  external_id,
  status,
  reason,
  score,
  provider_score,
  threshold_value,
  candidate_name,
  candidate_artist,
  search_query,
  strategy,
  error,
  next_retry_at,
  updated_at
)
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (entity_type, entity_id, provider) DO UPDATE
SET
  external_id = excluded.external_id,
  status = excluded.status,
  reason = excluded.reason,
  score = excluded.score,
  provider_score = excluded.provider_score,
  threshold_value = excluded.threshold_value,
  candidate_name = excluded.candidate_name,
  candidate_artist = excluded.candidate_artist,
  search_query = excluded.search_query,
  strategy = excluded.strategy,
  error = excluded.error,
  attempts = CASE
    WHEN excluded.status = 'failed' THEN music_metadata_matches.attempts + 1
    ELSE 1
  END,
  next_retry_at = excluded.next_retry_at,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertMusicMetadataMatchParams struct {
	EntityType      string         `json:"entity_type"`
	EntityID        int64          `json:"entity_id"`
	Provider        string         `json:"provider"`
	ExternalID      sql.NullString `json:"external_id"`
	Status          string         `json:"status"`
	Reason          sql.NullString `json:"reason"`
	Score           sql.NullInt64  `json:"score"`
	ProviderScore   sql.NullInt64  `json:"provider_score"`
	ThresholdValue  sql.NullInt64  `json:"threshold_value"`
	CandidateName   sql.NullString `json:"candidate_name"`
	CandidateArtist sql.NullString `json:"candidate_artist"`
	SearchQuery     sql.NullString `json:"search_query"`
	Strategy        sql.NullString `json:"strategy"`
	Error           sql.NullString `json:"error"`
	NextRetryAt     sql.NullString `json:"next_retry_at"`
}

// attempts counts consecutive failures for backoff: it grows while the status
// stays 'failed' and resets on any other outcome.
func (q *Queries) UpsertMusicMetadataMatch(ctx context.Context, arg UpsertMusicMetadataMatchParams) error {
	_, err := q.exec(ctx, q.upsertMusicMetadataMatchStmt, upsertMusicMetadataMatch,
		arg.EntityType,
		arg.EntityID,
		arg.Provider,
		arg.ExternalID,
		arg.Status,
		arg.Reason,
		arg.Score,
		arg.ProviderScore,
		arg.ThresholdValue,
		arg.CandidateName,
		arg.CandidateArtist,
		arg.SearchQuery,
		arg.Strategy,
		arg.Error,
		arg.NextRetryAt,
	)
	return err
}
