// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package database

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  created_by_user_id,
  user_id,
  title,
  message,
  is_admin
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, created_by_user_id, user_id, title, message, is_admin, created_at, updated_at
`

type CreateNotificationParams struct {
	CreatedByUserID int64         `json:"created_by_user_id"`
	UserID          sql.NullInt64 `json:"user_id"`
	Title           string        `json:"title"`
	Message         string        `json:"message"`
	IsAdmin         bool          `json:"is_admin"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.queryRow(ctx, q.createNotificationStmt, createNotification,
		arg.CreatedByUserID,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.IsAdmin,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
