// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package database

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  created_by_user_id,
  user_id,
  title,
  message,
  is_admin
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, created_by_user_id, user_id, title, message, is_admin, created_at, updated_at
`

type CreateNotificationParams struct {
	CreatedByUserID int64         `json:"created_by_user_id"`
	UserID          sql.NullInt64 `json:"user_id"`
	Title           string        `json:"title"`
	Message         string        `json:"message"`
	IsAdmin         bool          `json:"is_admin"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.queryRow(ctx, q.createNotificationStmt, createNotification,
		arg.CreatedByUserID,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.IsAdmin,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisibleNotification = `-- name: GetVisibleNotification :one
SELECT
  n.id,
  n.created_by_user_id,
  n.user_id,
  n.title,
  n.message,
  n.is_admin,
  n.created_at,
  n.updated_at,
  EXISTS (
    SELECT 1
    FROM notification_reads AS nr
    WHERE nr.notification_id = n.id
      AND nr.user_id = ?1
  ) AS is_read
FROM notifications AS n
WHERE n.id = ?2
  AND (
    n.user_id = ?1
    OR (n.user_id IS NULL AND n.is_admin = false)
    OR (n.is_admin = true AND n.is_admin = ?3)
  )
LIMIT 1
`

type GetVisibleNotificationParams struct {
	UserID  int64 `json:"user_id"`
	ID      int64 `json:"id"`
	IsAdmin bool  `json:"is_admin"`
}

type GetVisibleNotificationRow struct {
	ID              int64         `json:"id"`
	CreatedByUserID int64         `json:"created_by_user_id"`
	UserID          sql.NullInt64 `json:"user_id"`
	Title           string        `json:"title"`
	Message         string        `json:"message"`
	IsAdmin         bool          `json:"is_admin"`
	CreatedAt       string        `json:"created_at"`
	UpdatedAt       string        `json:"updated_at"`
	IsRead          bool          `json:"is_read"`
}

func (q *Queries) GetVisibleNotification(ctx context.Context, arg GetVisibleNotificationParams) (GetVisibleNotificationRow, error) {
	row := q.queryRow(ctx, q.getVisibleNotificationStmt, getVisibleNotification, arg.UserID, arg.ID, arg.IsAdmin)
	var i GetVisibleNotificationRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRead,
	)
	return i, err
}

const listVisibleNotifications = `-- name: ListVisibleNotifications :many
SELECT
  n.id,
  n.created_by_user_id,
  n.user_id,
  n.title,
  n.message,
  n.is_admin,
  n.created_at,
  n.updated_at,
  EXISTS (
    SELECT 1
    FROM notification_reads AS nr
    WHERE nr.notification_id = n.id
      AND nr.user_id = ?1
  ) AS is_read
FROM notifications AS n
WHERE
  n.user_id = ?1
  OR (n.user_id IS NULL AND n.is_admin = false)
  OR (n.is_admin = true AND n.is_admin = ?2)
ORDER BY n.created_at DESC, n.id DESC
LIMIT ?4 OFFSET ?3
`

type ListVisibleNotificationsParams struct {
	UserID  int64 `json:"user_id"`
	IsAdmin bool  `json:"is_admin"`
	Offset  int64 `json:"offset"`
	Limit   int64 `json:"limit"`
}

type ListVisibleNotificationsRow struct {
	ID              int64         `json:"id"`
	CreatedByUserID int64         `json:"created_by_user_id"`
	UserID          sql.NullInt64 `json:"user_id"`
	Title           string        `json:"title"`
	Message         string        `json:"message"`
	IsAdmin         bool          `json:"is_admin"`
	CreatedAt       string        `json:"created_at"`
	UpdatedAt       string        `json:"updated_at"`
	IsRead          bool          `json:"is_read"`
}

func (q *Queries) ListVisibleNotifications(ctx context.Context, arg ListVisibleNotificationsParams) ([]ListVisibleNotificationsRow, error) {
	rows, err := q.query(ctx, q.listVisibleNotificationsStmt, listVisibleNotifications,
		arg.UserID,
		arg.IsAdmin,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleNotificationsRow{}
	for rows.Next() {
		var i ListVisibleNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUserID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
INSERT INTO notification_reads (
  notification_id,
  user_id
)
SELECT
  n.id,
  ?1
FROM notifications AS n
WHERE n.id = ?2
  AND (
    n.user_id = ?1
    OR (n.user_id IS NULL AND n.is_admin = false)
    OR (n.is_admin = true AND n.is_admin = ?3)
  )
ON CONFLICT (notification_id, user_id) DO NOTHING
`

type MarkNotificationReadParams struct {
	UserID         int64 `json:"user_id"`
	NotificationID int64 `json:"notification_id"`
	IsAdmin        bool  `json:"is_admin"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.exec(ctx, q.markNotificationReadStmt, markNotificationRead, arg.UserID, arg.NotificationID, arg.IsAdmin)
	return err
}
