// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist_tracks.sql

package database

import (
	"context"
	"database/sql"
)

const addTrackToPlaylist = `-- name: AddTrackToPlaylist :execrows
INSERT INTO playlist_tracks (
  playlist_id,
  track_id,
  position,
  added_by
)
VALUES
  (
    ?1,
    ?2,
    (
      SELECT COALESCE(MAX(position), -1) + 1
      FROM playlist_tracks AS pt2
      WHERE pt2.playlist_id = ?1
    ),
    ?3
  )
ON CONFLICT (playlist_id, track_id) DO NOTHING
`

type AddTrackToPlaylistParams struct {
	PlaylistID int64         `json:"playlist_id"`
	TrackID    int64         `json:"track_id"`
	AddedBy    sql.NullInt64 `json:"added_by"`
}

// Zero rows affected means the track was already in the playlist; the unique
// constraint replaces a separate membership pre-check.
func (q *Queries) AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) (int64, error) {
	result, err := q.exec(ctx, q.addTrackToPlaylistStmt, addTrackToPlaylist, arg.PlaylistID, arg.TrackID, arg.AddedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPlaylistTracks = `-- name: CountPlaylistTracks :one
SELECT
  COUNT(*) AS count
FROM playlist_tracks
WHERE playlist_id = ?
`

func (q *Queries) CountPlaylistTracks(ctx context.Context, playlistID int64) (int64, error) {
	row := q.queryRow(ctx, q.countPlaylistTracksStmt, countPlaylistTracks, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlaylistTrackSummary = `-- name: GetPlaylistTrackSummary :one
SELECT
  COUNT(*) AS track_count,
  COALESCE(SUM(t.duration), 0) AS total_duration
FROM playlist_tracks AS pt
INNER JOIN tracks AS t
  ON pt.track_id = t.id
WHERE pt.playlist_id = ?
`

type GetPlaylistTrackSummaryRow struct {
	TrackCount    int64       `json:"track_count"`
	TotalDuration interface{} `json:"total_duration"`
}

// Count and total duration in one pass; the playlist detail response needs both.
func (q *Queries) GetPlaylistTrackSummary(ctx context.Context, playlistID int64) (GetPlaylistTrackSummaryRow, error) {
	row := q.queryRow(ctx, q.getPlaylistTrackSummaryStmt, getPlaylistTrackSummary, playlistID)
	var i GetPlaylistTrackSummaryRow
	err := row.Scan(&i.TrackCount, &i.TotalDuration)
	return i, err
}

const getPlaylistTracksInfinite = `-- name: GetPlaylistTracksInfinite :many
SELECT
  pt.id AS playlist_track_id,
  pt.position,
  pt.added_at,
  pt.added_by,
  t.id,
  t.title,
  t.duration,
  t.file_path,
  t.codec,
  t.bit_rate,
  t.album_id,
  t.musician_id,
  a.title AS album_title,
  a.cover AS album_cover,
  m.name AS musician_name
FROM playlist_tracks AS pt
INNER JOIN tracks AS t
  ON pt.track_id = t.id
LEFT JOIN albums AS a
  ON t.album_id = a.id
LEFT JOIN musicians AS m
  ON t.musician_id = m.id
WHERE pt.playlist_id = ?
ORDER BY pt.position ASC
LIMIT ?
OFFSET ?
`

type GetPlaylistTracksInfiniteParams struct {
	PlaylistID int64 `json:"playlist_id"`
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
}

type GetPlaylistTracksInfiniteRow struct {
	PlaylistTrackID int64          `json:"playlist_track_id"`
	Position        int64          `json:"position"`
	AddedAt         string         `json:"added_at"`
	AddedBy         sql.NullInt64  `json:"added_by"`
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Duration        int64          `json:"duration"`
	FilePath        string         `json:"file_path"`
	Codec           string         `json:"codec"`
	BitRate         int64          `json:"bit_rate"`
	AlbumID         sql.NullInt64  `json:"album_id"`
	MusicianID      sql.NullInt64  `json:"musician_id"`
	AlbumTitle      sql.NullString `json:"album_title"`
	AlbumCover      sql.NullString `json:"album_cover"`
	MusicianName    sql.NullString `json:"musician_name"`
}

func (q *Queries) GetPlaylistTracksInfinite(ctx context.Context, arg GetPlaylistTracksInfiniteParams) ([]GetPlaylistTracksInfiniteRow, error) {
	rows, err := q.query(ctx, q.getPlaylistTracksInfiniteStmt, getPlaylistTracksInfinite, arg.PlaylistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlaylistTracksInfiniteRow{}
	for rows.Next() {
		var i GetPlaylistTracksInfiniteRow
		if err := rows.Scan(
			&i.PlaylistTrackID,
			&i.Position,
			&i.AddedAt,
			&i.AddedBy,
			&i.ID,
			&i.Title,
			&i.Duration,
			&i.FilePath,
			&i.Codec,
			&i.BitRate,
			&i.AlbumID,
			&i.MusicianID,
			&i.AlbumTitle,
			&i.AlbumCover,
			&i.MusicianName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTrackFromPlaylist = `-- name: RemoveTrackFromPlaylist :exec
DELETE FROM playlist_tracks
WHERE playlist_id = ?
  AND track_id = ?
`

type RemoveTrackFromPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
}

func (q *Queries) RemoveTrackFromPlaylist(ctx context.Context, arg RemoveTrackFromPlaylistParams) error {
	_, err := q.exec(ctx, q.removeTrackFromPlaylistStmt, removeTrackFromPlaylist, arg.PlaylistID, arg.TrackID)
	return err
}

const updateTrackPosition = `-- name: UpdateTrackPosition :exec
UPDATE playlist_tracks
SET position = ?
WHERE playlist_id = ?
  AND track_id = ?
`

type UpdateTrackPositionParams struct {
	Position   int64 `json:"position"`
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
}

func (q *Queries) UpdateTrackPosition(ctx context.Context, arg UpdateTrackPositionParams) error {
	_, err := q.exec(ctx, q.updateTrackPositionStmt, updateTrackPosition, arg.Position, arg.PlaylistID, arg.TrackID)
	return err
}
