// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist_collaborators.sql

package database

import (
	"context"
)

const addCollaborator = `-- name: AddCollaborator :one
INSERT INTO playlist_collaborators (
  playlist_id,
  user_id,
  can_edit
)
VALUES
  (?, ?, ?)
RETURNING id, playlist_id, user_id, can_edit, created_at, updated_at
`

type AddCollaboratorParams struct {
	PlaylistID int64 `json:"playlist_id"`
	UserID     int64 `json:"user_id"`
	CanEdit    bool  `json:"can_edit"`
}

func (q *Queries) AddCollaborator(ctx context.Context, arg AddCollaboratorParams) (PlaylistCollaborator, error) {
	row := q.queryRow(ctx, q.addCollaboratorStmt, addCollaborator, arg.PlaylistID, arg.UserID, arg.CanEdit)
	var i PlaylistCollaborator
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.UserID,
		&i.CanEdit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistCollaborators = `-- name: GetPlaylistCollaborators :many
SELECT
  pc.id, pc.playlist_id, pc.user_id, pc.can_edit, pc.created_at, pc.updated_at,
  u.name AS username,
  u.email
FROM playlist_collaborators AS pc
INNER JOIN users AS u
  ON pc.user_id = u.id
WHERE pc.playlist_id = ?
ORDER BY pc.created_at ASC
`

type GetPlaylistCollaboratorsRow struct {
	ID         int64  `json:"id"`
	PlaylistID int64  `json:"playlist_id"`
	UserID     int64  `json:"user_id"`
	CanEdit    bool   `json:"can_edit"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
	Username   string `json:"username"`
	Email      string `json:"email"`
}

func (q *Queries) GetPlaylistCollaborators(ctx context.Context, playlistID int64) ([]GetPlaylistCollaboratorsRow, error) {
	rows, err := q.query(ctx, q.getPlaylistCollaboratorsStmt, getPlaylistCollaborators, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlaylistCollaboratorsRow{}
	for rows.Next() {
		var i GetPlaylistCollaboratorsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaylistID,
			&i.UserID,
			&i.CanEdit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollaborator = `-- name: RemoveCollaborator :exec
DELETE FROM playlist_collaborators
WHERE playlist_id = ?
  AND user_id = ?
`

type RemoveCollaboratorParams struct {
	PlaylistID int64 `json:"playlist_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) RemoveCollaborator(ctx context.Context, arg RemoveCollaboratorParams) error {
	_, err := q.exec(ctx, q.removeCollaboratorStmt, removeCollaborator, arg.PlaylistID, arg.UserID)
	return err
}
