// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlists.sql

package database

import (
	"context"
	"database/sql"
)

const createMoviePlaylist = `-- name: CreateMoviePlaylist :one
INSERT INTO playlists (
  user_id,
  name,
  description,
  cover_image,
  is_public,
  content_type,
  movie_id
)
VALUES
  (?, ?, ?, ?, ?, 'movie', ?)
RETURNING id, user_id, name, description, cover_image, is_public, folder_id, movie_id, content_type, created_at, updated_at
`

type CreateMoviePlaylistParams struct {
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CoverImage  sql.NullString `json:"cover_image"`
	IsPublic    bool           `json:"is_public"`
	MovieID     sql.NullInt64  `json:"movie_id"`
}

func (q *Queries) CreateMoviePlaylist(ctx context.Context, arg CreateMoviePlaylistParams) (Playlist, error) {
	row := q.queryRow(ctx, q.createMoviePlaylistStmt, createMoviePlaylist,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.CoverImage,
		arg.IsPublic,
		arg.MovieID,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CoverImage,
		&i.IsPublic,
		&i.FolderID,
		&i.MovieID,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (
  user_id,
  name,
  description,
  cover_image,
  is_public,
  content_type
)
VALUES
  (?, ?, ?, ?, ?, 'track')
RETURNING id, user_id, name, description, cover_image, is_public, folder_id, movie_id, content_type, created_at, updated_at
`

type CreatePlaylistParams struct {
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CoverImage  sql.NullString `json:"cover_image"`
	IsPublic    bool           `json:"is_public"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.queryRow(ctx, q.createPlaylistStmt, createPlaylist,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.CoverImage,
		arg.IsPublic,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CoverImage,
		&i.IsPublic,
		&i.FolderID,
		&i.MovieID,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists
WHERE id = ?
  AND user_id = ?
`

type DeletePlaylistParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error {
	_, err := q.exec(ctx, q.deletePlaylistStmt, deletePlaylist, arg.ID, arg.UserID)
	return err
}

const getMoviePlaylistsWithCollaboratorAccess = `-- name: GetMoviePlaylistsWithCollaboratorAccess :many
SELECT
  p.id,
  p.user_id,
  p.name,
  p.description,
  p.cover_image,
  p.is_public,
  p.folder_id,
  p.movie_id,
  p.content_type,
  p.created_at,
  p.updated_at,
  (
    SELECT COUNT(*)
    FROM playlist_movies AS pm
    WHERE pm.playlist_id = p.id
  ) AS movie_count
FROM playlists AS p
LEFT JOIN playlist_collaborators AS pc
  ON p.id = pc.playlist_id
WHERE (p.user_id = ? OR pc.user_id = ?)
  AND p.content_type = 'movie'
GROUP BY p.id
ORDER BY p.updated_at DESC
`

type GetMoviePlaylistsWithCollaboratorAccessParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

type GetMoviePlaylistsWithCollaboratorAccessRow struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CoverImage  sql.NullString `json:"cover_image"`
	IsPublic    bool           `json:"is_public"`
	FolderID    sql.NullInt64  `json:"folder_id"`
	MovieID     sql.NullInt64  `json:"movie_id"`
	ContentType string         `json:"content_type"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	MovieCount  int64          `json:"movie_count"`
}

func (q *Queries) GetMoviePlaylistsWithCollaboratorAccess(ctx context.Context, arg GetMoviePlaylistsWithCollaboratorAccessParams) ([]GetMoviePlaylistsWithCollaboratorAccessRow, error) {
	rows, err := q.query(ctx, q.getMoviePlaylistsWithCollaboratorAccessStmt, getMoviePlaylistsWithCollaboratorAccess, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMoviePlaylistsWithCollaboratorAccessRow{}
	for rows.Next() {
		var i GetMoviePlaylistsWithCollaboratorAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CoverImage,
			&i.IsPublic,
			&i.FolderID,
			&i.MovieID,
			&i.ContentType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MovieCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistById = `-- name: GetPlaylistById :one
SELECT
  id, user_id, name, description, cover_image, is_public, folder_id, movie_id, content_type, created_at, updated_at
FROM playlists
WHERE id = ?
`

func (q *Queries) GetPlaylistById(ctx context.Context, id int64) (Playlist, error) {
	row := q.queryRow(ctx, q.getPlaylistByIdStmt, getPlaylistById, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CoverImage,
		&i.IsPublic,
		&i.FolderID,
		&i.MovieID,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistsWithCollaboratorAccess = `-- name: GetPlaylistsWithCollaboratorAccess :many
SELECT
  p.id, p.user_id, p.name, p.description, p.cover_image, p.is_public, p.folder_id, p.movie_id, p.content_type, p.created_at, p.updated_at,
  (
    SELECT COUNT(*)
    FROM playlist_tracks AS pt
    WHERE pt.playlist_id = p.id
  ) AS track_count,
  (
    SELECT COALESCE(SUM(t.duration), 0)
    FROM playlist_tracks AS pt
    INNER JOIN tracks AS t
      ON pt.track_id = t.id
    WHERE pt.playlist_id = p.id
  ) AS total_duration
FROM playlists AS p
LEFT JOIN playlist_collaborators AS pc
  ON p.id = pc.playlist_id
WHERE (p.user_id = ? OR pc.user_id = ?)
  AND p.content_type = 'track'
GROUP BY p.id
ORDER BY p.updated_at DESC
`

type GetPlaylistsWithCollaboratorAccessParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

type GetPlaylistsWithCollaboratorAccessRow struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	CoverImage    sql.NullString `json:"cover_image"`
	IsPublic      bool           `json:"is_public"`
	FolderID      sql.NullInt64  `json:"folder_id"`
	MovieID       sql.NullInt64  `json:"movie_id"`
	ContentType   string         `json:"content_type"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
	TrackCount    int64          `json:"track_count"`
	TotalDuration interface{}    `json:"total_duration"`
}

func (q *Queries) GetPlaylistsWithCollaboratorAccess(ctx context.Context, arg GetPlaylistsWithCollaboratorAccessParams) ([]GetPlaylistsWithCollaboratorAccessRow, error) {
	rows, err := q.query(ctx, q.getPlaylistsWithCollaboratorAccessStmt, getPlaylistsWithCollaboratorAccess, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlaylistsWithCollaboratorAccessRow{}
	for rows.Next() {
		var i GetPlaylistsWithCollaboratorAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CoverImage,
			&i.IsPublic,
			&i.FolderID,
			&i.MovieID,
			&i.ContentType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrackCount,
			&i.TotalDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMoviePlaylist = `-- name: UpdateMoviePlaylist :one
UPDATE playlists
SET
  name = ?,
  description = ?,
  cover_image = ?,
  is_public = ?,
  movie_id = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND user_id = ?
  AND content_type = 'movie'
RETURNING id, user_id, name, description, cover_image, is_public, folder_id, movie_id, content_type, created_at, updated_at
`

type UpdateMoviePlaylistParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CoverImage  sql.NullString `json:"cover_image"`
	IsPublic    bool           `json:"is_public"`
	MovieID     sql.NullInt64  `json:"movie_id"`
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
}

func (q *Queries) UpdateMoviePlaylist(ctx context.Context, arg UpdateMoviePlaylistParams) (Playlist, error) {
	row := q.queryRow(ctx, q.updateMoviePlaylistStmt, updateMoviePlaylist,
		arg.Name,
		arg.Description,
		arg.CoverImage,
		arg.IsPublic,
		arg.MovieID,
		arg.ID,
		arg.UserID,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CoverImage,
		&i.IsPublic,
		&i.FolderID,
		&i.MovieID,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists
SET
  name = ?,
  description = ?,
  cover_image = ?,
  is_public = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, name, description, cover_image, is_public, folder_id, movie_id, content_type, created_at, updated_at
`

type UpdatePlaylistParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CoverImage  sql.NullString `json:"cover_image"`
	IsPublic    bool           `json:"is_public"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error) {
	row := q.queryRow(ctx, q.updatePlaylistStmt, updatePlaylist,
		arg.Name,
		arg.Description,
		arg.CoverImage,
		arg.IsPublic,
		arg.ID,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CoverImage,
		&i.IsPublic,
		&i.FolderID,
		&i.MovieID,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlaylistTimestamp = `-- name: UpdatePlaylistTimestamp :exec
UPDATE playlists
SET updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdatePlaylistTimestamp(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.updatePlaylistTimestampStmt, updatePlaylistTimestamp, id)
	return err
}
