// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddCollaborator(ctx context.Context, arg AddCollaboratorParams) (PlaylistCollaborator, error)
	// Zero rows affected means the movie was already in the playlist; the unique
	// constraint replaces a separate membership pre-check.
	AddMovieToPlaylist(ctx context.Context, arg AddMovieToPlaylistParams) (int64, error)
	// Zero rows affected means the track was already in the playlist; the unique
	// constraint replaces a separate membership pre-check.
	AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) (int64, error)
	AddWatchRoomMember(ctx context.Context, arg AddWatchRoomMemberParams) error
	AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountMoviesForGenre(ctx context.Context, genreID int64) (int64, error)
	CountPlaylistMovies(ctx context.Context, playlistID int64) (int64, error)
	CountPlaylistTracks(ctx context.Context, playlistID int64) (int64, error)
	CountUnreadNotificationsForUser(ctx context.Context, userID int64) (int64, error)
	CountUserLikedMovies(ctx context.Context, userID int64) (int64, error)
	CountUserLikedTracks(ctx context.Context, userID int64) (int64, error)
	CountUsersByIDs(ctx context.Context, ids []int64) (int64, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	// Link a movie to an extra video (trailer/special feature). Idempotent.
	CreateMovieExtraVideo(ctx context.Context, arg CreateMovieExtraVideoParams) error
	// Link movie to genre via junction table
	CreateMovieGenre(ctx context.Context, arg CreateMovieGenreParams) error
	CreateMoviePlaylist(ctx context.Context, arg CreateMoviePlaylistParams) (Playlist, error)
	// Link movie to production company via junction table
	CreateMovieProductionCompany(ctx context.Context, arg CreateMovieProductionCompanyParams) error
	CreateMusicianAlbum(ctx context.Context, arg CreateMusicianAlbumParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreateSettings(ctx context.Context, arg CreateSettingsParams) (Setting, error)
	CreateTrackGenre(ctx context.Context, arg CreateTrackGenreParams) error
	CreateTrackMusician(ctx context.Context, arg CreateTrackMusicianParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWatchRoom(ctx context.Context, arg CreateWatchRoomParams) (WatchRoom, error)
	DeleteAlbum(ctx context.Context, id int64) error
	DeleteDevice(ctx context.Context, id int64) error
	DeleteDeviceForUser(ctx context.Context, arg DeleteDeviceForUserParams) (int64, error)
	DeleteDevicesUnusedSince(ctx context.Context, cutoff string) (int64, error)
	// Delete a movie by ID. Related data is cascade-deleted via ON DELETE CASCADE.
	DeleteMovie(ctx context.Context, id int64) error
	// Delete all audio streams for a movie
	DeleteMovieAudioStreams(ctx context.Context, movieID int64) error
	// Remove all cast entries for a movie (used before re-identifying with TMDB).
	DeleteMovieCast(ctx context.Context, movieID int64) error
	// Delete all chapters for a movie
	DeleteMovieChapters(ctx context.Context, movieID int64) error
	// Remove all crew entries for a movie (used before re-identifying with TMDB).
	DeleteMovieCrew(ctx context.Context, movieID int64) error
	// Remove all extra-video links for a movie (e.g. before re-scanning).
	DeleteMovieExtraVideos(ctx context.Context, movieID int64) error
	// Remove all genre links for a movie
	DeleteMovieGenres(ctx context.Context, movieID int64) error
	// Remove all production company links for a movie
	DeleteMovieProductionCompanies(ctx context.Context, movieID int64) error
	// Delete all subtitles for a movie
	DeleteMovieSubtitles(ctx context.Context, movieID int64) error
	// Delete all video streams for a movie
	DeleteMovieVideoStreams(ctx context.Context, movieID int64) error
	DeleteMovieWatchProgress(ctx context.Context, arg DeleteMovieWatchProgressParams) error
	DeleteNotificationForUser(ctx context.Context, notificationID int64) (int64, error)
	DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error
	// Deletes all genre relationships for a track.
	DeleteTrackGenres(ctx context.Context, trackID int64) error
	// Deletes all genre relationships for a track except the specified genre.
	// Used to efficiently update genres: only removes stale relationships.
	DeleteTrackGenresExcept(ctx context.Context, arg DeleteTrackGenresExceptParams) error
	DeleteTrackMusicians(ctx context.Context, trackID int64) error
	DeleteTrackMusiciansExcept(ctx context.Context, arg DeleteTrackMusiciansExceptParams) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWatchRoom(ctx context.Context, id int64) error
	GetAdminUser(ctx context.Context) (User, error)
	GetAlbumByID(ctx context.Context, id int64) (Album, error)
	GetAlbumBySpotifyID(ctx context.Context, spotifyID sql.NullString) (Album, error)
	// The COALESCE must match idx_albums_title_musician and UpsertAlbum's conflict
	// target exactly, so a NULL-musician lookup finds a row written with '' and
	// vice versa.
	GetAlbumByTitleAndMusician(ctx context.Context, arg GetAlbumByTitleAndMusicianParams) (Album, error)
	// Returns all genres associated with an album
	GetAlbumGenres(ctx context.Context, albumID int64) ([]GetAlbumGenresRow, error)
	// Returns albums sorted alphabetically by title with pagination.
	// Non-alphabetic titles (numbers, symbols) are grouped under '#' and sorted first.
	GetAlbumsAlphabetical(ctx context.Context, arg GetAlbumsAlphabeticalParams) ([]GetAlbumsAlphabeticalRow, error)
	// Sorted by release date (newest first), then by title. Track counts come from
	// one grouped pass over idx_track_album instead of a correlated subquery per
	// album; this query has no LIMIT, so it runs for the artist's whole
	// discography.
	GetAlbumsByMusicianID(ctx context.Context, musicianID int64) ([]GetAlbumsByMusicianIDRow, error)
	GetAlbumsCount(ctx context.Context) (int64, error)
	// has_pin instead of the PIN itself: the admin listing only shows whether one
	// is set, so the values never leave the database.
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	// Audio streams for a movie (for technical details and playback settings).
	GetAudioStreamsByMovieID(ctx context.Context, movieID int64) ([]AudioStream, error)
	// Cast for a movie with artist name and profile (for details view).
	GetCastByMovieID(ctx context.Context, movieID int64) ([]GetCastByMovieIDRow, error)
	// Chapters for a movie (for technical details display).
	GetChaptersByMovieID(ctx context.Context, movieID int64) ([]Chapter, error)
	// The 30-second floor must match the web client's
	// MOVIE_WATCH_PROGRESS_MIN_SECONDS resume-eligibility floor.
	GetContinueWatchingMovies(ctx context.Context, userID int64) ([]GetContinueWatchingMoviesRow, error)
	// Crew for a movie with artist name and profile (for details view).
	GetCrewByMovieID(ctx context.Context, movieID int64) ([]GetCrewByMovieIDRow, error)
	GetDeviceByTokenHash(ctx context.Context, tokenHash string) (Device, error)
	GetDevicesByUser(ctx context.Context, userID int64) ([]GetDevicesByUserRow, error)
	GetGenresByAlbumID(ctx context.Context, albumID sql.NullInt64) ([]GetGenresByAlbumIDRow, error)
	// Genres linked to a movie (for details view).
	GetGenresByMovieID(ctx context.Context, movieID int64) ([]GetGenresByMovieIDRow, error)
	// Returns all genres associated with a musician
	GetGenresByMusicianID(ctx context.Context, musicianID int64) ([]GetGenresByMusicianIDRow, error)
	GetLatestAlbums(ctx context.Context) ([]GetLatestAlbumsRow, error)
	GetLatestMovies(ctx context.Context) ([]GetLatestMoviesRow, error)
	// id tie-breaker so LIMIT/OFFSET is stable when titles match.
	GetLikedMoviesForUserAsc(ctx context.Context, arg GetLikedMoviesForUserAscParams) ([]GetLikedMoviesForUserAscRow, error)
	// id tie-breaker so LIMIT/OFFSET is stable when titles match.
	GetLikedMoviesForUserDesc(ctx context.Context, arg GetLikedMoviesForUserDescParams) ([]GetLikedMoviesForUserDescRow, error)
	GetLikedTrackIDsByUserID(ctx context.Context, userID int64) ([]int64, error)
	GetLikedTracksForUser(ctx context.Context, arg GetLikedTracksForUserParams) ([]GetLikedTracksForUserRow, error)
	GetMovieByID(ctx context.Context, id int64) (Movie, error)
	GetMovieByTmdbID(ctx context.Context, tmdbID sql.NullInt64) (GetMovieByTmdbIDRow, error)
	// List all extra videos (trailers, special features) linked to a movie.
	GetMovieExtraVideos(ctx context.Context, movieID int64) ([]ExtraVideo, error)
	GetMovieForDirectStream(ctx context.Context, id int64) (GetMovieForDirectStreamRow, error)
	// Movie genres with counts per tag (genre_type movie only).
	GetMovieGenresWithCounts(ctx context.Context) ([]GetMovieGenresWithCountsRow, error)
	// The movie twin of GetPlaylistsWithCollaboratorAccess; see the notes there.
	GetMoviePlaylistsWithCollaboratorAccess(ctx context.Context, requestingUserID int64) ([]GetMoviePlaylistsWithCollaboratorAccessRow, error)
	GetMovieScanIndex(ctx context.Context) ([]GetMovieScanIndexRow, error)
	GetMovieWatchProgress(ctx context.Context, arg GetMovieWatchProgressParams) (MovieWatchProgress, error)
	GetMoviesByGenreAsc(ctx context.Context, arg GetMoviesByGenreAscParams) ([]GetMoviesByGenreAscRow, error)
	GetMoviesByGenreDesc(ctx context.Context, arg GetMoviesByGenreDescParams) ([]GetMoviesByGenreDescRow, error)
	// Card-sized projection: the watch-room listing only renders title and poster.
	GetMoviesByIDs(ctx context.Context, ids []int64) ([]GetMoviesByIDsRow, error)
	GetMoviesCount(ctx context.Context) (int64, error)
	// Paginated library A-Z (id tie-breaker so LIMIT/OFFSET is stable when titles match).
	GetMoviesLibraryAsc(ctx context.Context, arg GetMoviesLibraryAscParams) ([]GetMoviesLibraryAscRow, error)
	// Paginated library Z-A (id tie-breaker so LIMIT/OFFSET is stable when titles match).
	GetMoviesLibraryDesc(ctx context.Context, arg GetMoviesLibraryDescParams) ([]GetMoviesLibraryDescRow, error)
	// The music stats endpoint needs all three; one round trip instead of three.
	GetMusicLibraryCounts(ctx context.Context) (GetMusicLibraryCountsRow, error)
	GetMusicSpotifyMatch(ctx context.Context, arg GetMusicSpotifyMatchParams) (MusicSpotifyMatch, error)
	GetMusicianByID(ctx context.Context, id int64) (Musician, error)
	GetMusicianByName(ctx context.Context, name string) (Musician, error)
	GetMusicianBySpotifyID(ctx context.Context, spotifyID sql.NullString) (Musician, error)
	// Returns musicians sorted alphabetically by sort_name with pagination.
	// Non-alphabetic names (numbers, symbols) are grouped under '#' and sorted first.
	GetMusiciansAlphabetical(ctx context.Context, arg GetMusiciansAlphabeticalParams) ([]GetMusiciansAlphabeticalRow, error)
	GetMusiciansByAlbumID(ctx context.Context, albumID int64) ([]GetMusiciansByAlbumIDRow, error)
	GetMusiciansCount(ctx context.Context) (int64, error)
	GetOrCreateGenre(ctx context.Context, arg GetOrCreateGenreParams) (Genre, error)
	GetPlaylistCollaborators(ctx context.Context, playlistID int64) ([]GetPlaylistCollaboratorsRow, error)
	// Title order matches GET /api/movies/library sort=asc.
	GetPlaylistMoviesPaginatedAsc(ctx context.Context, arg GetPlaylistMoviesPaginatedAscParams) ([]GetPlaylistMoviesPaginatedAscRow, error)
	GetPlaylistMoviesPaginatedDesc(ctx context.Context, arg GetPlaylistMoviesPaginatedDescParams) ([]GetPlaylistMoviesPaginatedDescRow, error)
	// Count and total duration in one pass; the playlist detail response needs both.
	GetPlaylistTrackSummary(ctx context.Context, playlistID int64) (GetPlaylistTrackSummaryRow, error)
	GetPlaylistTracksInfinite(ctx context.Context, arg GetPlaylistTracksInfiniteParams) ([]GetPlaylistTracksInfiniteRow, error)
	// One seek for every playlist authorization decision: the playlist row by
	// primary key plus this user's collaborator row (if any) by the
	// (playlist_id, user_id) unique index. collaborator_can_edit is NULL when the
	// user is not a collaborator; the handler derives owner/edit/view from that
	// and p.user_id/p.is_public.
	GetPlaylistWithAccess(ctx context.Context, arg GetPlaylistWithAccessParams) (GetPlaylistWithAccessRow, error)
	// Playlists the user owns or collaborates on, newest-updated first. The two
	// access paths are separate indexed lookups (idx_playlist_user, then
	// idx_playlist_collaborators_user) glued with UNION ALL -- an OR would force a
	// scan of every user's playlists -- and they are disjoint because the
	// collaborator branch excludes playlists the user owns. Track count and total
	// duration come from one grouped pass over playlist_tracks instead of two
	// correlated subqueries per row.
	GetPlaylistsWithCollaboratorAccess(ctx context.Context, requestingUserID int64) ([]GetPlaylistsWithCollaboratorAccessRow, error)
	// Production companies linked to a movie (for details view).
	GetProductionCompaniesByMovieID(ctx context.Context, movieID int64) ([]GetProductionCompaniesByMovieIDRow, error)
	// The random pick happens over the bare tracks primary key, so the album and
	// musician joins run only for the chosen rows instead of the whole library.
	// The outer ORDER BY RANDOM() re-shuffles just those winners so playback order
	// stays random too.
	GetRandomTracks(ctx context.Context, limit int64) ([]GetRandomTracksRow, error)
	GetSettings(ctx context.Context) (Setting, error)
	// Subtitle tracks for a movie (for technical details display).
	GetSubtitlesByMovieID(ctx context.Context, movieID int64) ([]Subtitle, error)
	GetTrack(ctx context.Context, id int64) (Track, error)
	GetTracksAlphabetical(ctx context.Context, arg GetTracksAlphabeticalParams) ([]GetTracksAlphabeticalRow, error)
	GetTracksByAlbumID(ctx context.Context, albumID sql.NullInt64) ([]Track, error)
	// Same UNION-of-indexed-lookups shape as GetMusiciansAlphabetical's track_count:
	// the equivalent OR over tracks and track_musicians cannot use an index.
	GetTracksByMusicianID(ctx context.Context, musicianID sql.NullInt64) ([]GetTracksByMusicianIDRow, error)
	GetTracksCount(ctx context.Context) (int64, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Narrow admin check for hot paths (middleware, polled notification counts);
	// avoids shipping the full user row with its password hash.
	GetUserIsAdmin(ctx context.Context, id int64) (bool, error)
	// Returns overall listening statistics for a user
	GetUserListeningStats(ctx context.Context, userID int64) (GetUserListeningStatsRow, error)
	GetUserPin(ctx context.Context, id int64) (sql.NullString, error)
	GetUserPlaybackPreferences(ctx context.Context, id int64) (GetUserPlaybackPreferencesRow, error)
	// Returns the user's recently played tracks
	GetUserRecentlyPlayed(ctx context.Context, arg GetUserRecentlyPlayedParams) ([]GetUserRecentlyPlayedRow, error)
	// Returns the user's most listened albums
	GetUserTopAlbums(ctx context.Context, arg GetUserTopAlbumsParams) ([]GetUserTopAlbumsRow, error)
	// Returns the user's most listened genres
	GetUserTopGenres(ctx context.Context, arg GetUserTopGenresParams) ([]GetUserTopGenresRow, error)
	// Returns the user's most listened musicians by total play count
	GetUserTopMusicians(ctx context.Context, arg GetUserTopMusiciansParams) ([]GetUserTopMusiciansRow, error)
	// ============================================================================
	// USER STATISTICS QUERIES
	// ============================================================================
	// Returns the user's most played tracks
	GetUserTopTracks(ctx context.Context, arg GetUserTopTracksParams) ([]GetUserTopTracksRow, error)
	GetUsersExcluding(ctx context.Context, arg GetUsersExcludingParams) ([]GetUsersExcludingRow, error)
	// Video streams for a movie (for technical details display).
	GetVideoStreamsByMovieID(ctx context.Context, movieID int64) ([]VideoStream, error)
	GetWatchRoomByID(ctx context.Context, id int64) (WatchRoom, error)
	// The room row, but only when the user is a member: the auth check every
	// room media request (manifest, each segment, direct stream, websocket)
	// performs. One PK seek plus one (room_id, user_id) unique-index seek;
	// sql.ErrNoRows covers both "no such room" and "not a member", which callers
	// deliberately do not distinguish.
	GetWatchRoomForMember(ctx context.Context, arg GetWatchRoomForMemberParams) (WatchRoom, error)
	// GetWatchRoomForMember plus the requesting member's presence summary
	// (name, avatar), for the websocket upgrade only: it needs both and runs
	// once per socket. HTTP media requests keep the leaner GetWatchRoomForMember.
	GetWatchRoomForMemberWithSummary(ctx context.Context, arg GetWatchRoomForMemberWithSummaryParams) (GetWatchRoomForMemberWithSummaryRow, error)
	GetWatchRoomMembers(ctx context.Context, roomID int64) ([]GetWatchRoomMembersRow, error)
	GetWatchRoomMembersByRoomIDs(ctx context.Context, roomIds []int64) ([]GetWatchRoomMembersByRoomIDsRow, error)
	GetWatchRoomsForUser(ctx context.Context, userID int64) ([]WatchRoom, error)
	InsertAudioStream(ctx context.Context, arg InsertAudioStreamParams) (AudioStream, error)
	InsertChapter(ctx context.Context, arg InsertChapterParams) (Chapter, error)
	InsertSubtitle(ctx context.Context, arg InsertSubtitleParams) (Subtitle, error)
	InsertVideoStream(ctx context.Context, arg InsertVideoStreamParams) (VideoStream, error)
	IsMovieLiked(ctx context.Context, arg IsMovieLikedParams) (bool, error)
	IsWatchRoomMember(ctx context.Context, arg IsWatchRoomMemberParams) (bool, error)
	// Idempotent: duplicate (user_id, movie_id) is a no-op (no error).
	LikeMovie(ctx context.Context, arg LikeMovieParams) error
	LikeTrack(ctx context.Context, arg LikeTrackParams) error
	ListMusicTrackScanIndex(ctx context.Context) ([]ListMusicTrackScanIndexRow, error)
	// The shared admin request queue, newest first. Visibility is admin-only and
	// enforced by the handlers; user_id here only selects the viewer's read state
	// from notification_reads.
	ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]ListNotificationsForUserRow, error)
	MarkAllNotificationsReadForUser(ctx context.Context, userID int64) error
	MarkMovieUnwatched(ctx context.Context, arg MarkMovieUnwatchedParams) error
	MarkMovieWatched(ctx context.Context, arg MarkMovieWatchedParams) error
	MarkMovieWatchedFromProgress(ctx context.Context, arg MarkMovieWatchedFromProgressParams) error
	// Idempotent: marking an already-read or nonexistent notification is a no-op.
	MarkNotificationReadForUser(ctx context.Context, arg MarkNotificationReadForUserParams) error
	// Existence probe for handlers that only need to 404 on an unknown movie;
	// avoids shipping the full 27-column row.
	MovieExists(ctx context.Context, id int64) (bool, error)
	// ============================================================================
	// PLAY HISTORY RECORDING
	// ============================================================================
	// Records a new play event when a track is played
	RecordPlayEvent(ctx context.Context, arg RecordPlayEventParams) error
	RemoveCollaborator(ctx context.Context, arg RemoveCollaboratorParams) error
	RemoveMovieFromPlaylist(ctx context.Context, arg RemoveMovieFromPlaylistParams) error
	RemoveTrackFromPlaylist(ctx context.Context, arg RemoveTrackFromPlaylistParams) error
	RenameDevice(ctx context.Context, arg RenameDeviceParams) (int64, error)
	// Existence probe for handlers that only need to 404 on an unknown track.
	TrackExists(ctx context.Context, id int64) (bool, error)
	UnlikeMovie(ctx context.Context, arg UnlikeMovieParams) (int64, error)
	UnlikeTrack(ctx context.Context, arg UnlikeTrackParams) (int64, error)
	UpdateAlbumSpotifyCover(ctx context.Context, arg UpdateAlbumSpotifyCoverParams) (Album, error)
	UpdateDeviceLastUsed(ctx context.Context, id int64) error
	UpdateGeneralSettings(ctx context.Context, arg UpdateGeneralSettingsParams) (Setting, error)
	UpdateLibrarySettings(ctx context.Context, arg UpdateLibrarySettingsParams) (Setting, error)
	// Dedicated UPDATE for movie metadata (used by Edit feature).
	// Does NOT touch file-level fields (file_path, file_name, size, container, mime_type).
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
	UpdateMoviePlaylist(ctx context.Context, arg UpdateMoviePlaylistParams) (Playlist, error)
	UpdateMusicianSpotifyThumb(ctx context.Context, arg UpdateMusicianSpotifyThumbParams) (Musician, error)
	UpdatePlaybackServerSettings(ctx context.Context, arg UpdatePlaybackServerSettingsParams) (Setting, error)
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error)
	UpdatePlaylistTimestamp(ctx context.Context, id int64) error
	UpdateTrackPosition(ctx context.Context, arg UpdateTrackPositionParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPin(ctx context.Context, arg UpdateUserPinParams) (User, error)
	UpdateUserPlaybackPreferences(ctx context.Context, arg UpdateUserPlaybackPreferencesParams) (UpdateUserPlaybackPreferencesRow, error)
	// Matches idx_albums_title_musician, which treats a missing musician as '' so an
	// untagged album cannot be inserted twice.
	UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (Album, error)
	// Creates a relationship between an album and a genre (idempotent)
	UpsertAlbumGenre(ctx context.Context, arg UpsertAlbumGenreParams) error
	UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error)
	UpsertCast(ctx context.Context, arg UpsertCastParams) (Cast, error)
	UpsertCrew(ctx context.Context, arg UpsertCrewParams) (Crew, error)
	// Insert or update an extra video by external_id (e.g. TMDB video id). Use for trailers/special features.
	// Call with a non-null external_id so conflicts are detected; then link via CreateMovieExtraVideo.
	UpsertExtraVideo(ctx context.Context, arg UpsertExtraVideoParams) (ExtraVideo, error)
	UpsertMovie(ctx context.Context, arg UpsertMovieParams) (Movie, error)
	UpsertMovieWatchProgress(ctx context.Context, arg UpsertMovieWatchProgressParams) error
	UpsertMusicSpotifyMatch(ctx context.Context, arg UpsertMusicSpotifyMatchParams) error
	UpsertMusician(ctx context.Context, arg UpsertMusicianParams) (Musician, error)
	// Creates a relationship between a musician and a genre (idempotent)
	UpsertMusicianGenre(ctx context.Context, arg UpsertMusicianGenreParams) error
	UpsertProductionCompany(ctx context.Context, arg UpsertProductionCompanyParams) (ProductionCompany, error)
	UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error)
	// Updates aggregated stats when a play event is recorded
	UpsertUserTrackStats(ctx context.Context, arg UpsertUserTrackStatsParams) error
	UserExists(ctx context.Context, id int64) (bool, error)
}

var _ Querier = (*Queries)(nil)
