// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package database

import (
	"context"
	"database/sql"
)

const createSettings = `-- name: CreateSettings :one
INSERT INTO settings (
  tmdb_key,
  jellyfin_api_key,
  spotify_client_id,
  spotify_client_secret,
  hardware_acceleration_device,
  enable_logger,
  enable_watcher,
  download_images,
  movies_dir,
  shows_dir,
  music_dir,
  static_dir,
  logs_dir,
  transcode_dir
)
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, tmdb_key, immich_base_url, immich_api_key, jellyfin_base_url, jellyfin_api_key, spotify_client_id, spotify_client_secret, hardware_acceleration_device, enable_logger, enable_watcher, download_images, movies_dir, shows_dir, music_dir, server_upload_mbps, static_dir, logs_dir, transcode_dir, created_at, updated_at
`

type CreateSettingsParams struct {
	TmdbKey                    sql.NullString `json:"tmdb_key"`
	JellyfinApiKey             sql.NullString `json:"jellyfin_api_key"`
	SpotifyClientID            sql.NullString `json:"spotify_client_id"`
	SpotifyClientSecret        sql.NullString `json:"spotify_client_secret"`
	HardwareAccelerationDevice sql.NullString `json:"hardware_acceleration_device"`
	EnableLogger               bool           `json:"enable_logger"`
	EnableWatcher              bool           `json:"enable_watcher"`
	DownloadImages             bool           `json:"download_images"`
	MoviesDir                  sql.NullString `json:"movies_dir"`
	ShowsDir                   sql.NullString `json:"shows_dir"`
	MusicDir                   sql.NullString `json:"music_dir"`
	StaticDir                  string         `json:"static_dir"`
	LogsDir                    string         `json:"logs_dir"`
	TranscodeDir               string         `json:"transcode_dir"`
}

func (q *Queries) CreateSettings(ctx context.Context, arg CreateSettingsParams) (Setting, error) {
	row := q.queryRow(ctx, q.createSettingsStmt, createSettings,
		arg.TmdbKey,
		arg.JellyfinApiKey,
		arg.SpotifyClientID,
		arg.SpotifyClientSecret,
		arg.HardwareAccelerationDevice,
		arg.EnableLogger,
		arg.EnableWatcher,
		arg.DownloadImages,
		arg.MoviesDir,
		arg.ShowsDir,
		arg.MusicDir,
		arg.StaticDir,
		arg.LogsDir,
		arg.TranscodeDir,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TmdbKey,
		&i.ImmichBaseUrl,
		&i.ImmichApiKey,
		&i.JellyfinBaseUrl,
		&i.JellyfinApiKey,
		&i.SpotifyClientID,
		&i.SpotifyClientSecret,
		&i.HardwareAccelerationDevice,
		&i.EnableLogger,
		&i.EnableWatcher,
		&i.DownloadImages,
		&i.MoviesDir,
		&i.ShowsDir,
		&i.MusicDir,
		&i.ServerUploadMbps,
		&i.StaticDir,
		&i.LogsDir,
		&i.TranscodeDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT
  id, tmdb_key, immich_base_url, immich_api_key, jellyfin_base_url, jellyfin_api_key, spotify_client_id, spotify_client_secret, hardware_acceleration_device, enable_logger, enable_watcher, download_images, movies_dir, shows_dir, music_dir, server_upload_mbps, static_dir, logs_dir, transcode_dir, created_at, updated_at
FROM settings
ORDER BY id
LIMIT 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.queryRow(ctx, q.getSettingsStmt, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TmdbKey,
		&i.ImmichBaseUrl,
		&i.ImmichApiKey,
		&i.JellyfinBaseUrl,
		&i.JellyfinApiKey,
		&i.SpotifyClientID,
		&i.SpotifyClientSecret,
		&i.HardwareAccelerationDevice,
		&i.EnableLogger,
		&i.EnableWatcher,
		&i.DownloadImages,
		&i.MoviesDir,
		&i.ShowsDir,
		&i.MusicDir,
		&i.ServerUploadMbps,
		&i.StaticDir,
		&i.LogsDir,
		&i.TranscodeDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGeneralSettings = `-- name: UpdateGeneralSettings :one
UPDATE settings
SET
  tmdb_key = ?,
  immich_base_url = ?,
  immich_api_key = ?,
  jellyfin_base_url = ?,
  jellyfin_api_key = ?,
  spotify_client_id = ?,
  spotify_client_secret = ?,
  hardware_acceleration_device = ?,
  enable_logger = ?,
  enable_watcher = ?,
  download_images = ?,
  static_dir = ?,
  logs_dir = ?,
  transcode_dir = ?,
  server_upload_mbps = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = (
  SELECT id
  FROM settings
  ORDER BY id
  LIMIT 1
)
RETURNING id, tmdb_key, immich_base_url, immich_api_key, jellyfin_base_url, jellyfin_api_key, spotify_client_id, spotify_client_secret, hardware_acceleration_device, enable_logger, enable_watcher, download_images, movies_dir, shows_dir, music_dir, server_upload_mbps, static_dir, logs_dir, transcode_dir, created_at, updated_at
`

type UpdateGeneralSettingsParams struct {
	TmdbKey                    sql.NullString  `json:"tmdb_key"`
	ImmichBaseUrl              sql.NullString  `json:"immich_base_url"`
	ImmichApiKey               sql.NullString  `json:"immich_api_key"`
	JellyfinBaseUrl            sql.NullString  `json:"jellyfin_base_url"`
	JellyfinApiKey             sql.NullString  `json:"jellyfin_api_key"`
	SpotifyClientID            sql.NullString  `json:"spotify_client_id"`
	SpotifyClientSecret        sql.NullString  `json:"spotify_client_secret"`
	HardwareAccelerationDevice sql.NullString  `json:"hardware_acceleration_device"`
	EnableLogger               bool            `json:"enable_logger"`
	EnableWatcher              bool            `json:"enable_watcher"`
	DownloadImages             bool            `json:"download_images"`
	StaticDir                  string          `json:"static_dir"`
	LogsDir                    string          `json:"logs_dir"`
	TranscodeDir               string          `json:"transcode_dir"`
	ServerUploadMbps           sql.NullFloat64 `json:"server_upload_mbps"`
}

func (q *Queries) UpdateGeneralSettings(ctx context.Context, arg UpdateGeneralSettingsParams) (Setting, error) {
	row := q.queryRow(ctx, q.updateGeneralSettingsStmt, updateGeneralSettings,
		arg.TmdbKey,
		arg.ImmichBaseUrl,
		arg.ImmichApiKey,
		arg.JellyfinBaseUrl,
		arg.JellyfinApiKey,
		arg.SpotifyClientID,
		arg.SpotifyClientSecret,
		arg.HardwareAccelerationDevice,
		arg.EnableLogger,
		arg.EnableWatcher,
		arg.DownloadImages,
		arg.StaticDir,
		arg.LogsDir,
		arg.TranscodeDir,
		arg.ServerUploadMbps,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TmdbKey,
		&i.ImmichBaseUrl,
		&i.ImmichApiKey,
		&i.JellyfinBaseUrl,
		&i.JellyfinApiKey,
		&i.SpotifyClientID,
		&i.SpotifyClientSecret,
		&i.HardwareAccelerationDevice,
		&i.EnableLogger,
		&i.EnableWatcher,
		&i.DownloadImages,
		&i.MoviesDir,
		&i.ShowsDir,
		&i.MusicDir,
		&i.ServerUploadMbps,
		&i.StaticDir,
		&i.LogsDir,
		&i.TranscodeDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLibrarySettings = `-- name: UpdateLibrarySettings :one
UPDATE settings
SET
  movies_dir = ?,
  shows_dir = ?,
  music_dir = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = (
  SELECT id
  FROM settings
  ORDER BY id
  LIMIT 1
)
RETURNING id, tmdb_key, immich_base_url, immich_api_key, jellyfin_base_url, jellyfin_api_key, spotify_client_id, spotify_client_secret, hardware_acceleration_device, enable_logger, enable_watcher, download_images, movies_dir, shows_dir, music_dir, server_upload_mbps, static_dir, logs_dir, transcode_dir, created_at, updated_at
`

type UpdateLibrarySettingsParams struct {
	MoviesDir sql.NullString `json:"movies_dir"`
	ShowsDir  sql.NullString `json:"shows_dir"`
	MusicDir  sql.NullString `json:"music_dir"`
}

func (q *Queries) UpdateLibrarySettings(ctx context.Context, arg UpdateLibrarySettingsParams) (Setting, error) {
	row := q.queryRow(ctx, q.updateLibrarySettingsStmt, updateLibrarySettings, arg.MoviesDir, arg.ShowsDir, arg.MusicDir)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TmdbKey,
		&i.ImmichBaseUrl,
		&i.ImmichApiKey,
		&i.JellyfinBaseUrl,
		&i.JellyfinApiKey,
		&i.SpotifyClientID,
		&i.SpotifyClientSecret,
		&i.HardwareAccelerationDevice,
		&i.EnableLogger,
		&i.EnableWatcher,
		&i.DownloadImages,
		&i.MoviesDir,
		&i.ShowsDir,
		&i.MusicDir,
		&i.ServerUploadMbps,
		&i.StaticDir,
		&i.LogsDir,
		&i.TranscodeDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
