// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package database

import (
	"context"
	"database/sql"
)

const createSettings = `-- name: CreateSettings :one
INSERT INTO
  settings (
    tmdb_key,
    jellyfin_token,
    spotify_client_id,
    spotify_client_secret,
    hardware_acceleration_device,
    enable_logger,
    enable_watcher,
    download_images,
    movies_dir,
    shows_dir,
    music_dir,
    static_dir,
    logs_dir
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, tmdb_key, jellyfin_token, spotify_client_id, spotify_client_secret, hardware_acceleration_device, enable_logger, enable_watcher, download_images, movies_dir, shows_dir, music_dir, static_dir, logs_dir, created_at, updated_at
`

type CreateSettingsParams struct {
	TmdbKey                    sql.NullString `json:"tmdb_key"`
	JellyfinToken              sql.NullString `json:"jellyfin_token"`
	SpotifyClientID            sql.NullString `json:"spotify_client_id"`
	SpotifyClientSecret        sql.NullString `json:"spotify_client_secret"`
	HardwareAccelerationDevice sql.NullString `json:"hardware_acceleration_device"`
	EnableLogger               bool           `json:"enable_logger"`
	EnableWatcher              bool           `json:"enable_watcher"`
	DownloadImages             bool           `json:"download_images"`
	MoviesDir                  sql.NullString `json:"movies_dir"`
	ShowsDir                   sql.NullString `json:"shows_dir"`
	MusicDir                   sql.NullString `json:"music_dir"`
	StaticDir                  string         `json:"static_dir"`
	LogsDir                    string         `json:"logs_dir"`
}

func (q *Queries) CreateSettings(ctx context.Context, arg CreateSettingsParams) (Setting, error) {
	row := q.queryRow(ctx, q.createSettingsStmt, createSettings,
		arg.TmdbKey,
		arg.JellyfinToken,
		arg.SpotifyClientID,
		arg.SpotifyClientSecret,
		arg.HardwareAccelerationDevice,
		arg.EnableLogger,
		arg.EnableWatcher,
		arg.DownloadImages,
		arg.MoviesDir,
		arg.ShowsDir,
		arg.MusicDir,
		arg.StaticDir,
		arg.LogsDir,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TmdbKey,
		&i.JellyfinToken,
		&i.SpotifyClientID,
		&i.SpotifyClientSecret,
		&i.HardwareAccelerationDevice,
		&i.EnableLogger,
		&i.EnableWatcher,
		&i.DownloadImages,
		&i.MoviesDir,
		&i.ShowsDir,
		&i.MusicDir,
		&i.StaticDir,
		&i.LogsDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT
  id, tmdb_key, jellyfin_token, spotify_client_id, spotify_client_secret, hardware_acceleration_device, enable_logger, enable_watcher, download_images, movies_dir, shows_dir, music_dir, static_dir, logs_dir, created_at, updated_at
FROM
  settings
LIMIT
  1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.queryRow(ctx, q.getSettingsStmt, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TmdbKey,
		&i.JellyfinToken,
		&i.SpotifyClientID,
		&i.SpotifyClientSecret,
		&i.HardwareAccelerationDevice,
		&i.EnableLogger,
		&i.EnableWatcher,
		&i.DownloadImages,
		&i.MoviesDir,
		&i.ShowsDir,
		&i.MusicDir,
		&i.StaticDir,
		&i.LogsDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
