// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shows.sql

package database

import (
	"context"
	"database/sql"
)

const clearShowEpisodeRetry = `-- name: ClearShowEpisodeRetry :exec
DELETE FROM show_episode_tmdb_retries WHERE episode_id = ?
`

func (q *Queries) ClearShowEpisodeRetry(ctx context.Context, episodeID int64) error {
	_, err := q.exec(ctx, q.clearShowEpisodeRetryStmt, clearShowEpisodeRetry, episodeID)
	return err
}

const clearShowRetry = `-- name: ClearShowRetry :exec
DELETE FROM show_tmdb_retries WHERE show_id = ?
`

func (q *Queries) ClearShowRetry(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.clearShowRetryStmt, clearShowRetry, showID)
	return err
}

const clearShowSeasonRetry = `-- name: ClearShowSeasonRetry :exec
DELETE FROM show_season_tmdb_retries WHERE season_id = ?
`

func (q *Queries) ClearShowSeasonRetry(ctx context.Context, seasonID int64) error {
	_, err := q.exec(ctx, q.clearShowSeasonRetryStmt, clearShowSeasonRetry, seasonID)
	return err
}

const countShowRetries = `-- name: CountShowRetries :one
SELECT (SELECT COUNT(*) FROM show_tmdb_retries) + (SELECT COUNT(*) FROM show_season_tmdb_retries) + (SELECT COUNT(*) FROM show_episode_tmdb_retries)
`

func (q *Queries) CountShowRetries(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countShowRetriesStmt, countShowRetries)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createShowCast = `-- name: CreateShowCast :exec
INSERT INTO show_cast (show_id, artist_id, character, cast_order, credit_id, episode_count) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING
`

type CreateShowCastParams struct {
	ShowID       int64  `json:"show_id"`
	ArtistID     int64  `json:"artist_id"`
	Character    string `json:"character"`
	CastOrder    int64  `json:"cast_order"`
	CreditID     string `json:"credit_id"`
	EpisodeCount int64  `json:"episode_count"`
}

func (q *Queries) CreateShowCast(ctx context.Context, arg CreateShowCastParams) error {
	_, err := q.exec(ctx, q.createShowCastStmt, createShowCast,
		arg.ShowID,
		arg.ArtistID,
		arg.Character,
		arg.CastOrder,
		arg.CreditID,
		arg.EpisodeCount,
	)
	return err
}

const createShowCreator = `-- name: CreateShowCreator :exec
INSERT INTO show_creators (show_id, artist_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type CreateShowCreatorParams struct {
	ShowID   int64 `json:"show_id"`
	ArtistID int64 `json:"artist_id"`
}

func (q *Queries) CreateShowCreator(ctx context.Context, arg CreateShowCreatorParams) error {
	_, err := q.exec(ctx, q.createShowCreatorStmt, createShowCreator, arg.ShowID, arg.ArtistID)
	return err
}

const createShowCrew = `-- name: CreateShowCrew :exec
INSERT INTO show_crew (show_id, artist_id, department, job, credit_id, episode_count) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING
`

type CreateShowCrewParams struct {
	ShowID       int64  `json:"show_id"`
	ArtistID     int64  `json:"artist_id"`
	Department   string `json:"department"`
	Job          string `json:"job"`
	CreditID     string `json:"credit_id"`
	EpisodeCount int64  `json:"episode_count"`
}

func (q *Queries) CreateShowCrew(ctx context.Context, arg CreateShowCrewParams) error {
	_, err := q.exec(ctx, q.createShowCrewStmt, createShowCrew,
		arg.ShowID,
		arg.ArtistID,
		arg.Department,
		arg.Job,
		arg.CreditID,
		arg.EpisodeCount,
	)
	return err
}

const createShowEpisodeCrew = `-- name: CreateShowEpisodeCrew :exec
INSERT INTO show_episode_crew (episode_id, artist_id, department, job, credit_id, episode_count) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING
`

type CreateShowEpisodeCrewParams struct {
	EpisodeID    int64  `json:"episode_id"`
	ArtistID     int64  `json:"artist_id"`
	Department   string `json:"department"`
	Job          string `json:"job"`
	CreditID     string `json:"credit_id"`
	EpisodeCount int64  `json:"episode_count"`
}

func (q *Queries) CreateShowEpisodeCrew(ctx context.Context, arg CreateShowEpisodeCrewParams) error {
	_, err := q.exec(ctx, q.createShowEpisodeCrewStmt, createShowEpisodeCrew,
		arg.EpisodeID,
		arg.ArtistID,
		arg.Department,
		arg.Job,
		arg.CreditID,
		arg.EpisodeCount,
	)
	return err
}

const createShowEpisodeGuestCast = `-- name: CreateShowEpisodeGuestCast :exec
INSERT INTO show_episode_guest_cast (episode_id, artist_id, character, cast_order, credit_id, episode_count) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING
`

type CreateShowEpisodeGuestCastParams struct {
	EpisodeID    int64  `json:"episode_id"`
	ArtistID     int64  `json:"artist_id"`
	Character    string `json:"character"`
	CastOrder    int64  `json:"cast_order"`
	CreditID     string `json:"credit_id"`
	EpisodeCount int64  `json:"episode_count"`
}

func (q *Queries) CreateShowEpisodeGuestCast(ctx context.Context, arg CreateShowEpisodeGuestCastParams) error {
	_, err := q.exec(ctx, q.createShowEpisodeGuestCastStmt, createShowEpisodeGuestCast,
		arg.EpisodeID,
		arg.ArtistID,
		arg.Character,
		arg.CastOrder,
		arg.CreditID,
		arg.EpisodeCount,
	)
	return err
}

const createShowExtraVideo = `-- name: CreateShowExtraVideo :exec
INSERT INTO show_extra_videos (show_id, extra_video_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type CreateShowExtraVideoParams struct {
	ShowID       int64 `json:"show_id"`
	ExtraVideoID int64 `json:"extra_video_id"`
}

func (q *Queries) CreateShowExtraVideo(ctx context.Context, arg CreateShowExtraVideoParams) error {
	_, err := q.exec(ctx, q.createShowExtraVideoStmt, createShowExtraVideo, arg.ShowID, arg.ExtraVideoID)
	return err
}

const createShowGenre = `-- name: CreateShowGenre :exec
INSERT INTO show_genres (show_id, genre_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type CreateShowGenreParams struct {
	ShowID  int64 `json:"show_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) CreateShowGenre(ctx context.Context, arg CreateShowGenreParams) error {
	_, err := q.exec(ctx, q.createShowGenreStmt, createShowGenre, arg.ShowID, arg.GenreID)
	return err
}

const createShowNetwork = `-- name: CreateShowNetwork :exec
INSERT INTO show_networks (show_id, network_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type CreateShowNetworkParams struct {
	ShowID    int64 `json:"show_id"`
	NetworkID int64 `json:"network_id"`
}

func (q *Queries) CreateShowNetwork(ctx context.Context, arg CreateShowNetworkParams) error {
	_, err := q.exec(ctx, q.createShowNetworkStmt, createShowNetwork, arg.ShowID, arg.NetworkID)
	return err
}

const createShowProductionCompany = `-- name: CreateShowProductionCompany :exec
INSERT INTO show_production_companies (show_id, production_company_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type CreateShowProductionCompanyParams struct {
	ShowID              int64 `json:"show_id"`
	ProductionCompanyID int64 `json:"production_company_id"`
}

func (q *Queries) CreateShowProductionCompany(ctx context.Context, arg CreateShowProductionCompanyParams) error {
	_, err := q.exec(ctx, q.createShowProductionCompanyStmt, createShowProductionCompany, arg.ShowID, arg.ProductionCompanyID)
	return err
}

const createShowSeasonCast = `-- name: CreateShowSeasonCast :exec
INSERT INTO show_season_cast (season_id, artist_id, character, cast_order, credit_id, episode_count) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING
`

type CreateShowSeasonCastParams struct {
	SeasonID     int64  `json:"season_id"`
	ArtistID     int64  `json:"artist_id"`
	Character    string `json:"character"`
	CastOrder    int64  `json:"cast_order"`
	CreditID     string `json:"credit_id"`
	EpisodeCount int64  `json:"episode_count"`
}

func (q *Queries) CreateShowSeasonCast(ctx context.Context, arg CreateShowSeasonCastParams) error {
	_, err := q.exec(ctx, q.createShowSeasonCastStmt, createShowSeasonCast,
		arg.SeasonID,
		arg.ArtistID,
		arg.Character,
		arg.CastOrder,
		arg.CreditID,
		arg.EpisodeCount,
	)
	return err
}

const createShowSeasonCrew = `-- name: CreateShowSeasonCrew :exec
INSERT INTO show_season_crew (season_id, artist_id, department, job, credit_id, episode_count) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING
`

type CreateShowSeasonCrewParams struct {
	SeasonID     int64  `json:"season_id"`
	ArtistID     int64  `json:"artist_id"`
	Department   string `json:"department"`
	Job          string `json:"job"`
	CreditID     string `json:"credit_id"`
	EpisodeCount int64  `json:"episode_count"`
}

func (q *Queries) CreateShowSeasonCrew(ctx context.Context, arg CreateShowSeasonCrewParams) error {
	_, err := q.exec(ctx, q.createShowSeasonCrewStmt, createShowSeasonCrew,
		arg.SeasonID,
		arg.ArtistID,
		arg.Department,
		arg.Job,
		arg.CreditID,
		arg.EpisodeCount,
	)
	return err
}

const createShowSeasonExtraVideo = `-- name: CreateShowSeasonExtraVideo :exec
INSERT INTO show_season_extra_videos (season_id, extra_video_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type CreateShowSeasonExtraVideoParams struct {
	SeasonID     int64 `json:"season_id"`
	ExtraVideoID int64 `json:"extra_video_id"`
}

func (q *Queries) CreateShowSeasonExtraVideo(ctx context.Context, arg CreateShowSeasonExtraVideoParams) error {
	_, err := q.exec(ctx, q.createShowSeasonExtraVideoStmt, createShowSeasonExtraVideo, arg.SeasonID, arg.ExtraVideoID)
	return err
}

const deleteMissingShowFile = `-- name: DeleteMissingShowFile :one
DELETE FROM show_files WHERE id = ? AND file_path = ? RETURNING season_id
`

type DeleteMissingShowFileParams struct {
	ID       int64  `json:"id"`
	FilePath string `json:"file_path"`
}

func (q *Queries) DeleteMissingShowFile(ctx context.Context, arg DeleteMissingShowFileParams) (int64, error) {
	row := q.queryRow(ctx, q.deleteMissingShowFileStmt, deleteMissingShowFile, arg.ID, arg.FilePath)
	var season_id int64
	err := row.Scan(&season_id)
	return season_id, err
}

const deleteShowCast = `-- name: DeleteShowCast :exec
DELETE FROM show_cast WHERE show_id = ?
`

func (q *Queries) DeleteShowCast(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.deleteShowCastStmt, deleteShowCast, showID)
	return err
}

const deleteShowCreator = `-- name: DeleteShowCreator :exec
DELETE FROM show_creators WHERE show_id = ?
`

func (q *Queries) DeleteShowCreator(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.deleteShowCreatorStmt, deleteShowCreator, showID)
	return err
}

const deleteShowCrew = `-- name: DeleteShowCrew :exec
DELETE FROM show_crew WHERE show_id = ?
`

func (q *Queries) DeleteShowCrew(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.deleteShowCrewStmt, deleteShowCrew, showID)
	return err
}

const deleteShowEpisodeCrew = `-- name: DeleteShowEpisodeCrew :exec
DELETE FROM show_episode_crew WHERE episode_id = ?
`

func (q *Queries) DeleteShowEpisodeCrew(ctx context.Context, episodeID int64) error {
	_, err := q.exec(ctx, q.deleteShowEpisodeCrewStmt, deleteShowEpisodeCrew, episodeID)
	return err
}

const deleteShowEpisodeGuestCast = `-- name: DeleteShowEpisodeGuestCast :exec
DELETE FROM show_episode_guest_cast WHERE episode_id = ?
`

func (q *Queries) DeleteShowEpisodeGuestCast(ctx context.Context, episodeID int64) error {
	_, err := q.exec(ctx, q.deleteShowEpisodeGuestCastStmt, deleteShowEpisodeGuestCast, episodeID)
	return err
}

const deleteShowExtraVideo = `-- name: DeleteShowExtraVideo :exec
DELETE FROM show_extra_videos WHERE show_id = ?
`

func (q *Queries) DeleteShowExtraVideo(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.deleteShowExtraVideoStmt, deleteShowExtraVideo, showID)
	return err
}

const deleteShowFileAudioStreams = `-- name: DeleteShowFileAudioStreams :exec
DELETE FROM show_audio_streams
WHERE file_id = ?
`

func (q *Queries) DeleteShowFileAudioStreams(ctx context.Context, fileID int64) error {
	_, err := q.exec(ctx, q.deleteShowFileAudioStreamsStmt, deleteShowFileAudioStreams, fileID)
	return err
}

const deleteShowFileChapters = `-- name: DeleteShowFileChapters :exec
DELETE FROM show_chapters
WHERE file_id = ?
`

func (q *Queries) DeleteShowFileChapters(ctx context.Context, fileID int64) error {
	_, err := q.exec(ctx, q.deleteShowFileChaptersStmt, deleteShowFileChapters, fileID)
	return err
}

const deleteShowFileLinks = `-- name: DeleteShowFileLinks :exec
DELETE FROM show_episode_files WHERE file_id = ?
`

func (q *Queries) DeleteShowFileLinks(ctx context.Context, fileID int64) error {
	_, err := q.exec(ctx, q.deleteShowFileLinksStmt, deleteShowFileLinks, fileID)
	return err
}

const deleteShowFileSubtitles = `-- name: DeleteShowFileSubtitles :exec
DELETE FROM show_subtitles
WHERE file_id = ?
`

func (q *Queries) DeleteShowFileSubtitles(ctx context.Context, fileID int64) error {
	_, err := q.exec(ctx, q.deleteShowFileSubtitlesStmt, deleteShowFileSubtitles, fileID)
	return err
}

const deleteShowFileVideoStreams = `-- name: DeleteShowFileVideoStreams :exec
DELETE FROM show_video_streams
WHERE file_id = ?
`

func (q *Queries) DeleteShowFileVideoStreams(ctx context.Context, fileID int64) error {
	_, err := q.exec(ctx, q.deleteShowFileVideoStreamsStmt, deleteShowFileVideoStreams, fileID)
	return err
}

const deleteShowGenre = `-- name: DeleteShowGenre :exec
DELETE FROM show_genres WHERE show_id = ?
`

func (q *Queries) DeleteShowGenre(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.deleteShowGenreStmt, deleteShowGenre, showID)
	return err
}

const deleteShowNetwork = `-- name: DeleteShowNetwork :exec
DELETE FROM show_networks WHERE show_id = ?
`

func (q *Queries) DeleteShowNetwork(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.deleteShowNetworkStmt, deleteShowNetwork, showID)
	return err
}

const deleteShowProductionCompany = `-- name: DeleteShowProductionCompany :exec
DELETE FROM show_production_companies WHERE show_id = ?
`

func (q *Queries) DeleteShowProductionCompany(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.deleteShowProductionCompanyStmt, deleteShowProductionCompany, showID)
	return err
}

const deleteShowSeasonCast = `-- name: DeleteShowSeasonCast :exec
DELETE FROM show_season_cast WHERE season_id = ?
`

func (q *Queries) DeleteShowSeasonCast(ctx context.Context, seasonID int64) error {
	_, err := q.exec(ctx, q.deleteShowSeasonCastStmt, deleteShowSeasonCast, seasonID)
	return err
}

const deleteShowSeasonCrew = `-- name: DeleteShowSeasonCrew :exec
DELETE FROM show_season_crew WHERE season_id = ?
`

func (q *Queries) DeleteShowSeasonCrew(ctx context.Context, seasonID int64) error {
	_, err := q.exec(ctx, q.deleteShowSeasonCrewStmt, deleteShowSeasonCrew, seasonID)
	return err
}

const deleteShowSeasonExtraVideo = `-- name: DeleteShowSeasonExtraVideo :exec
DELETE FROM show_season_extra_videos WHERE season_id = ?
`

func (q *Queries) DeleteShowSeasonExtraVideo(ctx context.Context, seasonID int64) error {
	_, err := q.exec(ctx, q.deleteShowSeasonExtraVideoStmt, deleteShowSeasonExtraVideo, seasonID)
	return err
}

const getCastByShowID = `-- name: GetCastByShowID :many
SELECT
  sc.credit_id,
  sc.artist_id,
  sc.character,
  sc.cast_order,
  sc.episode_count,
  a.name AS artist_name,
  a.profile AS artist_profile
FROM show_cast AS sc
INNER JOIN artist AS a
  ON a.id = sc.artist_id
WHERE sc.show_id = ?
ORDER BY
  sc.cast_order,
  a.name
LIMIT 100
`

type GetCastByShowIDRow struct {
	CreditID      string         `json:"credit_id"`
	ArtistID      int64          `json:"artist_id"`
	Character     string         `json:"character"`
	CastOrder     int64          `json:"cast_order"`
	EpisodeCount  int64          `json:"episode_count"`
	ArtistName    string         `json:"artist_name"`
	ArtistProfile sql.NullString `json:"artist_profile"`
}

// Aggregate cast with artist name and profile. show_cast has no row id, so
// credit_id is the stable identity; TMDB can credit one artist with several
// roles, which is why the artist id alone will not do.
//
// Capped at 100 rows. TMDB aggregate credits for a long-running show reach into
// the thousands, while the details page bills a few dozen; the cap follows
// cast_order, so the billing TMDB considers most relevant is what survives it.
// The cap is part of the HTTP contract - see docs/openapi.json.
func (q *Queries) GetCastByShowID(ctx context.Context, showID int64) ([]GetCastByShowIDRow, error) {
	rows, err := q.query(ctx, q.getCastByShowIDStmt, getCastByShowID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCastByShowIDRow{}
	for rows.Next() {
		var i GetCastByShowIDRow
		if err := rows.Scan(
			&i.CreditID,
			&i.ArtistID,
			&i.Character,
			&i.CastOrder,
			&i.EpisodeCount,
			&i.ArtistName,
			&i.ArtistProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreatorsByShowID = `-- name: GetCreatorsByShowID :many
SELECT
  a.id,
  a.name,
  a.profile
FROM artist AS a
INNER JOIN show_creators AS sc
  ON sc.artist_id = a.id
WHERE sc.show_id = ?
ORDER BY a.name
`

type GetCreatorsByShowIDRow struct {
	ID      int64          `json:"id"`
	Name    string         `json:"name"`
	Profile sql.NullString `json:"profile"`
}

// Series creators, billed ahead of the aggregate crew on the details page.
func (q *Queries) GetCreatorsByShowID(ctx context.Context, showID int64) ([]GetCreatorsByShowIDRow, error) {
	rows, err := q.query(ctx, q.getCreatorsByShowIDStmt, getCreatorsByShowID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCreatorsByShowIDRow{}
	for rows.Next() {
		var i GetCreatorsByShowIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Profile); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCrewByShowID = `-- name: GetCrewByShowID :many
SELECT
  sc.credit_id,
  sc.artist_id,
  sc.department,
  sc.job,
  sc.episode_count,
  a.name AS artist_name,
  a.profile AS artist_profile
FROM show_crew AS sc
INNER JOIN artist AS a
  ON a.id = sc.artist_id
WHERE sc.show_id = ?
ORDER BY
  sc.department,
  sc.job,
  a.name
LIMIT 100
`

type GetCrewByShowIDRow struct {
	CreditID      string         `json:"credit_id"`
	ArtistID      int64          `json:"artist_id"`
	Department    string         `json:"department"`
	Job           string         `json:"job"`
	EpisodeCount  int64          `json:"episode_count"`
	ArtistName    string         `json:"artist_name"`
	ArtistProfile sql.NullString `json:"artist_profile"`
}

// Aggregate crew with artist name. credit_id is the stable identity, as in
// GetCastByShowID, and the same 100-row cap applies for the same reason.
func (q *Queries) GetCrewByShowID(ctx context.Context, showID int64) ([]GetCrewByShowIDRow, error) {
	rows, err := q.query(ctx, q.getCrewByShowIDStmt, getCrewByShowID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCrewByShowIDRow{}
	for rows.Next() {
		var i GetCrewByShowIDRow
		if err := rows.Scan(
			&i.CreditID,
			&i.ArtistID,
			&i.Department,
			&i.Job,
			&i.EpisodeCount,
			&i.ArtistName,
			&i.ArtistProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenresByShowID = `-- name: GetGenresByShowID :many
SELECT
  g.id,
  g.tag
FROM genres AS g
INNER JOIN show_genres AS sg
  ON sg.genre_id = g.id
WHERE sg.show_id = ?
ORDER BY g.tag
`

type GetGenresByShowIDRow struct {
	ID  int64  `json:"id"`
	Tag string `json:"tag"`
}

// Genres linked to a show (for details view).
func (q *Queries) GetGenresByShowID(ctx context.Context, showID int64) ([]GetGenresByShowIDRow, error) {
	rows, err := q.query(ctx, q.getGenresByShowIDStmt, getGenresByShowID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGenresByShowIDRow{}
	for rows.Next() {
		var i GetGenresByShowIDRow
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestShows = `-- name: GetLatestShows :many
SELECT id, name, poster_path, premiere_year FROM shows ORDER BY created_at DESC, id DESC LIMIT 12
`

type GetLatestShowsRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	PosterPath   sql.NullString `json:"poster_path"`
	PremiereYear sql.NullInt64  `json:"premiere_year"`
}

// created_at is written once by UpsertLocalShow, so it orders by first discovery.
// CURRENT_TIMESTAMP only has second resolution, so id breaks the ties a bulk scan creates.
func (q *Queries) GetLatestShows(ctx context.Context) ([]GetLatestShowsRow, error) {
	rows, err := q.query(ctx, q.getLatestShowsStmt, getLatestShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLatestShowsRow{}
	for rows.Next() {
		var i GetLatestShowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PosterPath,
			&i.PremiereYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNetworksByShowID = `-- name: GetNetworksByShowID :many
SELECT
  n.id,
  n.name,
  n.logo,
  n.country
FROM networks AS n
INNER JOIN show_networks AS sn
  ON sn.network_id = n.id
WHERE sn.show_id = ?
ORDER BY n.name
`

type GetNetworksByShowIDRow struct {
	ID      int64          `json:"id"`
	Name    string         `json:"name"`
	Logo    sql.NullString `json:"logo"`
	Country sql.NullString `json:"country"`
}

// Networks linked to a show, with the logo and country the About section
// renders. The only query in the project that reads networks.
func (q *Queries) GetNetworksByShowID(ctx context.Context, showID int64) ([]GetNetworksByShowIDRow, error) {
	rows, err := q.query(ctx, q.getNetworksByShowIDStmt, getNetworksByShowID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNetworksByShowIDRow{}
	for rows.Next() {
		var i GetNetworksByShowIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Logo,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingShows = `-- name: GetPendingShows :many
SELECT s.id, s.directory_path, s.local_name, s.premiere_year, s.name, s.tmdb_id, s.imdb_id, s.original_name, s.overview, s.tagline, s.language, s.origin_countries, s.first_air_date, s.last_air_date, s.status, s.type, s.adult, s.poster_path, s.backdrop_path, s.homepage, s.vote_average, s.vote_count, s.popularity, s.certification, s.tmdb_season_count, s.tmdb_episode_count, s.created_at, s.updated_at FROM shows s WHERE s.id > ?1 AND (
 EXISTS (SELECT 1 FROM show_tmdb_retries r WHERE r.show_id = s.id) OR
 EXISTS (SELECT 1 FROM show_seasons se JOIN show_season_tmdb_retries r ON r.season_id = se.id WHERE se.show_id = s.id) OR
 EXISTS (SELECT 1 FROM show_seasons se JOIN show_episodes e ON e.season_id = se.id JOIN show_episode_tmdb_retries r ON r.episode_id = e.id WHERE se.show_id = s.id))
 ORDER BY s.id LIMIT 100
`

func (q *Queries) GetPendingShows(ctx context.Context, afterID int64) ([]Show, error) {
	rows, err := q.query(ctx, q.getPendingShowsStmt, getPendingShows, afterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Show{}
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.DirectoryPath,
			&i.LocalName,
			&i.PremiereYear,
			&i.Name,
			&i.TmdbID,
			&i.ImdbID,
			&i.OriginalName,
			&i.Overview,
			&i.Tagline,
			&i.Language,
			&i.OriginCountries,
			&i.FirstAirDate,
			&i.LastAirDate,
			&i.Status,
			&i.Type,
			&i.Adult,
			&i.PosterPath,
			&i.BackdropPath,
			&i.Homepage,
			&i.VoteAverage,
			&i.VoteCount,
			&i.Popularity,
			&i.Certification,
			&i.TmdbSeasonCount,
			&i.TmdbEpisodeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionCompaniesByShowID = `-- name: GetProductionCompaniesByShowID :many
SELECT
  pc.id,
  pc.name
FROM production_companies AS pc
INNER JOIN show_production_companies AS spc
  ON spc.production_company_id = pc.id
WHERE spc.show_id = ?
ORDER BY pc.name
`

type GetProductionCompaniesByShowIDRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Production companies linked to a show (for details view).
func (q *Queries) GetProductionCompaniesByShowID(ctx context.Context, showID int64) ([]GetProductionCompaniesByShowIDRow, error) {
	rows, err := q.query(ctx, q.getProductionCompaniesByShowIDStmt, getProductionCompaniesByShowID, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductionCompaniesByShowIDRow{}
	for rows.Next() {
		var i GetProductionCompaniesByShowIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShow = `-- name: GetShow :one
SELECT id, directory_path, local_name, premiere_year, name, tmdb_id, imdb_id, original_name, overview, tagline, language, origin_countries, first_air_date, last_air_date, status, type, adult, poster_path, backdrop_path, homepage, vote_average, vote_count, popularity, certification, tmdb_season_count, tmdb_episode_count, created_at, updated_at FROM shows WHERE id = ?
`

func (q *Queries) GetShow(ctx context.Context, id int64) (Show, error) {
	row := q.queryRow(ctx, q.getShowStmt, getShow, id)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.DirectoryPath,
		&i.LocalName,
		&i.PremiereYear,
		&i.Name,
		&i.TmdbID,
		&i.ImdbID,
		&i.OriginalName,
		&i.Overview,
		&i.Tagline,
		&i.Language,
		&i.OriginCountries,
		&i.FirstAirDate,
		&i.LastAirDate,
		&i.Status,
		&i.Type,
		&i.Adult,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Homepage,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Popularity,
		&i.Certification,
		&i.TmdbSeasonCount,
		&i.TmdbEpisodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShowAudioStreamsByFileID = `-- name: GetShowAudioStreamsByFileID :many
SELECT
  id,
  file_id,
  stream_index,
  codec,
  codec_profile,
  bit_rate,
  sample_rate,
  channels,
  channel_layout,
  language,
  title,
  is_default
FROM show_audio_streams
WHERE file_id = ?
ORDER BY stream_index
`

type GetShowAudioStreamsByFileIDRow struct {
	ID            int64          `json:"id"`
	FileID        int64          `json:"file_id"`
	StreamIndex   int64          `json:"stream_index"`
	Codec         string         `json:"codec"`
	CodecProfile  sql.NullString `json:"codec_profile"`
	BitRate       int64          `json:"bit_rate"`
	SampleRate    sql.NullInt64  `json:"sample_rate"`
	Channels      int64          `json:"channels"`
	ChannelLayout sql.NullString `json:"channel_layout"`
	Language      sql.NullString `json:"language"`
	Title         sql.NullString `json:"title"`
	IsDefault     bool           `json:"is_default"`
}

func (q *Queries) GetShowAudioStreamsByFileID(ctx context.Context, fileID int64) ([]GetShowAudioStreamsByFileIDRow, error) {
	rows, err := q.query(ctx, q.getShowAudioStreamsByFileIDStmt, getShowAudioStreamsByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowAudioStreamsByFileIDRow{}
	for rows.Next() {
		var i GetShowAudioStreamsByFileIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.StreamIndex,
			&i.Codec,
			&i.CodecProfile,
			&i.BitRate,
			&i.SampleRate,
			&i.Channels,
			&i.ChannelLayout,
			&i.Language,
			&i.Title,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowChaptersByFileID = `-- name: GetShowChaptersByFileID :many
SELECT
  id,
  title,
  start_time,
  thumb,
  file_id
FROM show_chapters
WHERE file_id = ?
ORDER BY start_time
`

func (q *Queries) GetShowChaptersByFileID(ctx context.Context, fileID int64) ([]ShowChapter, error) {
	rows, err := q.query(ctx, q.getShowChaptersByFileIDStmt, getShowChaptersByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShowChapter{}
	for rows.Next() {
		var i ShowChapter
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartTime,
			&i.Thumb,
			&i.FileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowDetails = `-- name: GetShowDetails :one

SELECT
  id,
  name,
  original_name,
  premiere_year,
  tmdb_id,
  overview,
  tagline,
  language,
  origin_countries,
  first_air_date,
  last_air_date,
  status,
  type,
  poster_path,
  backdrop_path,
  vote_average,
  vote_count,
  certification,
  tmdb_season_count,
  tmdb_episode_count
FROM shows
WHERE id = ?
LIMIT 1
`

type GetShowDetailsRow struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	OriginalName     sql.NullString  `json:"original_name"`
	PremiereYear     sql.NullInt64   `json:"premiere_year"`
	TmdbID           sql.NullInt64   `json:"tmdb_id"`
	Overview         sql.NullString  `json:"overview"`
	Tagline          sql.NullString  `json:"tagline"`
	Language         sql.NullString  `json:"language"`
	OriginCountries  sql.NullString  `json:"origin_countries"`
	FirstAirDate     sql.NullString  `json:"first_air_date"`
	LastAirDate      sql.NullString  `json:"last_air_date"`
	Status           sql.NullString  `json:"status"`
	Type             sql.NullString  `json:"type"`
	PosterPath       sql.NullString  `json:"poster_path"`
	BackdropPath     sql.NullString  `json:"backdrop_path"`
	VoteAverage      sql.NullFloat64 `json:"vote_average"`
	VoteCount        sql.NullInt64   `json:"vote_count"`
	Certification    sql.NullString  `json:"certification"`
	TmdbSeasonCount  sql.NullInt64   `json:"tmdb_season_count"`
	TmdbEpisodeCount sql.NullInt64   `json:"tmdb_episode_count"`
}

// ============================================================================
// Show details page reads.
//
// The queries below build the show details payload. Like GetLatestShows above,
// they are explicit projections that never expose directory_path or local_name,
// and they address a season by its number rather than by an internal row id;
// the rest of the queries above serve the scanner.
// ============================================================================
// Show header for the details page. Omits the filesystem columns and the
// fields the page does not render (adult, imdb_id, homepage, popularity,
// timestamps).
func (q *Queries) GetShowDetails(ctx context.Context, id int64) (GetShowDetailsRow, error) {
	row := q.queryRow(ctx, q.getShowDetailsStmt, getShowDetails, id)
	var i GetShowDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginalName,
		&i.PremiereYear,
		&i.TmdbID,
		&i.Overview,
		&i.Tagline,
		&i.Language,
		&i.OriginCountries,
		&i.FirstAirDate,
		&i.LastAirDate,
		&i.Status,
		&i.Type,
		&i.PosterPath,
		&i.BackdropPath,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Certification,
		&i.TmdbSeasonCount,
		&i.TmdbEpisodeCount,
	)
	return i, err
}

const getShowEpisode = `-- name: GetShowEpisode :one
SELECT id, season_id, episode_number, name, tmdb_id, overview, air_date, still_path, production_code, tmdb_runtime, vote_average, vote_count, created_at, updated_at FROM show_episodes WHERE id = ?
`

func (q *Queries) GetShowEpisode(ctx context.Context, id int64) (ShowEpisode, error) {
	row := q.queryRow(ctx, q.getShowEpisodeStmt, getShowEpisode, id)
	var i ShowEpisode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.EpisodeNumber,
		&i.Name,
		&i.TmdbID,
		&i.Overview,
		&i.AirDate,
		&i.StillPath,
		&i.ProductionCode,
		&i.TmdbRuntime,
		&i.VoteAverage,
		&i.VoteCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShowEpisodeForDirectStream = `-- name: GetShowEpisodeForDirectStream :one
SELECT
  f.file_path,
  f.file_name,
  f.container,
  f.mime_type
FROM show_episode_files AS l
INNER JOIN show_files AS f
  ON f.id = l.file_id
WHERE l.episode_id = ?
ORDER BY f.id
LIMIT 1
`

type GetShowEpisodeForDirectStreamRow struct {
	FilePath  string `json:"file_path"`
	FileName  string `json:"file_name"`
	Container string `json:"container"`
	MimeType  string `json:"mime_type"`
}

// Direct-stream twin of GetMovieForDirectStream, resolved through the same
// lowest-file-id rule as GetShowFileForEpisode.
func (q *Queries) GetShowEpisodeForDirectStream(ctx context.Context, episodeID int64) (GetShowEpisodeForDirectStreamRow, error) {
	row := q.queryRow(ctx, q.getShowEpisodeForDirectStreamStmt, getShowEpisodeForDirectStream, episodeID)
	var i GetShowEpisodeForDirectStreamRow
	err := row.Scan(
		&i.FilePath,
		&i.FileName,
		&i.Container,
		&i.MimeType,
	)
	return i, err
}

const getShowEpisodePlaybackDetails = `-- name: GetShowEpisodePlaybackDetails :one
SELECT
  e.id,
  e.episode_number,
  e.name,
  e.overview,
  e.air_date,
  e.still_path,
  e.tmdb_runtime,
  e.vote_average,
  e.vote_count,
  s.season_number,
  s.name AS season_name,
  sh.id AS show_id,
  sh.name AS show_name,
  sh.poster_path AS show_poster_path,
  sh.backdrop_path AS show_backdrop_path
FROM show_episodes AS e
INNER JOIN show_seasons AS s
  ON s.id = e.season_id
INNER JOIN shows AS sh
  ON sh.id = s.show_id
WHERE e.id = ?
LIMIT 1
`

type GetShowEpisodePlaybackDetailsRow struct {
	ID               int64           `json:"id"`
	EpisodeNumber    int64           `json:"episode_number"`
	Name             string          `json:"name"`
	Overview         sql.NullString  `json:"overview"`
	AirDate          sql.NullString  `json:"air_date"`
	StillPath        sql.NullString  `json:"still_path"`
	TmdbRuntime      sql.NullInt64   `json:"tmdb_runtime"`
	VoteAverage      sql.NullFloat64 `json:"vote_average"`
	VoteCount        sql.NullInt64   `json:"vote_count"`
	SeasonNumber     int64           `json:"season_number"`
	SeasonName       string          `json:"season_name"`
	ShowID           int64           `json:"show_id"`
	ShowName         string          `json:"show_name"`
	ShowPosterPath   sql.NullString  `json:"show_poster_path"`
	ShowBackdropPath sql.NullString  `json:"show_backdrop_path"`
}

// Player header for one episode: the episode row plus the season number and
// show identity the page titles itself with and navigates back to.
func (q *Queries) GetShowEpisodePlaybackDetails(ctx context.Context, id int64) (GetShowEpisodePlaybackDetailsRow, error) {
	row := q.queryRow(ctx, q.getShowEpisodePlaybackDetailsStmt, getShowEpisodePlaybackDetails, id)
	var i GetShowEpisodePlaybackDetailsRow
	err := row.Scan(
		&i.ID,
		&i.EpisodeNumber,
		&i.Name,
		&i.Overview,
		&i.AirDate,
		&i.StillPath,
		&i.TmdbRuntime,
		&i.VoteAverage,
		&i.VoteCount,
		&i.SeasonNumber,
		&i.SeasonName,
		&i.ShowID,
		&i.ShowName,
		&i.ShowPosterPath,
		&i.ShowBackdropPath,
	)
	return i, err
}

const getShowEpisodes = `-- name: GetShowEpisodes :many
SELECT id, season_id, episode_number, name, tmdb_id, overview, air_date, still_path, production_code, tmdb_runtime, vote_average, vote_count, created_at, updated_at FROM show_episodes WHERE season_id = ? ORDER BY episode_number
`

func (q *Queries) GetShowEpisodes(ctx context.Context, seasonID int64) ([]ShowEpisode, error) {
	rows, err := q.query(ctx, q.getShowEpisodesStmt, getShowEpisodes, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShowEpisode{}
	for rows.Next() {
		var i ShowEpisode
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.EpisodeNumber,
			&i.Name,
			&i.TmdbID,
			&i.Overview,
			&i.AirDate,
			&i.StillPath,
			&i.ProductionCode,
			&i.TmdbRuntime,
			&i.VoteAverage,
			&i.VoteCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowEpisodesBySeasonNumber = `-- name: GetShowEpisodesBySeasonNumber :many
SELECT
  e.id,
  e.episode_number,
  e.name,
  e.overview,
  e.air_date,
  e.still_path,
  e.tmdb_runtime,
  e.vote_average,
  e.vote_count,
  wp.progress_sec,
  wp.duration_sec,
  CAST((wp.watched IS NOT NULL AND wp.watched) AS BOOLEAN) AS watched
FROM show_episodes AS e
INNER JOIN show_seasons AS s
  ON s.id = e.season_id
LEFT JOIN show_episode_watch_progress AS wp
  ON wp.episode_id = e.id
  AND wp.user_id = ?1
WHERE s.show_id = ?2
  AND s.season_number = ?3
ORDER BY e.episode_number
`

type GetShowEpisodesBySeasonNumberParams struct {
	UserID       int64 `json:"user_id"`
	ShowID       int64 `json:"show_id"`
	SeasonNumber int64 `json:"season_number"`
}

type GetShowEpisodesBySeasonNumberRow struct {
	ID            int64           `json:"id"`
	EpisodeNumber int64           `json:"episode_number"`
	Name          string          `json:"name"`
	Overview      sql.NullString  `json:"overview"`
	AirDate       sql.NullString  `json:"air_date"`
	StillPath     sql.NullString  `json:"still_path"`
	TmdbRuntime   sql.NullInt64   `json:"tmdb_runtime"`
	VoteAverage   sql.NullFloat64 `json:"vote_average"`
	VoteCount     sql.NullInt64   `json:"vote_count"`
	ProgressSec   sql.NullFloat64 `json:"progress_sec"`
	DurationSec   sql.NullFloat64 `json:"duration_sec"`
	Watched       bool            `json:"watched"`
}

// Episodes of one season, addressed by (show_id, season_number) so the route
// never exposes an internal season id. Carries no file, stream, codec, or
// chapter data: those belong to a physical file, and one file can back several
// episodes. The requesting user's watch progress rides along so the episode
// list can show resume and watched state without a query per row; the CAST
// keeps sqlc typing `watched` as a plain bool across the LEFT JOIN.
func (q *Queries) GetShowEpisodesBySeasonNumber(ctx context.Context, arg GetShowEpisodesBySeasonNumberParams) ([]GetShowEpisodesBySeasonNumberRow, error) {
	rows, err := q.query(ctx, q.getShowEpisodesBySeasonNumberStmt, getShowEpisodesBySeasonNumber, arg.UserID, arg.ShowID, arg.SeasonNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowEpisodesBySeasonNumberRow{}
	for rows.Next() {
		var i GetShowEpisodesBySeasonNumberRow
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeNumber,
			&i.Name,
			&i.Overview,
			&i.AirDate,
			&i.StillPath,
			&i.TmdbRuntime,
			&i.VoteAverage,
			&i.VoteCount,
			&i.ProgressSec,
			&i.DurationSec,
			&i.Watched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowExtraVideos = `-- name: GetShowExtraVideos :many
SELECT
  ev.id,
  ev.title,
  ev.key,
  ev.type,
  ev.site
FROM extra_videos AS ev
INNER JOIN show_extra_videos AS sev
  ON sev.extra_video_id = ev.id
WHERE sev.show_id = ?
ORDER BY
  ev.type,
  ev.title
`

type GetShowExtraVideosRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Key   string `json:"key"`
	Type  string `json:"type"`
	Site  string `json:"site"`
}

// List all extra videos (trailers, special features) linked to a show.
func (q *Queries) GetShowExtraVideos(ctx context.Context, showID int64) ([]GetShowExtraVideosRow, error) {
	rows, err := q.query(ctx, q.getShowExtraVideosStmt, getShowExtraVideos, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowExtraVideosRow{}
	for rows.Next() {
		var i GetShowExtraVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Key,
			&i.Type,
			&i.Site,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowFileByPath = `-- name: GetShowFileByPath :one
SELECT id, season_id, file_path, file_name, size, container, mime_type, duration, created_at, updated_at FROM show_files WHERE file_path = ?
`

func (q *Queries) GetShowFileByPath(ctx context.Context, filePath string) (ShowFile, error) {
	row := q.queryRow(ctx, q.getShowFileByPathStmt, getShowFileByPath, filePath)
	var i ShowFile
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.FilePath,
		&i.FileName,
		&i.Size,
		&i.Container,
		&i.MimeType,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShowFileEpisodeIDs = `-- name: GetShowFileEpisodeIDs :many
SELECT episode_id
FROM show_episode_files
WHERE file_id = ?
ORDER BY episode_order
`

// Episodes linked to a file, read before a deletion cascades the links away so
// the per-episode runtime caches can be evicted after commit.
func (q *Queries) GetShowFileEpisodeIDs(ctx context.Context, fileID int64) ([]int64, error) {
	rows, err := q.query(ctx, q.getShowFileEpisodeIDsStmt, getShowFileEpisodeIDs, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var episode_id int64
		if err := rows.Scan(&episode_id); err != nil {
			return nil, err
		}
		items = append(items, episode_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowFileForEpisode = `-- name: GetShowFileForEpisode :one
SELECT
  f.id,
  f.season_id,
  f.file_path,
  f.file_name,
  f.size,
  f.container,
  f.mime_type,
  f.duration,
  f.updated_at
FROM show_episode_files AS l
INNER JOIN show_files AS f
  ON f.id = l.file_id
WHERE l.episode_id = ?
ORDER BY f.id
LIMIT 1
`

type GetShowFileForEpisodeRow struct {
	ID        int64           `json:"id"`
	SeasonID  int64           `json:"season_id"`
	FilePath  string          `json:"file_path"`
	FileName  string          `json:"file_name"`
	Size      int64           `json:"size"`
	Container string          `json:"container"`
	MimeType  string          `json:"mime_type"`
	Duration  sql.NullFloat64 `json:"duration"`
	UpdatedAt string          `json:"updated_at"`
}

// The physical file behind an episode. An episode may be linked to more than
// one file (duplicate copies), so the lowest file id is the deterministic
// playback target; a combined file is returned whole, playback never seeks to
// a guessed episode offset.
func (q *Queries) GetShowFileForEpisode(ctx context.Context, episodeID int64) (GetShowFileForEpisodeRow, error) {
	row := q.queryRow(ctx, q.getShowFileForEpisodeStmt, getShowFileForEpisode, episodeID)
	var i GetShowFileForEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.FilePath,
		&i.FileName,
		&i.Size,
		&i.Container,
		&i.MimeType,
		&i.Duration,
		&i.UpdatedAt,
	)
	return i, err
}

const getShowNextEpisode = `-- name: GetShowNextEpisode :one
SELECT
  n.id,
  ns.season_number,
  n.episode_number,
  n.name,
  n.still_path,
  wp.progress_sec,
  wp.duration_sec,
  CAST((wp.watched IS NOT NULL AND wp.watched) AS BOOLEAN) AS watched
FROM show_episodes AS c
INNER JOIN show_seasons AS cs
  ON cs.id = c.season_id
INNER JOIN show_seasons AS ns
  ON ns.show_id = cs.show_id
INNER JOIN show_episodes AS n
  ON n.season_id = ns.id
LEFT JOIN show_episode_watch_progress AS wp
  ON wp.episode_id = n.id
  AND wp.user_id = ?1
WHERE c.id = ?2
  AND (
    (ns.season_number = 0) > (cs.season_number = 0)
    OR (
      (ns.season_number = 0) = (cs.season_number = 0)
      AND (
        ns.season_number > cs.season_number
        OR (
          ns.season_number = cs.season_number
          AND n.episode_number > c.episode_number
        )
      )
    )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM show_episode_files AS nl
    WHERE nl.episode_id = n.id
      AND nl.file_id = (
        SELECT MIN(cl.file_id)
        FROM show_episode_files AS cl
        WHERE cl.episode_id = c.id
      )
  )
ORDER BY
  ns.season_number = 0,
  ns.season_number,
  n.episode_number
LIMIT 1
`

type GetShowNextEpisodeParams struct {
	UserID    int64 `json:"user_id"`
	EpisodeID int64 `json:"episode_id"`
}

type GetShowNextEpisodeRow struct {
	ID            int64           `json:"id"`
	SeasonNumber  int64           `json:"season_number"`
	EpisodeNumber int64           `json:"episode_number"`
	Name          string          `json:"name"`
	StillPath     sql.NullString  `json:"still_path"`
	ProgressSec   sql.NullFloat64 `json:"progress_sec"`
	DurationSec   sql.NullFloat64 `json:"duration_sec"`
	Watched       bool            `json:"watched"`
}

// The episode the player advances to when one ends: the first episode of the
// same show that sorts after the current one in the order the season listing
// uses (specials last, then season, then episode number). Episodes backed by
// the file that just played are skipped, because a combined file plays whole
// and its other episodes have already been seen. The requesting user's
// progress rides along so the player can resume the next episode where it
// was left.
func (q *Queries) GetShowNextEpisode(ctx context.Context, arg GetShowNextEpisodeParams) (GetShowNextEpisodeRow, error) {
	row := q.queryRow(ctx, q.getShowNextEpisodeStmt, getShowNextEpisode, arg.UserID, arg.EpisodeID)
	var i GetShowNextEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.SeasonNumber,
		&i.EpisodeNumber,
		&i.Name,
		&i.StillPath,
		&i.ProgressSec,
		&i.DurationSec,
		&i.Watched,
	)
	return i, err
}

const getShowPendingEpisodeIDs = `-- name: GetShowPendingEpisodeIDs :many
SELECT r.episode_id FROM show_episode_tmdb_retries r JOIN show_episodes e ON e.id = r.episode_id JOIN show_seasons se ON se.id = e.season_id WHERE se.show_id = ?
`

func (q *Queries) GetShowPendingEpisodeIDs(ctx context.Context, showID int64) ([]int64, error) {
	rows, err := q.query(ctx, q.getShowPendingEpisodeIDsStmt, getShowPendingEpisodeIDs, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var episode_id int64
		if err := rows.Scan(&episode_id); err != nil {
			return nil, err
		}
		items = append(items, episode_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowPendingSeasonIDs = `-- name: GetShowPendingSeasonIDs :many
SELECT r.season_id FROM show_season_tmdb_retries r JOIN show_seasons se ON se.id = r.season_id WHERE se.show_id = ?
`

func (q *Queries) GetShowPendingSeasonIDs(ctx context.Context, showID int64) ([]int64, error) {
	rows, err := q.query(ctx, q.getShowPendingSeasonIDsStmt, getShowPendingSeasonIDs, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var season_id int64
		if err := rows.Scan(&season_id); err != nil {
			return nil, err
		}
		items = append(items, season_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowRetry = `-- name: GetShowRetry :one
SELECT attempts, last_attempt_at FROM show_tmdb_retries WHERE show_id = ?
`

type GetShowRetryRow struct {
	Attempts      int64         `json:"attempts"`
	LastAttemptAt sql.NullInt64 `json:"last_attempt_at"`
}

func (q *Queries) GetShowRetry(ctx context.Context, showID int64) (GetShowRetryRow, error) {
	row := q.queryRow(ctx, q.getShowRetryStmt, getShowRetry, showID)
	var i GetShowRetryRow
	err := row.Scan(&i.Attempts, &i.LastAttemptAt)
	return i, err
}

const getShowScanEpisodeLinks = `-- name: GetShowScanEpisodeLinks :many
SELECT file_id, episode_id FROM show_episode_files ORDER BY file_id, episode_order
`

type GetShowScanEpisodeLinksRow struct {
	FileID    int64 `json:"file_id"`
	EpisodeID int64 `json:"episode_id"`
}

func (q *Queries) GetShowScanEpisodeLinks(ctx context.Context) ([]GetShowScanEpisodeLinksRow, error) {
	rows, err := q.query(ctx, q.getShowScanEpisodeLinksStmt, getShowScanEpisodeLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowScanEpisodeLinksRow{}
	for rows.Next() {
		var i GetShowScanEpisodeLinksRow
		if err := rows.Scan(&i.FileID, &i.EpisodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowScanIndex = `-- name: GetShowScanIndex :many
SELECT f.id, f.season_id, f.file_path, f.file_name, f.size, f.container, f.mime_type, f.duration, f.created_at, f.updated_at, fp.mtime_ns, fp.ctime_ns, fp.device, fp.inode FROM show_files f LEFT JOIN show_file_fingerprints fp ON fp.file_id = f.id
`

type GetShowScanIndexRow struct {
	ID        int64           `json:"id"`
	SeasonID  int64           `json:"season_id"`
	FilePath  string          `json:"file_path"`
	FileName  string          `json:"file_name"`
	Size      int64           `json:"size"`
	Container string          `json:"container"`
	MimeType  string          `json:"mime_type"`
	Duration  sql.NullFloat64 `json:"duration"`
	CreatedAt string          `json:"created_at"`
	UpdatedAt string          `json:"updated_at"`
	MtimeNs   sql.NullInt64   `json:"mtime_ns"`
	CtimeNs   sql.NullInt64   `json:"ctime_ns"`
	Device    sql.NullString  `json:"device"`
	Inode     sql.NullString  `json:"inode"`
}

func (q *Queries) GetShowScanIndex(ctx context.Context) ([]GetShowScanIndexRow, error) {
	rows, err := q.query(ctx, q.getShowScanIndexStmt, getShowScanIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowScanIndexRow{}
	for rows.Next() {
		var i GetShowScanIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.FilePath,
			&i.FileName,
			&i.Size,
			&i.Container,
			&i.MimeType,
			&i.Duration,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MtimeNs,
			&i.CtimeNs,
			&i.Device,
			&i.Inode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowSeason = `-- name: GetShowSeason :one
SELECT id, show_id, season_number, name, tmdb_id, overview, air_date, poster_path, vote_average, tmdb_episode_count, created_at, updated_at FROM show_seasons WHERE id = ?
`

func (q *Queries) GetShowSeason(ctx context.Context, id int64) (ShowSeason, error) {
	row := q.queryRow(ctx, q.getShowSeasonStmt, getShowSeason, id)
	var i ShowSeason
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.SeasonNumber,
		&i.Name,
		&i.TmdbID,
		&i.Overview,
		&i.AirDate,
		&i.PosterPath,
		&i.VoteAverage,
		&i.TmdbEpisodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShowSeasonSummaries = `-- name: GetShowSeasonSummaries :many
SELECT
  s.id,
  s.season_number,
  s.name,
  s.overview,
  s.air_date,
  s.poster_path,
  s.tmdb_episode_count,
  COUNT(e.id) AS available_episode_count
FROM show_seasons AS s
LEFT JOIN show_episodes AS e
  ON e.season_id = s.id
WHERE s.show_id = ?
GROUP BY s.id
ORDER BY
  s.season_number = 0,
  s.season_number
`

type GetShowSeasonSummariesRow struct {
	ID                    int64          `json:"id"`
	SeasonNumber          int64          `json:"season_number"`
	Name                  string         `json:"name"`
	Overview              sql.NullString `json:"overview"`
	AirDate               sql.NullString `json:"air_date"`
	PosterPath            sql.NullString `json:"poster_path"`
	TmdbEpisodeCount      sql.NullInt64  `json:"tmdb_episode_count"`
	AvailableEpisodeCount int64          `json:"available_episode_count"`
}

// Seasons with the count of episodes actually present. Pruning deletes episodes
// that lost their last file, so a stored episode always has one and the stored
// count is the available count; TMDB's tmdb_episode_count rides alongside it so
// the page can state how much of a season is here. Specials (season 0) sort
// last rather than first.
func (q *Queries) GetShowSeasonSummaries(ctx context.Context, showID int64) ([]GetShowSeasonSummariesRow, error) {
	rows, err := q.query(ctx, q.getShowSeasonSummariesStmt, getShowSeasonSummaries, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowSeasonSummariesRow{}
	for rows.Next() {
		var i GetShowSeasonSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonNumber,
			&i.Name,
			&i.Overview,
			&i.AirDate,
			&i.PosterPath,
			&i.TmdbEpisodeCount,
			&i.AvailableEpisodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowSeasonSummaryByNumber = `-- name: GetShowSeasonSummaryByNumber :one
SELECT
  s.id,
  s.season_number,
  s.name,
  s.overview,
  s.air_date,
  s.poster_path,
  s.tmdb_episode_count,
  COUNT(e.id) AS available_episode_count
FROM show_seasons AS s
LEFT JOIN show_episodes AS e
  ON e.season_id = s.id
WHERE s.show_id = ?
  AND s.season_number = ?
GROUP BY s.id
`

type GetShowSeasonSummaryByNumberParams struct {
	ShowID       int64 `json:"show_id"`
	SeasonNumber int64 `json:"season_number"`
}

type GetShowSeasonSummaryByNumberRow struct {
	ID                    int64          `json:"id"`
	SeasonNumber          int64          `json:"season_number"`
	Name                  string         `json:"name"`
	Overview              sql.NullString `json:"overview"`
	AirDate               sql.NullString `json:"air_date"`
	PosterPath            sql.NullString `json:"poster_path"`
	TmdbEpisodeCount      sql.NullInt64  `json:"tmdb_episode_count"`
	AvailableEpisodeCount int64          `json:"available_episode_count"`
}

// The GetShowSeasonSummaries aggregate for one season, addressed by number.
func (q *Queries) GetShowSeasonSummaryByNumber(ctx context.Context, arg GetShowSeasonSummaryByNumberParams) (GetShowSeasonSummaryByNumberRow, error) {
	row := q.queryRow(ctx, q.getShowSeasonSummaryByNumberStmt, getShowSeasonSummaryByNumber, arg.ShowID, arg.SeasonNumber)
	var i GetShowSeasonSummaryByNumberRow
	err := row.Scan(
		&i.ID,
		&i.SeasonNumber,
		&i.Name,
		&i.Overview,
		&i.AirDate,
		&i.PosterPath,
		&i.TmdbEpisodeCount,
		&i.AvailableEpisodeCount,
	)
	return i, err
}

const getShowSeasons = `-- name: GetShowSeasons :many
SELECT id, show_id, season_number, name, tmdb_id, overview, air_date, poster_path, vote_average, tmdb_episode_count, created_at, updated_at FROM show_seasons WHERE show_id = ? ORDER BY season_number
`

func (q *Queries) GetShowSeasons(ctx context.Context, showID int64) ([]ShowSeason, error) {
	rows, err := q.query(ctx, q.getShowSeasonsStmt, getShowSeasons, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShowSeason{}
	for rows.Next() {
		var i ShowSeason
		if err := rows.Scan(
			&i.ID,
			&i.ShowID,
			&i.SeasonNumber,
			&i.Name,
			&i.TmdbID,
			&i.Overview,
			&i.AirDate,
			&i.PosterPath,
			&i.VoteAverage,
			&i.TmdbEpisodeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowSubtitlesByFileID = `-- name: GetShowSubtitlesByFileID :many
SELECT
  id,
  file_id,
  stream_index,
  codec,
  language,
  title,
  is_forced,
  is_default
FROM show_subtitles
WHERE file_id = ?
ORDER BY stream_index
`

type GetShowSubtitlesByFileIDRow struct {
	ID          int64          `json:"id"`
	FileID      int64          `json:"file_id"`
	StreamIndex int64          `json:"stream_index"`
	Codec       string         `json:"codec"`
	Language    sql.NullString `json:"language"`
	Title       sql.NullString `json:"title"`
	IsForced    bool           `json:"is_forced"`
	IsDefault   bool           `json:"is_default"`
}

func (q *Queries) GetShowSubtitlesByFileID(ctx context.Context, fileID int64) ([]GetShowSubtitlesByFileIDRow, error) {
	rows, err := q.query(ctx, q.getShowSubtitlesByFileIDStmt, getShowSubtitlesByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowSubtitlesByFileIDRow{}
	for rows.Next() {
		var i GetShowSubtitlesByFileIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.StreamIndex,
			&i.Codec,
			&i.Language,
			&i.Title,
			&i.IsForced,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShowVideoStreamsByFileID = `-- name: GetShowVideoStreamsByFileID :many
SELECT
  id,
  file_id,
  stream_index,
  codec,
  codec_profile,
  codec_level,
  bit_rate,
  width,
  height,
  coded_width,
  coded_height,
  aspect_ratio,
  frame_rate,
  avg_frame_rate,
  bit_depth,
  pixel_format,
  color_range,
  color_space,
  color_primaries,
  color_transfer,
  field_order,
  rotation,
  language,
  title
FROM show_video_streams
WHERE file_id = ?
ORDER BY stream_index
`

type GetShowVideoStreamsByFileIDRow struct {
	ID             int64          `json:"id"`
	FileID         int64          `json:"file_id"`
	StreamIndex    int64          `json:"stream_index"`
	Codec          string         `json:"codec"`
	CodecProfile   sql.NullString `json:"codec_profile"`
	CodecLevel     sql.NullInt64  `json:"codec_level"`
	BitRate        int64          `json:"bit_rate"`
	Width          int64          `json:"width"`
	Height         int64          `json:"height"`
	CodedWidth     sql.NullInt64  `json:"coded_width"`
	CodedHeight    sql.NullInt64  `json:"coded_height"`
	AspectRatio    sql.NullString `json:"aspect_ratio"`
	FrameRate      float64        `json:"frame_rate"`
	AvgFrameRate   sql.NullString `json:"avg_frame_rate"`
	BitDepth       sql.NullInt64  `json:"bit_depth"`
	PixelFormat    sql.NullString `json:"pixel_format"`
	ColorRange     sql.NullString `json:"color_range"`
	ColorSpace     sql.NullString `json:"color_space"`
	ColorPrimaries sql.NullString `json:"color_primaries"`
	ColorTransfer  sql.NullString `json:"color_transfer"`
	FieldOrder     sql.NullString `json:"field_order"`
	Rotation       sql.NullInt64  `json:"rotation"`
	Language       sql.NullString `json:"language"`
	Title          sql.NullString `json:"title"`
}

// Video streams of a show file, in the same order the movie twin uses.
func (q *Queries) GetShowVideoStreamsByFileID(ctx context.Context, fileID int64) ([]GetShowVideoStreamsByFileIDRow, error) {
	rows, err := q.query(ctx, q.getShowVideoStreamsByFileIDStmt, getShowVideoStreamsByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShowVideoStreamsByFileIDRow{}
	for rows.Next() {
		var i GetShowVideoStreamsByFileIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.StreamIndex,
			&i.Codec,
			&i.CodecProfile,
			&i.CodecLevel,
			&i.BitRate,
			&i.Width,
			&i.Height,
			&i.CodedWidth,
			&i.CodedHeight,
			&i.AspectRatio,
			&i.FrameRate,
			&i.AvgFrameRate,
			&i.BitDepth,
			&i.PixelFormat,
			&i.ColorRange,
			&i.ColorSpace,
			&i.ColorPrimaries,
			&i.ColorTransfer,
			&i.FieldOrder,
			&i.Rotation,
			&i.Language,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertShowAudioStream = `-- name: InsertShowAudioStream :exec
INSERT INTO show_audio_streams (
  file_id,
  stream_index,
  codec,
  codec_profile,
  bit_rate,
  sample_rate,
  channels,
  channel_layout,
  language,
  title,
  is_default
)
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertShowAudioStreamParams struct {
	FileID        int64          `json:"file_id"`
	StreamIndex   int64          `json:"stream_index"`
	Codec         string         `json:"codec"`
	CodecProfile  sql.NullString `json:"codec_profile"`
	BitRate       int64          `json:"bit_rate"`
	SampleRate    sql.NullInt64  `json:"sample_rate"`
	Channels      int64          `json:"channels"`
	ChannelLayout sql.NullString `json:"channel_layout"`
	Language      sql.NullString `json:"language"`
	Title         sql.NullString `json:"title"`
	IsDefault     bool           `json:"is_default"`
}

func (q *Queries) InsertShowAudioStream(ctx context.Context, arg InsertShowAudioStreamParams) error {
	_, err := q.exec(ctx, q.insertShowAudioStreamStmt, insertShowAudioStream,
		arg.FileID,
		arg.StreamIndex,
		arg.Codec,
		arg.CodecProfile,
		arg.BitRate,
		arg.SampleRate,
		arg.Channels,
		arg.ChannelLayout,
		arg.Language,
		arg.Title,
		arg.IsDefault,
	)
	return err
}

const insertShowChapter = `-- name: InsertShowChapter :exec
INSERT INTO show_chapters (
  file_id,
  title,
  start_time,
  thumb
)
VALUES
  (?, ?, ?, ?)
`

type InsertShowChapterParams struct {
	FileID    int64          `json:"file_id"`
	Title     string         `json:"title"`
	StartTime int64          `json:"start_time"`
	Thumb     sql.NullString `json:"thumb"`
}

func (q *Queries) InsertShowChapter(ctx context.Context, arg InsertShowChapterParams) error {
	_, err := q.exec(ctx, q.insertShowChapterStmt, insertShowChapter,
		arg.FileID,
		arg.Title,
		arg.StartTime,
		arg.Thumb,
	)
	return err
}

const insertShowSubtitle = `-- name: InsertShowSubtitle :exec
INSERT INTO show_subtitles (
  file_id,
  stream_index,
  codec,
  language,
  title,
  is_forced,
  is_default
)
VALUES
  (?, ?, ?, ?, ?, ?, ?)
`

type InsertShowSubtitleParams struct {
	FileID      int64          `json:"file_id"`
	StreamIndex int64          `json:"stream_index"`
	Codec       string         `json:"codec"`
	Language    sql.NullString `json:"language"`
	Title       sql.NullString `json:"title"`
	IsForced    bool           `json:"is_forced"`
	IsDefault   bool           `json:"is_default"`
}

func (q *Queries) InsertShowSubtitle(ctx context.Context, arg InsertShowSubtitleParams) error {
	_, err := q.exec(ctx, q.insertShowSubtitleStmt, insertShowSubtitle,
		arg.FileID,
		arg.StreamIndex,
		arg.Codec,
		arg.Language,
		arg.Title,
		arg.IsForced,
		arg.IsDefault,
	)
	return err
}

const insertShowVideoStream = `-- name: InsertShowVideoStream :exec
INSERT INTO show_video_streams (
  file_id,
  stream_index,
  codec,
  codec_profile,
  codec_level,
  bit_rate,
  width,
  height,
  coded_width,
  coded_height,
  aspect_ratio,
  frame_rate,
  avg_frame_rate,
  bit_depth,
  pixel_format,
  color_range,
  color_space,
  color_primaries,
  color_transfer,
  field_order,
  rotation,
  language,
  title
)
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertShowVideoStreamParams struct {
	FileID         int64          `json:"file_id"`
	StreamIndex    int64          `json:"stream_index"`
	Codec          string         `json:"codec"`
	CodecProfile   sql.NullString `json:"codec_profile"`
	CodecLevel     sql.NullInt64  `json:"codec_level"`
	BitRate        int64          `json:"bit_rate"`
	Width          int64          `json:"width"`
	Height         int64          `json:"height"`
	CodedWidth     sql.NullInt64  `json:"coded_width"`
	CodedHeight    sql.NullInt64  `json:"coded_height"`
	AspectRatio    sql.NullString `json:"aspect_ratio"`
	FrameRate      float64        `json:"frame_rate"`
	AvgFrameRate   sql.NullString `json:"avg_frame_rate"`
	BitDepth       sql.NullInt64  `json:"bit_depth"`
	PixelFormat    sql.NullString `json:"pixel_format"`
	ColorRange     sql.NullString `json:"color_range"`
	ColorSpace     sql.NullString `json:"color_space"`
	ColorPrimaries sql.NullString `json:"color_primaries"`
	ColorTransfer  sql.NullString `json:"color_transfer"`
	FieldOrder     sql.NullString `json:"field_order"`
	Rotation       sql.NullInt64  `json:"rotation"`
	Language       sql.NullString `json:"language"`
	Title          sql.NullString `json:"title"`
}

func (q *Queries) InsertShowVideoStream(ctx context.Context, arg InsertShowVideoStreamParams) error {
	_, err := q.exec(ctx, q.insertShowVideoStreamStmt, insertShowVideoStream,
		arg.FileID,
		arg.StreamIndex,
		arg.Codec,
		arg.CodecProfile,
		arg.CodecLevel,
		arg.BitRate,
		arg.Width,
		arg.Height,
		arg.CodedWidth,
		arg.CodedHeight,
		arg.AspectRatio,
		arg.FrameRate,
		arg.AvgFrameRate,
		arg.BitDepth,
		arg.PixelFormat,
		arg.ColorRange,
		arg.ColorSpace,
		arg.ColorPrimaries,
		arg.ColorTransfer,
		arg.FieldOrder,
		arg.Rotation,
		arg.Language,
		arg.Title,
	)
	return err
}

const linkShowEpisodeFile = `-- name: LinkShowEpisodeFile :exec
INSERT INTO show_episode_files (episode_id, file_id, season_id, episode_order) VALUES (?, ?, ?, ?)
`

type LinkShowEpisodeFileParams struct {
	EpisodeID    int64 `json:"episode_id"`
	FileID       int64 `json:"file_id"`
	SeasonID     int64 `json:"season_id"`
	EpisodeOrder int64 `json:"episode_order"`
}

func (q *Queries) LinkShowEpisodeFile(ctx context.Context, arg LinkShowEpisodeFileParams) error {
	_, err := q.exec(ctx, q.linkShowEpisodeFileStmt, linkShowEpisodeFile,
		arg.EpisodeID,
		arg.FileID,
		arg.SeasonID,
		arg.EpisodeOrder,
	)
	return err
}

const markShowEpisodeRetry = `-- name: MarkShowEpisodeRetry :exec
INSERT INTO show_episode_tmdb_retries (episode_id) VALUES (?) ON CONFLICT DO NOTHING
`

func (q *Queries) MarkShowEpisodeRetry(ctx context.Context, episodeID int64) error {
	_, err := q.exec(ctx, q.markShowEpisodeRetryStmt, markShowEpisodeRetry, episodeID)
	return err
}

const markShowRetry = `-- name: MarkShowRetry :exec
INSERT INTO show_tmdb_retries (show_id) VALUES (?) ON CONFLICT (show_id) DO UPDATE SET attempts = 0, last_attempt_at = NULL
`

func (q *Queries) MarkShowRetry(ctx context.Context, showID int64) error {
	_, err := q.exec(ctx, q.markShowRetryStmt, markShowRetry, showID)
	return err
}

const markShowSeasonRetry = `-- name: MarkShowSeasonRetry :exec
INSERT INTO show_season_tmdb_retries (season_id) VALUES (?) ON CONFLICT DO NOTHING
`

func (q *Queries) MarkShowSeasonRetry(ctx context.Context, seasonID int64) error {
	_, err := q.exec(ctx, q.markShowSeasonRetryStmt, markShowSeasonRetry, seasonID)
	return err
}

const pruneShow = `-- name: PruneShow :exec
DELETE FROM shows WHERE shows.id = ? AND NOT EXISTS (SELECT 1 FROM show_seasons s WHERE s.show_id = shows.id)
`

func (q *Queries) PruneShow(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.pruneShowStmt, pruneShow, id)
	return err
}

const pruneShowSeason = `-- name: PruneShowSeason :one
DELETE FROM show_seasons WHERE show_seasons.id = ? AND NOT EXISTS (SELECT 1 FROM show_files f WHERE f.season_id = show_seasons.id) RETURNING show_id
`

func (q *Queries) PruneShowSeason(ctx context.Context, id int64) (int64, error) {
	row := q.queryRow(ctx, q.pruneShowSeasonStmt, pruneShowSeason, id)
	var show_id int64
	err := row.Scan(&show_id)
	return show_id, err
}

const pruneShowSeasonEpisodes = `-- name: PruneShowSeasonEpisodes :exec
DELETE FROM show_episodes WHERE show_episodes.season_id = ? AND NOT EXISTS (SELECT 1 FROM show_episode_files l WHERE l.episode_id = show_episodes.id)
`

// Pruning is scoped to the season a file change touched: cascades leave the
// catalog rows behind, and a full-table NOT EXISTS per file did not scale.
func (q *Queries) PruneShowSeasonEpisodes(ctx context.Context, seasonID int64) error {
	_, err := q.exec(ctx, q.pruneShowSeasonEpisodesStmt, pruneShowSeasonEpisodes, seasonID)
	return err
}

const recordShowTmdbMiss = `-- name: RecordShowTmdbMiss :exec
INSERT INTO show_tmdb_retries (show_id, attempts, last_attempt_at) VALUES (?, 1, ?)
ON CONFLICT (show_id) DO UPDATE SET attempts = show_tmdb_retries.attempts + 1, last_attempt_at = excluded.last_attempt_at
`

type RecordShowTmdbMissParams struct {
	ShowID        int64         `json:"show_id"`
	LastAttemptAt sql.NullInt64 `json:"last_attempt_at"`
}

func (q *Queries) RecordShowTmdbMiss(ctx context.Context, arg RecordShowTmdbMissParams) error {
	_, err := q.exec(ctx, q.recordShowTmdbMissStmt, recordShowTmdbMiss, arg.ShowID, arg.LastAttemptAt)
	return err
}

const updateShowEpisodeMetadata = `-- name: UpdateShowEpisodeMetadata :exec
UPDATE show_episodes SET name = ?, tmdb_id = ?, overview = ?, air_date = ?, still_path = ?, production_code = ?, tmdb_runtime = ?, vote_average = ?, vote_count = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateShowEpisodeMetadataParams struct {
	Name           string          `json:"name"`
	TmdbID         sql.NullInt64   `json:"tmdb_id"`
	Overview       sql.NullString  `json:"overview"`
	AirDate        sql.NullString  `json:"air_date"`
	StillPath      sql.NullString  `json:"still_path"`
	ProductionCode sql.NullString  `json:"production_code"`
	TmdbRuntime    sql.NullInt64   `json:"tmdb_runtime"`
	VoteAverage    sql.NullFloat64 `json:"vote_average"`
	VoteCount      sql.NullInt64   `json:"vote_count"`
	ID             int64           `json:"id"`
}

func (q *Queries) UpdateShowEpisodeMetadata(ctx context.Context, arg UpdateShowEpisodeMetadataParams) error {
	_, err := q.exec(ctx, q.updateShowEpisodeMetadataStmt, updateShowEpisodeMetadata,
		arg.Name,
		arg.TmdbID,
		arg.Overview,
		arg.AirDate,
		arg.StillPath,
		arg.ProductionCode,
		arg.TmdbRuntime,
		arg.VoteAverage,
		arg.VoteCount,
		arg.ID,
	)
	return err
}

const updateShowMetadata = `-- name: UpdateShowMetadata :exec
UPDATE shows SET name = ?, tmdb_id = ?, imdb_id = ?, original_name = ?, overview = ?, tagline = ?, language = ?, origin_countries = ?, first_air_date = ?, last_air_date = ?, status = ?, type = ?, adult = ?, poster_path = ?, backdrop_path = ?, homepage = ?, vote_average = ?, vote_count = ?, popularity = ?, certification = ?, tmdb_season_count = ?, tmdb_episode_count = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateShowMetadataParams struct {
	Name             string          `json:"name"`
	TmdbID           sql.NullInt64   `json:"tmdb_id"`
	ImdbID           sql.NullString  `json:"imdb_id"`
	OriginalName     sql.NullString  `json:"original_name"`
	Overview         sql.NullString  `json:"overview"`
	Tagline          sql.NullString  `json:"tagline"`
	Language         sql.NullString  `json:"language"`
	OriginCountries  sql.NullString  `json:"origin_countries"`
	FirstAirDate     sql.NullString  `json:"first_air_date"`
	LastAirDate      sql.NullString  `json:"last_air_date"`
	Status           sql.NullString  `json:"status"`
	Type             sql.NullString  `json:"type"`
	Adult            bool            `json:"adult"`
	PosterPath       sql.NullString  `json:"poster_path"`
	BackdropPath     sql.NullString  `json:"backdrop_path"`
	Homepage         sql.NullString  `json:"homepage"`
	VoteAverage      sql.NullFloat64 `json:"vote_average"`
	VoteCount        sql.NullInt64   `json:"vote_count"`
	Popularity       sql.NullFloat64 `json:"popularity"`
	Certification    sql.NullString  `json:"certification"`
	TmdbSeasonCount  sql.NullInt64   `json:"tmdb_season_count"`
	TmdbEpisodeCount sql.NullInt64   `json:"tmdb_episode_count"`
	ID               int64           `json:"id"`
}

func (q *Queries) UpdateShowMetadata(ctx context.Context, arg UpdateShowMetadataParams) error {
	_, err := q.exec(ctx, q.updateShowMetadataStmt, updateShowMetadata,
		arg.Name,
		arg.TmdbID,
		arg.ImdbID,
		arg.OriginalName,
		arg.Overview,
		arg.Tagline,
		arg.Language,
		arg.OriginCountries,
		arg.FirstAirDate,
		arg.LastAirDate,
		arg.Status,
		arg.Type,
		arg.Adult,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Homepage,
		arg.VoteAverage,
		arg.VoteCount,
		arg.Popularity,
		arg.Certification,
		arg.TmdbSeasonCount,
		arg.TmdbEpisodeCount,
		arg.ID,
	)
	return err
}

const updateShowSeasonMetadata = `-- name: UpdateShowSeasonMetadata :exec
UPDATE show_seasons SET name = ?, tmdb_id = ?, overview = ?, air_date = ?, poster_path = ?, vote_average = ?, tmdb_episode_count = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateShowSeasonMetadataParams struct {
	Name             string          `json:"name"`
	TmdbID           sql.NullInt64   `json:"tmdb_id"`
	Overview         sql.NullString  `json:"overview"`
	AirDate          sql.NullString  `json:"air_date"`
	PosterPath       sql.NullString  `json:"poster_path"`
	VoteAverage      sql.NullFloat64 `json:"vote_average"`
	TmdbEpisodeCount sql.NullInt64   `json:"tmdb_episode_count"`
	ID               int64           `json:"id"`
}

func (q *Queries) UpdateShowSeasonMetadata(ctx context.Context, arg UpdateShowSeasonMetadataParams) error {
	_, err := q.exec(ctx, q.updateShowSeasonMetadataStmt, updateShowSeasonMetadata,
		arg.Name,
		arg.TmdbID,
		arg.Overview,
		arg.AirDate,
		arg.PosterPath,
		arg.VoteAverage,
		arg.TmdbEpisodeCount,
		arg.ID,
	)
	return err
}

const upsertLocalShow = `-- name: UpsertLocalShow :one
INSERT INTO shows (directory_path, local_name, premiere_year, name) VALUES (?, ?, ?, ?) ON CONFLICT (directory_path) DO UPDATE SET id = shows.id RETURNING id, directory_path, local_name, premiere_year, name, tmdb_id, imdb_id, original_name, overview, tagline, language, origin_countries, first_air_date, last_air_date, status, type, adult, poster_path, backdrop_path, homepage, vote_average, vote_count, popularity, certification, tmdb_season_count, tmdb_episode_count, created_at, updated_at
`

type UpsertLocalShowParams struct {
	DirectoryPath string        `json:"directory_path"`
	LocalName     string        `json:"local_name"`
	PremiereYear  sql.NullInt64 `json:"premiere_year"`
	Name          string        `json:"name"`
}

func (q *Queries) UpsertLocalShow(ctx context.Context, arg UpsertLocalShowParams) (Show, error) {
	row := q.queryRow(ctx, q.upsertLocalShowStmt, upsertLocalShow,
		arg.DirectoryPath,
		arg.LocalName,
		arg.PremiereYear,
		arg.Name,
	)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.DirectoryPath,
		&i.LocalName,
		&i.PremiereYear,
		&i.Name,
		&i.TmdbID,
		&i.ImdbID,
		&i.OriginalName,
		&i.Overview,
		&i.Tagline,
		&i.Language,
		&i.OriginCountries,
		&i.FirstAirDate,
		&i.LastAirDate,
		&i.Status,
		&i.Type,
		&i.Adult,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Homepage,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Popularity,
		&i.Certification,
		&i.TmdbSeasonCount,
		&i.TmdbEpisodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLocalShowEpisode = `-- name: UpsertLocalShowEpisode :one
INSERT INTO show_episodes (season_id, episode_number, name) VALUES (?, ?, ?) ON CONFLICT (season_id, episode_number) DO UPDATE SET id = show_episodes.id RETURNING id, season_id, episode_number, name, tmdb_id, overview, air_date, still_path, production_code, tmdb_runtime, vote_average, vote_count, created_at, updated_at
`

type UpsertLocalShowEpisodeParams struct {
	SeasonID      int64  `json:"season_id"`
	EpisodeNumber int64  `json:"episode_number"`
	Name          string `json:"name"`
}

func (q *Queries) UpsertLocalShowEpisode(ctx context.Context, arg UpsertLocalShowEpisodeParams) (ShowEpisode, error) {
	row := q.queryRow(ctx, q.upsertLocalShowEpisodeStmt, upsertLocalShowEpisode, arg.SeasonID, arg.EpisodeNumber, arg.Name)
	var i ShowEpisode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.EpisodeNumber,
		&i.Name,
		&i.TmdbID,
		&i.Overview,
		&i.AirDate,
		&i.StillPath,
		&i.ProductionCode,
		&i.TmdbRuntime,
		&i.VoteAverage,
		&i.VoteCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLocalShowSeason = `-- name: UpsertLocalShowSeason :one
INSERT INTO show_seasons (show_id, season_number, name) VALUES (?, ?, ?) ON CONFLICT (show_id, season_number) DO UPDATE SET id = show_seasons.id RETURNING id, show_id, season_number, name, tmdb_id, overview, air_date, poster_path, vote_average, tmdb_episode_count, created_at, updated_at
`

type UpsertLocalShowSeasonParams struct {
	ShowID       int64  `json:"show_id"`
	SeasonNumber int64  `json:"season_number"`
	Name         string `json:"name"`
}

func (q *Queries) UpsertLocalShowSeason(ctx context.Context, arg UpsertLocalShowSeasonParams) (ShowSeason, error) {
	row := q.queryRow(ctx, q.upsertLocalShowSeasonStmt, upsertLocalShowSeason, arg.ShowID, arg.SeasonNumber, arg.Name)
	var i ShowSeason
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.SeasonNumber,
		&i.Name,
		&i.TmdbID,
		&i.Overview,
		&i.AirDate,
		&i.PosterPath,
		&i.VoteAverage,
		&i.TmdbEpisodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNetwork = `-- name: UpsertNetwork :one
INSERT INTO networks (tmdb_id, name, logo, country) VALUES (?, ?, ?, ?) ON CONFLICT (tmdb_id) DO UPDATE SET name = excluded.name, logo = excluded.logo, country = excluded.country RETURNING id, tmdb_id, name, logo, country
`

type UpsertNetworkParams struct {
	TmdbID  int64          `json:"tmdb_id"`
	Name    string         `json:"name"`
	Logo    sql.NullString `json:"logo"`
	Country sql.NullString `json:"country"`
}

func (q *Queries) UpsertNetwork(ctx context.Context, arg UpsertNetworkParams) (Network, error) {
	row := q.queryRow(ctx, q.upsertNetworkStmt, upsertNetwork,
		arg.TmdbID,
		arg.Name,
		arg.Logo,
		arg.Country,
	)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Name,
		&i.Logo,
		&i.Country,
	)
	return i, err
}

const upsertShowFile = `-- name: UpsertShowFile :one
INSERT INTO show_files (season_id, file_path, file_name, size, container, mime_type, duration) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (file_path) DO UPDATE SET size = excluded.size, container = excluded.container, mime_type = excluded.mime_type, duration = excluded.duration, updated_at = CURRENT_TIMESTAMP RETURNING id, season_id, file_path, file_name, size, container, mime_type, duration, created_at, updated_at
`

type UpsertShowFileParams struct {
	SeasonID  int64           `json:"season_id"`
	FilePath  string          `json:"file_path"`
	FileName  string          `json:"file_name"`
	Size      int64           `json:"size"`
	Container string          `json:"container"`
	MimeType  string          `json:"mime_type"`
	Duration  sql.NullFloat64 `json:"duration"`
}

func (q *Queries) UpsertShowFile(ctx context.Context, arg UpsertShowFileParams) (ShowFile, error) {
	row := q.queryRow(ctx, q.upsertShowFileStmt, upsertShowFile,
		arg.SeasonID,
		arg.FilePath,
		arg.FileName,
		arg.Size,
		arg.Container,
		arg.MimeType,
		arg.Duration,
	)
	var i ShowFile
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.FilePath,
		&i.FileName,
		&i.Size,
		&i.Container,
		&i.MimeType,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertShowFingerprint = `-- name: UpsertShowFingerprint :exec
INSERT INTO show_file_fingerprints (file_id, mtime_ns, ctime_ns, device, inode) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (file_id) DO UPDATE SET mtime_ns = excluded.mtime_ns, ctime_ns = excluded.ctime_ns, device = excluded.device, inode = excluded.inode
`

type UpsertShowFingerprintParams struct {
	FileID  int64  `json:"file_id"`
	MtimeNs int64  `json:"mtime_ns"`
	CtimeNs int64  `json:"ctime_ns"`
	Device  string `json:"device"`
	Inode   string `json:"inode"`
}

func (q *Queries) UpsertShowFingerprint(ctx context.Context, arg UpsertShowFingerprintParams) error {
	_, err := q.exec(ctx, q.upsertShowFingerprintStmt, upsertShowFingerprint,
		arg.FileID,
		arg.MtimeNs,
		arg.CtimeNs,
		arg.Device,
		arg.Inode,
	)
	return err
}
