// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: show_remux_safety_verdicts.sql

package database

import (
	"context"
)

const getShowRemuxSafetyVerdict = `-- name: GetShowRemuxSafetyVerdict :one
SELECT
  fingerprint,
  safe,
  reason
FROM show_remux_safety_verdicts
WHERE file_id = ?
  AND stream_index = ?
`

type GetShowRemuxSafetyVerdictParams struct {
	FileID      int64 `json:"file_id"`
	StreamIndex int64 `json:"stream_index"`
}

type GetShowRemuxSafetyVerdictRow struct {
	Fingerprint string `json:"fingerprint"`
	Safe        bool   `json:"safe"`
	Reason      string `json:"reason"`
}

// Persisted remux-safety verdict for one video stream of a show file; the
// caller compares the stored fingerprint and treats a mismatch as a miss.
func (q *Queries) GetShowRemuxSafetyVerdict(ctx context.Context, arg GetShowRemuxSafetyVerdictParams) (GetShowRemuxSafetyVerdictRow, error) {
	row := q.queryRow(ctx, q.getShowRemuxSafetyVerdictStmt, getShowRemuxSafetyVerdict, arg.FileID, arg.StreamIndex)
	var i GetShowRemuxSafetyVerdictRow
	err := row.Scan(&i.Fingerprint, &i.Safe, &i.Reason)
	return i, err
}

const upsertShowRemuxSafetyVerdict = `-- name: UpsertShowRemuxSafetyVerdict :exec
INSERT INTO show_remux_safety_verdicts (
  file_id,
  stream_index,
  fingerprint,
  safe,
  reason
)
VALUES
  (?, ?, ?, ?, ?)
ON CONFLICT (file_id, stream_index) DO UPDATE
SET
  fingerprint = excluded.fingerprint,
  safe = excluded.safe,
  reason = excluded.reason
`

type UpsertShowRemuxSafetyVerdictParams struct {
	FileID      int64  `json:"file_id"`
	StreamIndex int64  `json:"stream_index"`
	Fingerprint string `json:"fingerprint"`
	Safe        bool   `json:"safe"`
	Reason      string `json:"reason"`
}

func (q *Queries) UpsertShowRemuxSafetyVerdict(ctx context.Context, arg UpsertShowRemuxSafetyVerdictParams) error {
	_, err := q.exec(ctx, q.upsertShowRemuxSafetyVerdictStmt, upsertShowRemuxSafetyVerdict,
		arg.FileID,
		arg.StreamIndex,
		arg.Fingerprint,
		arg.Safe,
		arg.Reason,
	)
	return err
}
