// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: show_keyframe_indexes.sql

package database

import (
	"context"
)

const getShowKeyframeIndex = `-- name: GetShowKeyframeIndex :one
SELECT
  fingerprint,
  duration_sec,
  keyframes
FROM show_keyframe_indexes
WHERE file_id = ?
  AND stream_index = ?
`

type GetShowKeyframeIndexParams struct {
	FileID      int64 `json:"file_id"`
	StreamIndex int64 `json:"stream_index"`
}

type GetShowKeyframeIndexRow struct {
	Fingerprint string  `json:"fingerprint"`
	DurationSec float64 `json:"duration_sec"`
	Keyframes   string  `json:"keyframes"`
}

// Persisted keyframe index for one video stream of a show file; the caller
// compares the stored fingerprint and treats a mismatch as a miss.
func (q *Queries) GetShowKeyframeIndex(ctx context.Context, arg GetShowKeyframeIndexParams) (GetShowKeyframeIndexRow, error) {
	row := q.queryRow(ctx, q.getShowKeyframeIndexStmt, getShowKeyframeIndex, arg.FileID, arg.StreamIndex)
	var i GetShowKeyframeIndexRow
	err := row.Scan(&i.Fingerprint, &i.DurationSec, &i.Keyframes)
	return i, err
}

const upsertShowKeyframeIndex = `-- name: UpsertShowKeyframeIndex :exec
INSERT INTO show_keyframe_indexes (
  file_id,
  stream_index,
  fingerprint,
  duration_sec,
  keyframes
)
VALUES
  (?, ?, ?, ?, ?)
ON CONFLICT (file_id, stream_index) DO UPDATE
SET
  fingerprint = excluded.fingerprint,
  duration_sec = excluded.duration_sec,
  keyframes = excluded.keyframes
`

type UpsertShowKeyframeIndexParams struct {
	FileID      int64   `json:"file_id"`
	StreamIndex int64   `json:"stream_index"`
	Fingerprint string  `json:"fingerprint"`
	DurationSec float64 `json:"duration_sec"`
	Keyframes   string  `json:"keyframes"`
}

func (q *Queries) UpsertShowKeyframeIndex(ctx context.Context, arg UpsertShowKeyframeIndexParams) error {
	_, err := q.exec(ctx, q.upsertShowKeyframeIndexStmt, upsertShowKeyframeIndex,
		arg.FileID,
		arg.StreamIndex,
		arg.Fingerprint,
		arg.DurationSec,
		arg.Keyframes,
	)
	return err
}
