// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subtitles.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubtitle = `-- name: CreateSubtitle :one
INSERT INTO subtitles (
    title,
    subtitle_index,
    codec,
    language,
    movie_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, created_at, updated_at, title, subtitle_index, codec, language, movie_id
`

type CreateSubtitleParams struct {
	Title         string      `json:"title"`
	SubtitleIndex int32       `json:"subtitle_index"`
	Codec         string      `json:"codec"`
	Language      string      `json:"language"`
	MovieID       pgtype.Int4 `json:"movie_id"`
}

func (q *Queries) CreateSubtitle(ctx context.Context, arg CreateSubtitleParams) (Subtitle, error) {
	row := q.db.QueryRow(ctx, createSubtitle,
		arg.Title,
		arg.SubtitleIndex,
		arg.Codec,
		arg.Language,
		arg.MovieID,
	)
	var i Subtitle
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.SubtitleIndex,
		&i.Codec,
		&i.Language,
		&i.MovieID,
	)
	return i, err
}
