// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track_genres.sql

package database

import (
	"context"
)

const checkTrackGenreExists = `-- name: CheckTrackGenreExists :one
SELECT EXISTS(
    SELECT 1 FROM track_genres WHERE track_id = $1 AND genre_id = $2
) as exists
`

type CheckTrackGenreExistsParams struct {
	TrackID int32 `json:"track_id"`
	GenreID int32 `json:"genre_id"`
}

func (q *Queries) CheckTrackGenreExists(ctx context.Context, arg CheckTrackGenreExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTrackGenreExists, arg.TrackID, arg.GenreID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTrackGenre = `-- name: CreateTrackGenre :exec
INSERT INTO track_genres (
    track_id, genre_id
) VALUES (
    $1, $2
)
`

type CreateTrackGenreParams struct {
	TrackID int32 `json:"track_id"`
	GenreID int32 `json:"genre_id"`
}

func (q *Queries) CreateTrackGenre(ctx context.Context, arg CreateTrackGenreParams) error {
	_, err := q.db.Exec(ctx, createTrackGenre, arg.TrackID, arg.GenreID)
	return err
}
