// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track_musicians.sql

package database

import (
	"context"
)

const createTrackMusician = `-- name: CreateTrackMusician :exec
INSERT INTO track_musicians (
  track_id,
  musician_id
)
VALUES
  (?, ?)
ON CONFLICT (track_id, musician_id) DO NOTHING
`

type CreateTrackMusicianParams struct {
	TrackID    int64 `json:"track_id"`
	MusicianID int64 `json:"musician_id"`
}

func (q *Queries) CreateTrackMusician(ctx context.Context, arg CreateTrackMusicianParams) error {
	_, err := q.exec(ctx, q.createTrackMusicianStmt, createTrackMusician, arg.TrackID, arg.MusicianID)
	return err
}

const deleteTrackMusicians = `-- name: DeleteTrackMusicians :exec
DELETE FROM track_musicians
WHERE track_id = ?
`

func (q *Queries) DeleteTrackMusicians(ctx context.Context, trackID int64) error {
	_, err := q.exec(ctx, q.deleteTrackMusiciansStmt, deleteTrackMusicians, trackID)
	return err
}

const getMusicianIDsByTrackID = `-- name: GetMusicianIDsByTrackID :many
SELECT musician_id FROM track_musicians WHERE track_id = ?
`

func (q *Queries) GetMusicianIDsByTrackID(ctx context.Context, trackID int64) ([]int64, error) {
	rows, err := q.query(ctx, q.getMusicianIDsByTrackIDStmt, getMusicianIDsByTrackID, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var musician_id int64
		if err := rows.Scan(&musician_id); err != nil {
			return nil, err
		}
		items = append(items, musician_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
