// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: user_liked_tracks.sql

package database

import (
	"context"
	"database/sql"
)

const countUserLikedTracks = `-- name: CountUserLikedTracks :one
SELECT
  COUNT(*)
FROM user_liked_tracks
WHERE user_id = ?
`

func (q *Queries) CountUserLikedTracks(ctx context.Context, userID int64) (int64, error) {
	row := q.queryRow(ctx, q.countUserLikedTracksStmt, countUserLikedTracks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLikedTrackIDsByUserID = `-- name: GetLikedTrackIDsByUserID :many
SELECT
  track_id
FROM user_liked_tracks
WHERE user_id = ?
`

func (q *Queries) GetLikedTrackIDsByUserID(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.query(ctx, q.getLikedTrackIDsByUserIDStmt, getLikedTrackIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var track_id int64
		if err := rows.Scan(&track_id); err != nil {
			return nil, err
		}
		items = append(items, track_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikedTracksForUser = `-- name: GetLikedTracksForUser :many
SELECT
  t.id,
  t.title,
  t.duration,
  t.codec,
  t.bit_rate,
  t.file_path,
  a.id    AS album_id,
  a.title AS album_title,
  a.cover AS album_cover,
  m.id    AS musician_id,
  m.name  AS musician_name
FROM user_liked_tracks AS ult
INNER JOIN tracks AS t ON t.id = ult.track_id
LEFT JOIN albums AS a ON t.album_id = a.id
LEFT JOIN musicians AS m ON t.musician_id = m.id
WHERE ult.user_id = ?
ORDER BY ult.created_at DESC
LIMIT ?
OFFSET ?
`

type GetLikedTracksForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetLikedTracksForUserRow struct {
	ID           int64          `json:"id"`
	Title        string         `json:"title"`
	Duration     int64          `json:"duration"`
	Codec        string         `json:"codec"`
	BitRate      int64          `json:"bit_rate"`
	FilePath     string         `json:"file_path"`
	AlbumID      sql.NullInt64  `json:"album_id"`
	AlbumTitle   sql.NullString `json:"album_title"`
	AlbumCover   sql.NullString `json:"album_cover"`
	MusicianID   sql.NullInt64  `json:"musician_id"`
	MusicianName sql.NullString `json:"musician_name"`
}

func (q *Queries) GetLikedTracksForUser(ctx context.Context, arg GetLikedTracksForUserParams) ([]GetLikedTracksForUserRow, error) {
	rows, err := q.query(ctx, q.getLikedTracksForUserStmt, getLikedTracksForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLikedTracksForUserRow{}
	for rows.Next() {
		var i GetLikedTracksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Duration,
			&i.Codec,
			&i.BitRate,
			&i.FilePath,
			&i.AlbumID,
			&i.AlbumTitle,
			&i.AlbumCover,
			&i.MusicianID,
			&i.MusicianName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTrackLiked = `-- name: IsTrackLiked :one
SELECT
  COUNT(*) > 0 AS is_liked
FROM user_liked_tracks
WHERE user_id = ?
  AND track_id = ?
`

type IsTrackLikedParams struct {
	UserID  int64 `json:"user_id"`
	TrackID int64 `json:"track_id"`
}

func (q *Queries) IsTrackLiked(ctx context.Context, arg IsTrackLikedParams) (bool, error) {
	row := q.queryRow(ctx, q.isTrackLikedStmt, isTrackLiked, arg.UserID, arg.TrackID)
	var is_liked bool
	err := row.Scan(&is_liked)
	return is_liked, err
}

const likeTrack = `-- name: LikeTrack :exec
INSERT INTO user_liked_tracks (
  user_id,
  track_id
)
VALUES
  (?, ?)
ON CONFLICT (user_id, track_id) DO NOTHING
`

type LikeTrackParams struct {
	UserID  int64 `json:"user_id"`
	TrackID int64 `json:"track_id"`
}

func (q *Queries) LikeTrack(ctx context.Context, arg LikeTrackParams) error {
	_, err := q.exec(ctx, q.likeTrackStmt, likeTrack, arg.UserID, arg.TrackID)
	return err
}

const unlikeTrack = `-- name: UnlikeTrack :exec
DELETE FROM user_liked_tracks
WHERE user_id = ?
  AND track_id = ?
`

type UnlikeTrackParams struct {
	UserID  int64 `json:"user_id"`
	TrackID int64 `json:"track_id"`
}

func (q *Queries) UnlikeTrack(ctx context.Context, arg UnlikeTrackParams) error {
	_, err := q.exec(ctx, q.unlikeTrackStmt, unlikeTrack, arg.UserID, arg.TrackID)
	return err
}
